PROMPT v4.2.0 Graph Runtime state and worker tables

CREATE TABLE GRAPH_RUNS (
    RUN_ID VARCHAR2(128) PRIMARY KEY, GRAPH_VERSION_ID VARCHAR2(128) NOT NULL, PLAN_ID VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, ACTOR_ID VARCHAR2(256) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256),
    INPUT_STATE_JSON CLOB, CURRENT_CHECKPOINT_ID VARCHAR2(128), BUDGET_JSON CLOB, BUDGET_USAGE_JSON CLOB,
    ERROR_CODE VARCHAR2(128), ERROR_MESSAGE VARCHAR2(2000), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT CK_GRAPH_RUN_STATUS CHECK (STATUS IN ('PENDING','RUNNING','WAITING','PAUSED','SUCCEEDED','FAILED','CANCELLED','MIGRATING','REVIEW_REQUIRED')),
    CONSTRAINT UK_GRAPH_RUN_IDEMPOTENCY UNIQUE (GRAPH_VERSION_ID, IDEMPOTENCY_KEY)
);
CREATE TABLE GRAPH_NODE_RUNS (
    NODE_RUN_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_KEY VARCHAR2(256) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, BRANCH_KEY VARCHAR2(256), JOIN_KEY VARCHAR2(256), ITERATION_NO NUMBER(10,0) DEFAULT 0 NOT NULL,
    INPUT_CHECKPOINT_ID VARCHAR2(128), OUTPUT_CHECKPOINT_ID VARCHAR2(128), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT FK_GRAPH_NODE_RUN_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID),
    CONSTRAINT CK_GRAPH_NODE_RUN_STATUS CHECK (STATUS IN ('PENDING','READY','RUNNING','WAITING','SUCCEEDED','FAILED','CANCELLED','SKIPPED','REVIEW_REQUIRED')),
    CONSTRAINT UK_GRAPH_NODE_RUN UNIQUE (RUN_ID, NODE_KEY, ITERATION_NO, BRANCH_KEY)
);
CREATE TABLE GRAPH_READY_NODES (
    READY_ID VARCHAR2(128) PRIMARY KEY, NODE_RUN_ID VARCHAR2(128) NOT NULL, RUN_ID VARCHAR2(128) NOT NULL, NODE_KEY VARCHAR2(256) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'READY' NOT NULL, PRIORITY NUMBER(10,0) DEFAULT 5 NOT NULL, AVAILABLE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DEADLINE_AT TIMESTAMP, REQUIRED_CAPABILITY_JSON CLOB, RESOURCE_CLASS VARCHAR2(128), CLAIMED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_READY_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID), CONSTRAINT FK_GRAPH_READY_NODE_RUN FOREIGN KEY (NODE_RUN_ID) REFERENCES GRAPH_NODE_RUNS(NODE_RUN_ID),
    CONSTRAINT CK_GRAPH_READY_STATUS CHECK (STATUS IN ('READY','CLAIMED','WAITING','DONE','CANCELLED'))
);
CREATE TABLE GRAPH_ATTEMPTS (
    ATTEMPT_ID VARCHAR2(128) PRIMARY KEY, NODE_RUN_ID VARCHAR2(128) NOT NULL, RUN_ID VARCHAR2(128) NOT NULL, WORKER_ID VARCHAR2(256),
    STATUS VARCHAR2(32) DEFAULT 'CLAIMED' NOT NULL, FENCING_TOKEN NUMBER(20,0) NOT NULL, LEASE_TOKEN_HASH VARCHAR2(128), LEASE_EXPIRES_AT TIMESTAMP,
    INPUT_STATE_JSON CLOB, OUTPUT_STATE_JSON CLOB, RESULT_ARTIFACT_ID VARCHAR2(128), IDEMPOTENCY_KEY VARCHAR2(256), EFFECT_IDEMPOTENCY_KEY VARCHAR2(256), ERROR_CODE VARCHAR2(128), ERROR_MESSAGE VARCHAR2(2000),
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, CONSTRAINT FK_GRAPH_ATTEMPT_NODE_RUN FOREIGN KEY (NODE_RUN_ID) REFERENCES GRAPH_NODE_RUNS(NODE_RUN_ID),
    CONSTRAINT FK_GRAPH_ATTEMPT_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID), CONSTRAINT CK_GRAPH_ATTEMPT_STATUS CHECK (STATUS IN ('CLAIMED','RUNNING','WAITING','SUCCEEDED','FAILED','CANCELLED','STALE','REVIEW_REQUIRED')),
    CONSTRAINT UK_GRAPH_ATTEMPT_IDEMPOTENCY UNIQUE (NODE_RUN_ID, IDEMPOTENCY_KEY)
);
CREATE TABLE GRAPH_STATE_EVENTS (
    EVENT_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, SEQ_NO NUMBER(20,0) NOT NULL, CHECKPOINT_ID VARCHAR2(128), PRIOR_CHECKPOINT_ID VARCHAR2(128), SOURCE_ATTEMPT_ID VARCHAR2(128),
    DELTA_JSON CLOB NOT NULL, REDUCER_JSON CLOB, STATE_HASH VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_STATE_EVENT_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID), CONSTRAINT UK_GRAPH_STATE_EVENT_SEQ UNIQUE (RUN_ID, SEQ_NO)
);
CREATE TABLE GRAPH_CHECKPOINTS (
    CHECKPOINT_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, SEQ_NO NUMBER(20,0) NOT NULL, PARENT_CHECKPOINT_ID VARCHAR2(128), STATE_JSON CLOB NOT NULL,
    STATE_HASH VARCHAR2(128) NOT NULL, SNAPSHOT_KIND VARCHAR2(32) DEFAULT 'DELTA' NOT NULL, BRANCH_ID VARCHAR2(128), ACTOR_ID VARCHAR2(256) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_CHECKPOINT_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID), CONSTRAINT CK_GRAPH_CHECKPOINT_KIND CHECK (SNAPSHOT_KIND IN ('DELTA','FULL','FORK','MIGRATION','INTERVENTION'))
);
CREATE TABLE GRAPH_TRANSITIONS (
    TRANSITION_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_RUN_ID VARCHAR2(128), ATTEMPT_ID VARCHAR2(128), EDGE_ID VARCHAR2(128), FROM_NODE_KEY VARCHAR2(256), TO_NODE_KEY VARCHAR2(256),
    TRANSITION_TYPE VARCHAR2(64) NOT NULL, STATUS VARCHAR2(32) NOT NULL, CHECKPOINT_ID VARCHAR2(128), STATE_EVENT_ID VARCHAR2(128), FENCING_TOKEN NUMBER(20,0), EVIDENCE_JSON CLOB, ACTOR_ID VARCHAR2(256) NOT NULL, REASON VARCHAR2(2000), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_TRANSITION_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID), CONSTRAINT UK_GRAPH_TRANSITION_ATTEMPT UNIQUE (ATTEMPT_ID)
);
CREATE TABLE GRAPH_ARTIFACTS (
    ARTIFACT_ID VARCHAR2(128) PRIMARY KEY, CONTENT_HASH VARCHAR2(128) NOT NULL, MEDIA_TYPE VARCHAR2(256), CONTENT_SIZE NUMBER(20,0) NOT NULL, STORAGE_URI VARCHAR2(2048), CONTENT_BLOB BLOB,
    OWNER_REF VARCHAR2(256) NOT NULL, CLASSIFICATION VARCHAR2(64) DEFAULT 'INTERNAL' NOT NULL, ENCRYPTION_KEY_REF VARCHAR2(256), RETENTION_UNTIL TIMESTAMP, LEGAL_HOLD CHAR(1) DEFAULT 'N' NOT NULL, LEGAL_HOLD_ACTOR VARCHAR2(256), LEGAL_HOLD_REASON VARCHAR2(2000), LEGAL_HOLD_AT TIMESTAMP, RELEASED_BY VARCHAR2(256), RELEASE_REASON VARCHAR2(2000), RELEASED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_GRAPH_ARTIFACT_HASH UNIQUE (CONTENT_HASH), CONSTRAINT CK_GRAPH_ARTIFACT_HOLD CHECK (LEGAL_HOLD IN ('Y','N'))
);
CREATE TABLE GRAPH_WORKERS (
    WORKER_ID VARCHAR2(256) PRIMARY KEY, AGENT_ID VARCHAR2(128), RUNTIME VARCHAR2(128) NOT NULL, CAPABILITY_JSON CLOB, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, LAST_HEARTBEAT_AT TIMESTAMP, NODE_ID VARCHAR2(256), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_GRAPH_WORKER_STATUS CHECK (STATUS IN ('ACTIVE','DISABLED','REVOKED','DRAINING'))
);
CREATE TABLE GRAPH_LEASE_TOKENS (
    LEASE_ID VARCHAR2(128) PRIMARY KEY, ATTEMPT_ID VARCHAR2(128) NOT NULL, WORKER_ID VARCHAR2(256) NOT NULL, TOKEN_HASH VARCHAR2(128) NOT NULL, FENCING_TOKEN NUMBER(20,0) NOT NULL,
    OPERATIONS_JSON CLOB NOT NULL, SCOPE_JSON CLOB NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT UK_GRAPH_LEASE_ATTEMPT UNIQUE (ATTEMPT_ID)
);
CREATE TABLE GRAPH_INBOX (
    INBOX_ID VARCHAR2(128) PRIMARY KEY, SOURCE_REF VARCHAR2(256) NOT NULL, EVENT_TYPE VARCHAR2(128) NOT NULL, SCHEMA_VERSION VARCHAR2(64) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256) NOT NULL, AUTHENTICATION_JSON CLOB, PAYLOAD_JSON CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'RECEIVED' NOT NULL, RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PROCESSED_AT TIMESTAMP, ERROR_MESSAGE VARCHAR2(2000), CONSTRAINT UK_GRAPH_INBOX_KEY UNIQUE (SOURCE_REF, IDEMPOTENCY_KEY), CONSTRAINT CK_GRAPH_INBOX_STATUS CHECK (STATUS IN ('RECEIVED','PROCESSING','PROCESSED','DUPLICATE','DEAD_LETTER'))
);
CREATE TABLE GRAPH_OUTBOX (
    OUTBOX_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128), EVENT_TYPE VARCHAR2(128) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256) NOT NULL, PAYLOAD_JSON CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, ATTEMPTS NUMBER(10,0) DEFAULT 0 NOT NULL, AVAILABLE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, LAST_ERROR VARCHAR2(2000), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, SENT_AT TIMESTAMP, CONSTRAINT UK_GRAPH_OUTBOX_KEY UNIQUE (EVENT_TYPE, IDEMPOTENCY_KEY), CONSTRAINT CK_GRAPH_OUTBOX_STATUS CHECK (STATUS IN ('PENDING','DISPATCHING','SENT','DEAD_LETTER'))
);
CREATE TABLE GRAPH_EVALUATIONS (
    EVALUATION_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_RUN_ID VARCHAR2(128), EVALUATOR_NAME VARCHAR2(128) NOT NULL, EVALUATOR_VERSION VARCHAR2(64) NOT NULL, LEVEL_NAME VARCHAR2(32) NOT NULL, INPUT_JSON CLOB, RESULT_JSON CLOB, ROUTE_DECISION VARCHAR2(64), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT FK_GRAPH_EVAL_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID)
);
CREATE TABLE GRAPH_INTERVENTIONS (
    INTERVENTION_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_RUN_ID VARCHAR2(128), ACTION_NAME VARCHAR2(64) NOT NULL, ACTOR_ID VARCHAR2(256) NOT NULL, REASON VARCHAR2(2000) NOT NULL, EVIDENCE_JSON CLOB, STATUS VARCHAR2(32) DEFAULT 'APPLIED' NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT FK_GRAPH_INTERVENTION_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID)
);
CREATE INDEX IDX_GRAPH_RUN_STATUS ON GRAPH_RUNS(STATUS, UPDATED_AT);
CREATE INDEX IDX_GRAPH_READY_CLAIM ON GRAPH_READY_NODES(STATUS, AVAILABLE_AT, PRIORITY);
CREATE INDEX IDX_GRAPH_ATTEMPT_LEASE ON GRAPH_ATTEMPTS(STATUS, LEASE_EXPIRES_AT);
CREATE INDEX IDX_GRAPH_TRANSITION_RUN ON GRAPH_TRANSITIONS(RUN_ID, CREATED_AT);
CREATE INDEX IDX_GRAPH_INBOX_STATUS ON GRAPH_INBOX(STATUS, RECEIVED_AT);
CREATE INDEX IDX_GRAPH_OUTBOX_STATUS ON GRAPH_OUTBOX(STATUS, AVAILABLE_AT);
