PROMPT v4.2.0 Graph Engineering control, join, trace and migration evidence

CREATE TABLE GRAPH_JOIN_STATES (
    JOIN_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL,
    NODE_KEY VARCHAR2(256) NOT NULL, JOIN_KEY VARCHAR2(256) NOT NULL,
    STRATEGY VARCHAR2(32) NOT NULL, REQUIRED_COUNT NUMBER(10,0) DEFAULT 1 NOT NULL,
    EXPECTED_COUNT NUMBER(10,0) DEFAULT 1 NOT NULL, ACCEPTED_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'WAITING' NOT NULL, INPUTS_JSON CLOB, REDUCER_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_GRAPH_JOIN_STATUS CHECK (STATUS IN ('WAITING','READY','COMMITTED','CANCELLED','DEADLOCKED')),
    CONSTRAINT UK_GRAPH_JOIN_KEY UNIQUE (RUN_ID, NODE_KEY, JOIN_KEY)
);
CREATE TABLE GRAPH_RUN_BRANCHES (
    BRANCH_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL,
    PARENT_NODE_RUN_ID VARCHAR2(128), BRANCH_KEY VARCHAR2(256) NOT NULL, SOURCE_EDGE_ID VARCHAR2(128),
    NODE_KEY VARCHAR2(256), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    INPUT_CHECKPOINT_ID VARCHAR2(128), OUTPUT_CHECKPOINT_ID VARCHAR2(128), METADATA_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_BRANCH_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID),
    CONSTRAINT CK_GRAPH_BRANCH_STATUS CHECK (STATUS IN ('ACTIVE','SUCCEEDED','FAILED','CANCELLED','MERGED','REVIEW_REQUIRED')),
    CONSTRAINT UK_GRAPH_BRANCH_KEY UNIQUE (RUN_ID, BRANCH_KEY, NODE_KEY)
);
CREATE TABLE GRAPH_WAIT_SUBSCRIPTIONS (
    WAIT_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_RUN_ID VARCHAR2(128) NOT NULL,
    WAIT_KIND VARCHAR2(32) NOT NULL, EVENT_TYPE VARCHAR2(128), CORRELATION_KEY VARCHAR2(256),
    STATUS VARCHAR2(32) DEFAULT 'WAITING' NOT NULL, DEADLINE_AT TIMESTAMP, PAYLOAD_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, RESOLVED_AT TIMESTAMP,
    CONSTRAINT FK_GRAPH_WAIT_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID),
    CONSTRAINT UK_GRAPH_WAIT_NODE UNIQUE (NODE_RUN_ID),
    CONSTRAINT CK_GRAPH_WAIT_STATUS CHECK (STATUS IN ('WAITING','RESOLVED','EXPIRED','CANCELLED'))
);
CREATE TABLE GRAPH_TRACES (
    TRACE_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL, NODE_RUN_ID VARCHAR2(128),
    ATTEMPT_ID VARCHAR2(128), TRANSITION_ID VARCHAR2(128), EVENT_TYPE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(32), RETRY_NO NUMBER(10,0) DEFAULT 0 NOT NULL, DURATION_MS NUMBER(20,0),
    TOKEN_COUNT NUMBER(20,0), ESTIMATED_COST NUMBER(30,10), PAYLOAD_REF VARCHAR2(128), DETAIL_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_GRAPH_TRACE_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID)
);
CREATE TABLE GRAPH_RUN_MIGRATIONS (
    MIGRATION_ID VARCHAR2(128) PRIMARY KEY, RUN_ID VARCHAR2(128) NOT NULL,
    FROM_VERSION_ID VARCHAR2(128) NOT NULL, TO_VERSION_ID VARCHAR2(128) NOT NULL,
    FROM_PLAN_ID VARCHAR2(128) NOT NULL, TO_PLAN_ID VARCHAR2(128) NOT NULL,
    PRECHECKPOINT_ID VARCHAR2(128), STATUS VARCHAR2(32) NOT NULL, MAPPING_JSON CLOB,
    ACTOR_ID VARCHAR2(256) NOT NULL, REASON VARCHAR2(2000) NOT NULL, ERROR_MESSAGE VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_GRAPH_MIGRATION_RUN FOREIGN KEY (RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID),
    CONSTRAINT CK_GRAPH_MIGRATION_STATUS CHECK (STATUS IN ('VALIDATING','APPLIED','FAILED','ROLLED_BACK'))
);
CREATE TABLE GRAPH_COMPAT_BINDINGS (
    BINDING_ID VARCHAR2(128) PRIMARY KEY, LEGACY_KIND VARCHAR2(64) NOT NULL,
    LEGACY_ID VARCHAR2(256) NOT NULL, GRAPH_ID VARCHAR2(128) NOT NULL,
    GRAPH_VERSION_ID VARCHAR2(128), GRAPH_RUN_ID VARCHAR2(128),
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    TOPOLOGY_STATUS VARCHAR2(32) DEFAULT 'KNOWN' NOT NULL, READ_ONLY CHAR(1) DEFAULT 'N' NOT NULL,
    REVIEW_REASON VARCHAR2(2000), METADATA_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_SYNC_AT TIMESTAMP,
    CONSTRAINT UK_GRAPH_COMPAT_LEGACY UNIQUE (LEGACY_KIND, LEGACY_ID),
    CONSTRAINT FK_GRAPH_COMPAT_GRAPH FOREIGN KEY (GRAPH_ID) REFERENCES GRAPH_DEFINITIONS(GRAPH_ID),
    CONSTRAINT FK_GRAPH_COMPAT_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID),
    CONSTRAINT FK_GRAPH_COMPAT_RUN FOREIGN KEY (GRAPH_RUN_ID) REFERENCES GRAPH_RUNS(RUN_ID),
    CONSTRAINT CK_GRAPH_COMPAT_STATUS CHECK (STATUS IN ('ACTIVE','MIGRATED','REVIEW_REQUIRED','READ_ONLY')),
    CONSTRAINT CK_GRAPH_COMPAT_TOPOLOGY CHECK (TOPOLOGY_STATUS IN ('KNOWN','REVIEW_REQUIRED','UNKNOWN')),
    CONSTRAINT CK_GRAPH_COMPAT_READONLY CHECK (READ_ONLY IN ('Y','N'))
);
CREATE INDEX IDX_GRAPH_JOIN_RUN ON GRAPH_JOIN_STATES(RUN_ID, STATUS, UPDATED_AT);
CREATE INDEX IDX_GRAPH_BRANCH_RUN ON GRAPH_RUN_BRANCHES(RUN_ID, STATUS, UPDATED_AT);
CREATE INDEX IDX_GRAPH_WAIT_EVENT ON GRAPH_WAIT_SUBSCRIPTIONS(STATUS, EVENT_TYPE, CORRELATION_KEY);
CREATE INDEX IDX_GRAPH_TRACE_RUN ON GRAPH_TRACES(RUN_ID, CREATED_AT);
CREATE INDEX IDX_GRAPH_MIGRATION_RUN ON GRAPH_RUN_MIGRATIONS(RUN_ID, CREATED_AT);
CREATE INDEX IDX_GRAPH_COMPAT_GRAPH ON GRAPH_COMPAT_BINDINGS(GRAPH_ID, STATUS, UPDATED_AT);
CREATE INDEX IDX_GRAPH_COMPAT_RUN ON GRAPH_COMPAT_BINDINGS(GRAPH_RUN_ID, STATUS);

PROMPT v4.2.0 Graph control objects ready.
