PROMPT v4.2.0 Graph trigger registration and delivery bindings

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE GRAPH_TRIGGERS (
        TRIGGER_ID VARCHAR2(128) NOT NULL,
        GRAPH_VERSION_ID VARCHAR2(128) NOT NULL,
        TRIGGER_KIND VARCHAR2(32) NOT NULL,
        CONFIG_JSON CLOB NOT NULL,
        STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL,
        ACTOR_ID VARCHAR2(256) NOT NULL,
        REASON VARCHAR2(2000) NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_GRAPH_TRIGGERS PRIMARY KEY (TRIGGER_ID),
        CONSTRAINT FK_GRAPH_TRIGGER_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID),
        CONSTRAINT CK_GRAPH_TRIGGER_KIND CHECK (TRIGGER_KIND IN (''MANUAL'',''API'',''SCHEDULE'',''DATABASE'',''EXTERNAL'',''INTERNAL'')),
        CONSTRAINT CK_GRAPH_TRIGGER_STATUS CHECK (STATUS IN (''ACTIVE'',''DISABLED''))
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRAPH_TRIGGER_VERSION
        ON GRAPH_TRIGGERS(GRAPH_VERSION_ID, STATUS, TRIGGER_KIND)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -1408) THEN
            RAISE;
        END IF;
END;
/

PROMPT v4.2.0 Graph trigger objects ready.
