PROMPT v4.2.1 Graph Engineering - persistent Node Executor registry

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE GRAPH_EXECUTOR_REGISTRY (
        EXECUTOR_ID VARCHAR(128) NOT NULL,
        EXECUTOR_NAME VARCHAR(128) NOT NULL,
        EXECUTOR_VERSION VARCHAR(64) NOT NULL,
        EXECUTOR_KIND VARCHAR(32) NOT NULL,
        NODE_TYPES_JSON CLOB NOT NULL,
        SIDE_EFFECT_CLASSES_JSON CLOB NOT NULL,
        MANIFEST_JSON CLOB NOT NULL,
        STATUS VARCHAR(32) DEFAULT ''ACTIVE'' NOT NULL,
        ACTOR_ID VARCHAR(256) NOT NULL,
        STATUS_REASON VARCHAR(2000),
        STATUS_CHANGED_BY VARCHAR(256),
        STATUS_CHANGED_AT TIMESTAMP,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_GRAPH_EXECUTOR_REG PRIMARY KEY (EXECUTOR_ID),
        CONSTRAINT UK_GRAPH_EXECUTOR_NAME UNIQUE (EXECUTOR_NAME, EXECUTOR_VERSION),
        CONSTRAINT CK_GRAPH_EXECUTOR_KIND CHECK (EXECUTOR_KIND IN (''CONTROL'',''WORKER'',''WAIT'')),
        CONSTRAINT CK_GRAPH_EXECUTOR_STATUS CHECK (STATUS IN (''ACTIVE'',''DISABLED'',''DEPRECATED''))
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE GRAPH_GOVERNANCE_EVENTS (
        EVENT_ID VARCHAR(128) NOT NULL,
        RUN_ID VARCHAR(128),
        ARTIFACT_ID VARCHAR(128),
        EVENT_TYPE VARCHAR(64) NOT NULL,
        ACTOR_ID VARCHAR(256) NOT NULL,
        REASON VARCHAR(2000) NOT NULL,
        DETAIL_JSON CLOB,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_GRAPH_GOV_EVENTS PRIMARY KEY (EVENT_ID)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRAPH_EXECUTOR_LOOKUP ON GRAPH_EXECUTOR_REGISTRY (EXECUTOR_NAME, EXECUTOR_VERSION, STATUS)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRAPH_GOV_EVENTS_RUN ON GRAPH_GOVERNANCE_EVENTS (RUN_ID, CREATED_AT)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRAPH_GOV_EVENTS_ARTIFACT ON GRAPH_GOVERNANCE_EVENTS (ARTIFACT_ID, CREATED_AT)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'GRAPH_EXECUTOR_REGISTRY' AND COLUMN_NAME = 'STATUS_REASON';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_EXECUTOR_REGISTRY ADD (STATUS_REASON VARCHAR(2000))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'GRAPH_EXECUTOR_REGISTRY' AND COLUMN_NAME = 'STATUS_CHANGED_BY';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_EXECUTOR_REGISTRY ADD (STATUS_CHANGED_BY VARCHAR(256))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'GRAPH_EXECUTOR_REGISTRY' AND COLUMN_NAME = 'STATUS_CHANGED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_EXECUTOR_REGISTRY ADD (STATUS_CHANGED_AT TIMESTAMP)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'GRAPH_INBOX' AND COLUMN_NAME = 'ATTEMPTS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_INBOX ADD (ATTEMPTS NUMBER(10,0) DEFAULT 0 NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'GRAPH_INBOX' AND COLUMN_NAME = 'AVAILABLE_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_INBOX ADD (AVAILABLE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'GRAPH_OUTBOX' AND COLUMN_NAME = 'MAX_ATTEMPTS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_OUTBOX ADD (MAX_ATTEMPTS NUMBER(10,0) DEFAULT 5 NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'GRAPH_ATTEMPTS' AND COLUMN_NAME = 'COMPLETION_DIGEST';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_ATTEMPTS ADD (COMPLETION_DIGEST VARCHAR(128))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'GRAPH_ATTEMPTS' AND COLUMN_NAME = 'EFFECT_IDEMPOTENCY_KEY';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE GRAPH_ATTEMPTS ADD (EFFECT_IDEMPOTENCY_KEY VARCHAR(256))'; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRAPH_INBOX_AVAILABLE ON GRAPH_INBOX (STATUS, AVAILABLE_AT, RECEIVED_AT)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

PROMPT v4.2.1 Graph Executor registry ready.
