-- v4.3.0 Human Principal, Agent Enrollment, governed Channel and Barrier core.
-- YashanDB 23.5.4 adapter.  The schema follows the Oracle-compatible
-- relational contract and keeps payloads in CLOB for portable canonical JSON.

CREATE TABLE CX_PRINCIPALS (
    PRINCIPAL_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_TYPE VARCHAR2(16) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, PERMISSION_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_PRINCIPAL_TYPE CHECK (PRINCIPAL_TYPE IN ('HUMAN','AGENT','SERVICE'))
);
CREATE INDEX IDX_CX_PRINCIPAL_TYPE ON CX_PRINCIPALS(PRINCIPAL_TYPE, STATUS);
CREATE TABLE CX_HUMAN_IDENTITIES (
    IDENTITY_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, IDENTITY_TYPE VARCHAR2(16) NOT NULL,
    PROVIDER VARCHAR2(256) DEFAULT 'LOCAL' NOT NULL, SUBJECT_KEY VARCHAR2(512) NOT NULL, USERNAME VARCHAR2(128), EMAIL VARCHAR2(320),
    PASSWORD_HASH CLOB, PASSWORD_VERSION VARCHAR2(32), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, LAST_LOGIN_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_IDENTITY_TYPE CHECK (IDENTITY_TYPE IN ('LOCAL','LDAP','OIDC')),
    CONSTRAINT UK_CX_IDENTITY_SUBJECT UNIQUE (IDENTITY_TYPE, PROVIDER, SUBJECT_KEY)
);
CREATE INDEX IDX_CX_IDENTITY_PRINCIPAL ON CX_HUMAN_IDENTITIES(PRINCIPAL_ID, STATUS);
CREATE UNIQUE INDEX IDX_CX_IDENTITY_USERNAME ON CX_HUMAN_IDENTITIES(LOWER(USERNAME));
CREATE TABLE CX_REGISTRATION_REQUESTS (
    REQUEST_ID VARCHAR2(128) PRIMARY KEY, USERNAME VARCHAR2(128) NOT NULL, EMAIL VARCHAR2(320), PASSWORD_HASH CLOB NOT NULL,
    AUTH_SOURCE VARCHAR2(16) DEFAULT 'LOCAL' NOT NULL, REGISTRATION_MODE VARCHAR2(32) DEFAULT 'APPROVAL' NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, DECISION_BY VARCHAR2(128), DECISION_REASON VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, DECIDED_AT TIMESTAMP
);
CREATE INDEX IDX_CX_REGISTRATION_STATUS ON CX_REGISTRATION_REQUESTS(STATUS, CREATED_AT);
CREATE TABLE CX_WEB_SESSIONS (
    SESSION_DIGEST VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, USER_ID VARCHAR2(128),
    AUTH_METHOD VARCHAR2(32) NOT NULL, MFA_LEVEL VARCHAR2(32) DEFAULT 'NONE' NOT NULL, NODE_ID VARCHAR2(128) NOT NULL,
    CLIENT_SUMMARY VARCHAR2(1000), PERMISSION_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL, CSRF_DIGEST VARCHAR2(128) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL, LAST_SEEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP,
    REVOKE_REASON VARCHAR2(1000), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_SESSION_PRINCIPAL ON CX_WEB_SESSIONS(PRINCIPAL_ID, REVOKED_AT, EXPIRES_AT);
CREATE TABLE CX_ROLE_TEMPLATES (
    ROLE_CODE VARCHAR2(64) PRIMARY KEY, DISPLAY_NAME VARCHAR2(256) NOT NULL, PERMISSIONS_JSON CLOB NOT NULL,
    DATA_SCOPES_JSON CLOB NOT NULL, VERSION NUMBER(19,0) DEFAULT 1 NOT NULL, MANAGED CHAR(1) DEFAULT 'Y' NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_USER_ROLES (
    USER_ROLE_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, ROLE_CODE VARCHAR2(64) NOT NULL,
    SOURCE VARCHAR2(32) DEFAULT 'DIRECT' NOT NULL, VALID_FROM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP,
    GRANTED_BY VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL
);
CREATE INDEX IDX_CX_USER_ROLES ON CX_USER_ROLES(PRINCIPAL_ID, STATUS, VALID_UNTIL);
CREATE TABLE CX_USER_PERMISSION_OVERRIDES (
    OVERRIDE_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, RESOURCE_ACTION VARCHAR2(256) NOT NULL,
    EFFECT VARCHAR2(16) NOT NULL, DATA_SCOPE VARCHAR2(32) DEFAULT 'NONE' NOT NULL, SECURITY_DOMAIN_ID VARCHAR2(128),
    VALID_UNTIL TIMESTAMP, REASON VARCHAR2(2000) NOT NULL, GRANTED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_OVERRIDE_EFFECT CHECK (EFFECT IN ('ALLOW','DENY'))
);
CREATE INDEX IDX_CX_PERMISSION_OVERRIDE ON CX_USER_PERMISSION_OVERRIDES(PRINCIPAL_ID, RESOURCE_ACTION, VALID_UNTIL);
CREATE TABLE CX_ORGANIZATIONS (
    ORGANIZATION_ID VARCHAR2(128) PRIMARY KEY, PARENT_ID VARCHAR2(128), ORGANIZATION_NAME VARCHAR2(256) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_ORGANIZATION_MEMBERS (
    MEMBERSHIP_ID VARCHAR2(128) PRIMARY KEY, ORGANIZATION_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    MEMBERSHIP_ROLE VARCHAR2(64) DEFAULT 'MEMBER' NOT NULL, MANAGER_PRINCIPAL_ID VARCHAR2(128), VALID_UNTIL TIMESTAMP, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT UK_CX_ORG_MEMBER UNIQUE (ORGANIZATION_ID, PRINCIPAL_ID)
);
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_ORGANIZATION_MEMBERS' AND COLUMN_NAME = 'MANAGER_PRINCIPAL_ID';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_ORGANIZATION_MEMBERS ADD (MANAGER_PRINCIPAL_ID VARCHAR2(128))';
    END IF;
END;
/
CREATE TABLE CX_RESPONSIBLE_GROUPS (
    GROUP_ID VARCHAR2(128) PRIMARY KEY, GROUP_NAME VARCHAR2(256) NOT NULL, SECURITY_DOMAIN_ID VARCHAR2(128),
    PARENT_GROUP_ID VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_RESPONSIBLE_GROUP_MEMBERS (
    GROUP_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL, MEMBER_ROLE VARCHAR2(64) DEFAULT 'MEMBER' NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CX_RESP_GROUP_MEMBER PRIMARY KEY (GROUP_ID, PRINCIPAL_ID)
);
CREATE TABLE CX_SECURITY_DOMAINS (
    SECURITY_DOMAIN_ID VARCHAR2(128) PRIMARY KEY, DOMAIN_NAME VARCHAR2(256) NOT NULL, CLASSIFICATION VARCHAR2(32) DEFAULT 'INTERNAL' NOT NULL,
    PURPOSE VARCHAR2(1000), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_DOMAIN_MEMBERS (
    MEMBERSHIP_ID VARCHAR2(128) PRIMARY KEY, SECURITY_DOMAIN_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    MEMBERSHIP_TIER VARCHAR2(32) DEFAULT 'MEMBER' NOT NULL, VALID_UNTIL TIMESTAMP, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT UK_CX_DOMAIN_MEMBER UNIQUE (SECURITY_DOMAIN_ID, PRINCIPAL_ID)
);
CREATE TABLE CX_ENROLLMENT_GRANTS (
    GRANT_ID VARCHAR2(128) PRIMARY KEY, SPONSOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, OWNER_PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    RESPONSIBLE_GROUP_ID VARCHAR2(128), SECURITY_DOMAIN_ID VARCHAR2(128), ENVIRONMENT VARCHAR2(64) NOT NULL, RUNTIME VARCHAR2(128) NOT NULL,
    AGENT_NAME VARCHAR2(256), NODE_CONSTRAINT VARCHAR2(256), PUBLIC_KEY_CONSTRAINT CLOB, RISK_TIER VARCHAR2(32) DEFAULT 'STANDARD' NOT NULL,
    QUOTA_KEY VARCHAR2(256), POLICY_SNAPSHOT CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL,
    MAX_USES NUMBER(10,0) DEFAULT 1 NOT NULL, USED_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_ENROLLMENT_TOKENS (
    TOKEN_ID VARCHAR2(128) PRIMARY KEY, GRANT_ID VARCHAR2(128) NOT NULL, TOKEN_DIGEST VARCHAR2(128) NOT NULL UNIQUE,
    PURPOSE VARCHAR2(32) DEFAULT 'AGENT_ENROLLMENT' NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL, CONSUMED_AT TIMESTAMP,
    CONSUMED_AGENT_ID VARCHAR2(128), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_ENROLLMENT_TOKEN_ACTIVE ON CX_ENROLLMENT_TOKENS(TOKEN_DIGEST, EXPIRES_AT, CONSUMED_AT);
CREATE TABLE CX_AGENT_RELATIONSHIPS (
    RELATIONSHIP_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    RELATIONSHIP_ROLE VARCHAR2(32) NOT NULL, RESPONSIBLE_GROUP_ID VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, ENDED_AT TIMESTAMP,
    CONSTRAINT CK_CX_AGENT_REL_ROLE CHECK (RELATIONSHIP_ROLE IN ('SPONSOR','PRIMARY_OWNER','OPERATOR','VIEWER'))
);
CREATE UNIQUE INDEX IDX_CX_AGENT_PRIMARY_OWNER ON CX_AGENT_RELATIONSHIPS(AGENT_ID, RELATIONSHIP_ROLE, STATUS);
CREATE TABLE CX_AGENT_CREDENTIALS (
    CREDENTIAL_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, CREDENTIAL_TYPE VARCHAR2(32) NOT NULL,
    PUBLIC_KEY CLOB, SECRET_DIGEST VARCHAR2(128), KEY_VERSION NUMBER(10,0) DEFAULT 1 NOT NULL, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    EXPIRES_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP,
    CONSTRAINT CK_CX_AGENT_CRED_TYPE CHECK (CREDENTIAL_TYPE IN ('ED25519','CLIENT_SECRET','MTLS'))
);
CREATE TABLE CX_AGENT_ACCESS_TOKENS (
    TOKEN_DIGEST VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, INSTANCE_ID VARCHAR2(128) NOT NULL,
    SCOPE_JSON CLOB NOT NULL, LEASE_DIGEST VARCHAR2(128), FENCING_TOKEN NUMBER(19,0), EXPIRES_AT TIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_AGENT_ACCESS_TOKEN ON CX_AGENT_ACCESS_TOKENS(AGENT_ID, INSTANCE_ID, EXPIRES_AT, REVOKED_AT);
CREATE TABLE CX_CHANNELS (
    CHANNEL_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_NAME VARCHAR2(256) NOT NULL, SECURITY_DOMAIN_ID VARCHAR2(128) NOT NULL,
    CLASSIFICATION VARCHAR2(32) DEFAULT 'INTERNAL' NOT NULL, CHANNEL_TYPE VARCHAR2(32) DEFAULT 'TEAM' NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, RETENTION_UNTIL TIMESTAMP, LEGAL_HOLD CHAR(1) DEFAULT 'N' NOT NULL,
    METADATA_JSON CLOB, CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_CHANNEL_DOMAIN ON CX_CHANNELS(SECURITY_DOMAIN_ID, STATUS, UPDATED_AT);
CREATE TABLE CX_CHANNEL_MEMBERS (
    MEMBER_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    MEMBER_ROLE VARCHAR2(32) DEFAULT 'MEMBER' NOT NULL, JOINED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    VALID_UNTIL TIMESTAMP, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, CONSTRAINT UK_CX_CHANNEL_MEMBER UNIQUE(CHANNEL_ID, PRINCIPAL_ID)
);
CREATE TABLE CX_CHANNEL_MESSAGES (
    MESSAGE_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128) NOT NULL, THREAD_TYPE VARCHAR2(32) DEFAULT 'CHANNEL' NOT NULL,
    THREAD_ID VARCHAR2(128), PRINCIPAL_ID VARCHAR2(128) NOT NULL, BODY_TEXT CLOB NOT NULL, BODY_CLASSIFICATION VARCHAR2(32) DEFAULT 'INTERNAL' NOT NULL,
    MESSAGE_TYPE VARCHAR2(32) DEFAULT 'TEXT' NOT NULL, REFERENCE_JSON CLOB, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REDACTED_AT TIMESTAMP
);
CREATE INDEX IDX_CX_CHANNEL_MESSAGE_CURSOR ON CX_CHANNEL_MESSAGES(CHANNEL_ID, CREATED_AT, MESSAGE_ID);
CREATE TABLE CX_BARRIERS (
    BARRIER_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128), RUN_ID VARCHAR2(128), NODE_KEY VARCHAR2(128) NOT NULL,
    POLICY_JSON CLOB NOT NULL, PARTICIPANT_SNAPSHOT CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'WAITING' NOT NULL,
    POLICY_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL, CHECKPOINT_ID VARCHAR2(128), RELEASED_BY VARCHAR2(128), RELEASED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(128), TIMEOUT_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_BARRIER_STATUS ON CX_BARRIERS(STATUS, TIMEOUT_AT, UPDATED_AT);
CREATE TABLE CX_BARRIER_ARRIVALS (
    ARRIVAL_ID VARCHAR2(128) PRIMARY KEY, BARRIER_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
    PARTICIPANT_ROLE VARCHAR2(64) NOT NULL, REPORT_DIGEST VARCHAR2(128) NOT NULL, REPORT_JSON CLOB NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(256),
    STATUS VARCHAR2(32) DEFAULT 'ACCEPTED' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_CX_BARRIER_ARRIVAL UNIQUE(BARRIER_ID, PRINCIPAL_ID)
);
CREATE UNIQUE INDEX IDX_CX_BARRIER_ARRIVAL_IDEMP ON CX_BARRIER_ARRIVALS(BARRIER_ID, PRINCIPAL_ID, IDEMPOTENCY_KEY);
CREATE TABLE CX_ACTION_CARDS (
    ACTION_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128) NOT NULL, PROPOSED_BY VARCHAR2(128) NOT NULL,
    ACTION_TYPE VARCHAR2(64) NOT NULL, VERSION NUMBER(10,0) DEFAULT 1 NOT NULL, PAYLOAD_JSON CLOB NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'PROPOSED' NOT NULL, REASON VARCHAR2(2000) NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256) NOT NULL UNIQUE,
    DECIDED_BY VARCHAR2(128), DECIDED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE CX_NOTIFICATIONS (
    NOTIFICATION_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, NOTIFICATION_TYPE VARCHAR2(64) NOT NULL,
    DEDUPE_KEY VARCHAR2(256) NOT NULL, PAYLOAD_JSON CLOB NOT NULL, ACKNOWLEDGED_AT TIMESTAMP, DEADLINE_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT UK_CX_NOTIFICATION_DEDUPE UNIQUE(PRINCIPAL_ID, DEDUPE_KEY)
);
CREATE TABLE CX_SECURITY_EVENTS (
    EVENT_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128), ACTOR_TYPE VARCHAR2(16) NOT NULL,
    ACTION_NAME VARCHAR2(128) NOT NULL, RESOURCE_TYPE VARCHAR2(64), RESOURCE_ID VARCHAR2(128), OUTCOME VARCHAR2(32) NOT NULL,
    REASON VARCHAR2(2000), DETAIL_JSON CLOB, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_SECURITY_EVENT_TIME ON CX_SECURITY_EVENTS(CREATED_AT, ACTION_NAME, OUTCOME);
CREATE TABLE CX_BRIDGES (
    BRIDGE_ID VARCHAR2(128) PRIMARY KEY, SOURCE_DOMAIN_ID VARCHAR2(128) NOT NULL, TARGET_DOMAIN_ID VARCHAR2(128) NOT NULL,
    CHANNEL_ID VARCHAR2(128), TRANSFER_MODE VARCHAR2(32) NOT NULL, PURPOSE VARCHAR2(2000) NOT NULL, CLASSIFICATION VARCHAR2(32) NOT NULL,
    RECIPIENT_SNAPSHOT CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL,
    APPROVED_BY VARCHAR2(128), CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_BRIDGE_MODE CHECK (TRANSFER_MODE IN ('REFERENCE','REDACTED_COPY','SUMMARY','ARTIFACT','FULL_COPY'))
);

CREATE TABLE CX_AGENT_INSTANCES (
    INSTANCE_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL,
    CHANNEL_ID VARCHAR2(128), SECURITY_DOMAIN_ID VARCHAR2(128), RUN_ID VARCHAR2(128),
    CLASSIFICATION VARCHAR2(32) DEFAULT 'INTERNAL' NOT NULL, NODE_ID VARCHAR2(128),
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL, FENCING_TOKEN NUMBER(19,0) DEFAULT 1 NOT NULL,
    LAST_SEEN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LEASE_EXPIRES_AT TIMESTAMP DEFAULT (SYSTIMESTAMP + INTERVAL '5' MINUTE) NOT NULL,
    REVOKED_AT TIMESTAMP,
    REVOKE_REASON VARCHAR2(1000), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_CX_AGENT_INSTANCE_SCOPE ON CX_AGENT_INSTANCES(AGENT_ID, CHANNEL_ID, SECURITY_DOMAIN_ID, STATUS);
CREATE TABLE CX_AGENT_DELIVERIES (
    DELIVERY_ID VARCHAR2(128) PRIMARY KEY, EVENT_TYPE VARCHAR2(64) NOT NULL,
    CHANNEL_ID VARCHAR2(128), MESSAGE_ID VARCHAR2(128), AGENT_ID VARCHAR2(128) NOT NULL,
    INSTANCE_ID VARCHAR2(128) NOT NULL, PAYLOAD_JSON CLOB NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL, VISIBILITY_UNTIL TIMESTAMP,
    ATTEMPT_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL, MAX_ATTEMPTS NUMBER(10,0) DEFAULT 5 NOT NULL,
    CLAIMED_BY VARCHAR2(128), CLAIM_TOKEN_DIGEST VARCHAR2(128), CLAIMED_AT TIMESTAMP,
    FENCING_TOKEN NUMBER(19,0), ACKED_AT TIMESTAMP, FAILURE_REASON VARCHAR2(2000), DEAD_LETTER_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_CX_DELIVERY_IDEMP UNIQUE(AGENT_ID, IDEMPOTENCY_KEY)
);
CREATE INDEX IDX_CX_DELIVERY_CLAIM ON CX_AGENT_DELIVERIES(INSTANCE_ID, STATUS, VISIBILITY_UNTIL, CREATED_AT);

-- Additive compatibility for databases that applied an early v4.3.0 draft.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_AGENT_INSTANCES' AND COLUMN_NAME = 'LEASE_EXPIRES_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_AGENT_INSTANCES ADD (LEASE_EXPIRES_AT TIMESTAMP)';
    END IF;
END;
/
UPDATE CX_AGENT_INSTANCES
   SET LEASE_EXPIRES_AT = NVL(LEASE_EXPIRES_AT, LAST_SEEN_AT + INTERVAL '5' MINUTE)
 WHERE LEASE_EXPIRES_AT IS NULL;
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_AGENT_DELIVERIES' AND COLUMN_NAME = 'CLAIM_TOKEN_DIGEST';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_AGENT_DELIVERIES ADD (CLAIM_TOKEN_DIGEST VARCHAR2(128))';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_AGENT_DELIVERIES' AND COLUMN_NAME = 'CLAIMED_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_AGENT_DELIVERIES ADD (CLAIMED_AT TIMESTAMP)';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_AGENT_DELIVERIES' AND COLUMN_NAME = 'FENCING_TOKEN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_AGENT_DELIVERIES ADD (FENCING_TOKEN NUMBER(19,0))';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_AGENT_ACCESS_TOKENS' AND COLUMN_NAME = 'FENCING_TOKEN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_AGENT_ACCESS_TOKENS ADD (FENCING_TOKEN NUMBER(19,0))';
    END IF;
END;
/
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_BARRIERS' AND COLUMN_NAME = 'CREATED_BY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_BARRIERS ADD (CREATED_BY VARCHAR2(128))';
    END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_DELIVERY_CLAIM_TOKEN ON CX_AGENT_DELIVERIES(CLAIM_TOKEN_DIGEST)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
CREATE TABLE CX_CHANNEL_MEMORY_CANDIDATES (
    CANDIDATE_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128) NOT NULL,
    SECURITY_DOMAIN_ID VARCHAR2(128) NOT NULL, PROPOSED_BY VARCHAR2(128) NOT NULL,
    CONTENT_JSON CLOB NOT NULL, CLASSIFICATION VARCHAR2(32) NOT NULL, DESTINATION_SCOPE VARCHAR2(32) NOT NULL,
    PROVENANCE_JSON CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT 'PROPOSED' NOT NULL,
    REVIEWED_BY VARCHAR2(128), REVIEW_REASON VARCHAR2(2000), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REVIEWED_AT TIMESTAMP
);
CREATE TABLE CX_BRIDGE_TRANSFERS (
    TRANSFER_ID VARCHAR2(128) PRIMARY KEY, BRIDGE_ID VARCHAR2(128) NOT NULL,
    SOURCE_OBJECT_TYPE VARCHAR2(64) NOT NULL, SOURCE_OBJECT_ID VARCHAR2(128) NOT NULL,
    TARGET_OBJECT_ID VARCHAR2(128), PAYLOAD_DIGEST VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
    CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DELIVERED_AT TIMESTAMP, QUARANTINED_AT TIMESTAMP, REASON VARCHAR2(2000)
);
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'END_USER' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('END_USER','End User','["profile.read","profile.update","agents.enroll","agents.read","channels.read","channels.write","tasks.read","workspaces.read","knowledge.read","memory.read","skills.read","specs.read","branches.read","collab.read","loops.read","graphs.read","notifications.read"]','["OWNED","ASSIGNED"]');
UPDATE CX_ROLE_TEMPLATES
   SET DISPLAY_NAME = 'End User',
       PERMISSIONS_JSON = '["profile.read","profile.update","agents.enroll","agents.read","channels.read","channels.write","tasks.read","workspaces.read","knowledge.read","memory.read","skills.read","specs.read","branches.read","collab.read","loops.read","graphs.read","notifications.read"]',
       DATA_SCOPES_JSON = '["OWNED","ASSIGNED"]',
       VERSION = VERSION + 1,
       UPDATED_AT = SYSTIMESTAMP
 WHERE ROLE_CODE = 'END_USER'
   AND (INSTR(PERMISSIONS_JSON, '"agents.enroll"') = 0
        OR INSTR(PERMISSIONS_JSON, '"channels.read"') = 0
        OR INSTR(DATA_SCOPES_JSON, '"ASSIGNED"') = 0);
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'SYSTEM_ADMIN' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('SYSTEM_ADMIN','System Administrator','["*"]','["ALL"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'SECURITY_ADMIN' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('SECURITY_ADMIN','Security Administrator','["security.*","sessions.revoke","domains.manage","channels.bridge"]','["SECURITY_DOMAIN"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'AGENT_MANAGER' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('AGENT_MANAGER','Agent Manager','["agents.read","agents.enroll","agents.manage","agents.operate","channels.read","channels.manage_members","users.read"]','["ORG_SUBTREE"]');
UPDATE CX_ROLE_TEMPLATES
   SET PERMISSIONS_JSON = '["agents.read","agents.enroll","agents.manage","agents.operate","channels.read","channels.manage_members","users.read"]',
       VERSION = VERSION + 1, UPDATED_AT = SYSTIMESTAMP
 WHERE ROLE_CODE = 'AGENT_MANAGER' AND INSTR(PERMISSIONS_JSON, '"agents.*"') > 0;
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'AUDITOR' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('AUDITOR','Auditor','["audit.read","audit.export","users.read"]','["SECURITY_DOMAIN"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'APPROVER' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('APPROVER','Approver','["approvals.read","approvals.decide","channels.actions.decide","barriers.release","users.read"]','["ASSIGNED"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'OPERATOR' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('OPERATOR','Operator','["agents.read","agents.operate","channels.write","barriers.arrive"]','["ASSIGNED"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'DEVELOPER' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('DEVELOPER','Developer','["skills.read","tools.read","graphs.read","barriers.create"]','["OWNED"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'USER_ADMIN' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('USER_ADMIN','User Administrator','["users.read","users.approve","users.roles.manage","users.permissions.manage"]','["ORG_SUBTREE"]');
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'ROLE_ADMIN' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON) VALUES ('ROLE_ADMIN','Role Administrator','["users.read","users.roles.manage","users.permissions.manage"]','["ORG_SUBTREE"]');
MERGE INTO CX_SECURITY_DOMAINS dst USING (SELECT 'DEFAULT' SECURITY_DOMAIN_ID FROM DUAL) src ON (dst.SECURITY_DOMAIN_ID = src.SECURITY_DOMAIN_ID)
WHEN NOT MATCHED THEN INSERT (SECURITY_DOMAIN_ID, DOMAIN_NAME, CLASSIFICATION, PURPOSE, STATUS)
VALUES ('DEFAULT','Default Security Domain','INTERNAL','Bootstrap domain; replace with an organization-specific domain before production','ACTIVE');
