-- v4.3.0 security lifecycle for YashanDB 23.5.4.
-- YashanDB uses the same portable relational boundary as Oracle.  Every
-- guarded block absorbs only the known duplicate object/column conditions.

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_PRINCIPALS ADD (MFA_REQUIRED CHAR(1) DEFAULT ''N'' NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (1430, 2013, 2176) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_HUMAN_IDENTITIES ADD (FAILED_LOGIN_COUNT NUMBER(10,0) DEFAULT 0 NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (1430, 2013, 2176) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_HUMAN_IDENTITIES ADD (LOCKED_UNTIL TIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (1430, 2013, 2176) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_HUMAN_IDENTITIES ADD (USER_ID VARCHAR2(128))';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (1430, 2013, 2176) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_ENROLLMENT_GRANTS ADD (AGENT_ID VARCHAR2(128))';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (1430, 2013, 2176) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MFA_FACTORS (FACTOR_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, FACTOR_TYPE VARCHAR2(32) NOT NULL, SECRET_CIPHERTEXT CLOB, CREDENTIAL_REF VARCHAR2(512), STATUS VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL, VERIFIED_AT TIMESTAMP, LAST_USED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MFA_RECOVERY_CODES (CODE_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, CODE_DIGEST VARCHAR2(128) NOT NULL UNIQUE, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, USED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_PASSWORD_RESET_TOKENS (TOKEN_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL, TOKEN_DIGEST VARCHAR2(128) NOT NULL UNIQUE, PURPOSE VARCHAR2(32) NOT NULL, EXPIRES_AT TIMESTAMP NOT NULL, CONSUMED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_IDENTITY_LINK_AUDIT (LINK_EVENT_ID VARCHAR2(128) PRIMARY KEY, IDENTITY_ID VARCHAR2(128), PRINCIPAL_ID VARCHAR2(128) NOT NULL, ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, PROVIDER VARCHAR2(256) NOT NULL, SUBJECT_DIGEST VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL, OUTCOME VARCHAR2(32) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_DELEGATIONS (DELEGATION_ID VARCHAR2(128) PRIMARY KEY, GRANTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, GRANTEE_PRINCIPAL_ID VARCHAR2(128) NOT NULL, PERMISSIONS_JSON CLOB NOT NULL, DATA_SCOPE VARCHAR2(32) NOT NULL, VALID_UNTIL TIMESTAMP, REASON VARCHAR2(2000) NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, VERSION NUMBER(19,0) DEFAULT 1 NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_QUOTAS (QUOTA_ID VARCHAR2(128) PRIMARY KEY, SCOPE_TYPE VARCHAR2(32) NOT NULL, SCOPE_ID VARCHAR2(128) NOT NULL, ENVIRONMENT VARCHAR2(64) NOT NULL, MAX_AGENTS NUMBER(19,0) DEFAULT 0 NOT NULL, USED_AGENTS NUMBER(19,0) DEFAULT 0 NOT NULL, MAX_ACTIVE_INSTANCES NUMBER(19,0) DEFAULT 0 NOT NULL, USED_ACTIVE_INSTANCES NUMBER(19,0) DEFAULT 0 NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT UK_CX_AGENT_QUOTA UNIQUE(SCOPE_TYPE, SCOPE_ID, ENVIRONMENT))';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_OWNERSHIP_HISTORY (HISTORY_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, OLD_OWNER_PRINCIPAL_ID VARCHAR2(128), NEW_OWNER_PRINCIPAL_ID VARCHAR2(128), ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, POLICY_VERSION NUMBER(19,0), CREDENTIAL_ROTATED CHAR(1) DEFAULT ''N'' NOT NULL, GRANTS_REEVALUATED CHAR(1) DEFAULT ''N'' NOT NULL, REASON VARCHAR2(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_LEGACY_REVIEWS (REVIEW_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, CLASSIFICATION VARCHAR2(32) NOT NULL, EVIDENCE_JSON CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT ''OPEN'' NOT NULL, CLAIMED_BY VARCHAR2(128), CLAIM_REASON VARCHAR2(2000), DECIDED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_DERIVED_OBJECTS (DERIVED_OBJECT_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL, INSTANCE_ID VARCHAR2(128), OBJECT_TYPE VARCHAR2(64) NOT NULL, OBJECT_ID VARCHAR2(128) NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REVOKED_AT TIMESTAMP, REVOKE_REASON VARCHAR2(2000))';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_CHANNEL_DELETION_EVIDENCE (EVIDENCE_ID VARCHAR2(128) PRIMARY KEY, CHANNEL_ID VARCHAR2(128) NOT NULL, ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, FROM_STATUS VARCHAR2(32) NOT NULL, TO_STATUS VARCHAR2(32) NOT NULL, REFERENCE_COUNT NUMBER(19,0) DEFAULT 0 NOT NULL, REASON VARCHAR2(2000) NOT NULL, DETAIL_JSON CLOB NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MEMORY_ARTIFACT_LINKS (LINK_ID VARCHAR2(128) PRIMARY KEY, CANDIDATE_ID VARCHAR2(128) NOT NULL, ARTIFACT_ID VARCHAR2(128) NOT NULL, DESTINATION_SCOPE VARCHAR2(32) NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_BRIDGE_CONNECTORS (CONNECTOR_ID VARCHAR2(128) PRIMARY KEY, BRIDGE_ID VARCHAR2(128) NOT NULL, CONNECTOR_MODE VARCHAR2(32) NOT NULL, ENDPOINT_REF VARCHAR2(512) NOT NULL, METADATA_ONLY CHAR(1) DEFAULT ''Y'' NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, REASON VARCHAR2(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207, 2043) THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_MFA_PRINCIPAL ON CX_MFA_FACTORS(PRINCIPAL_ID, STATUS)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_RESET_ACTIVE ON CX_PASSWORD_RESET_TOKENS(TOKEN_DIGEST, EXPIRES_AT, CONSUMED_AT)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_AGENT_REVIEW_STATUS ON CX_AGENT_LEGACY_REVIEWS(STATUS, CLASSIFICATION, CREATED_AT)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_DERIVED_AGENT ON CX_AGENT_DERIVED_OBJECTS(AGENT_ID, INSTANCE_ID, STATUS)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_ENROLLMENT_AGENT ON CX_ENROLLMENT_GRANTS(AGENT_ID, STATUS)';
EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955, 4207) THEN RAISE; END IF; END;
