-- v4.3.1 authoritative organization governance schema.
-- YashanDB 23.5.4 adapter. Native Property Graph remains a replaceable
-- projection; relational facts remain authoritative for authorization.

DECLARE
    PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
        l_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = UPPER(p_table) AND COLUMN_NAME = UPPER(p_column);
        IF l_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
        END IF;
    END;
    PROCEDURE add_constraint(p_name VARCHAR2, p_ddl VARCHAR2) IS
        l_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_name);
        IF l_count = 0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
    END;
BEGIN
    add_column('CX_ORGANIZATIONS','ORGANIZATION_CODE','VARCHAR2(128)');
    add_column('CX_ORGANIZATIONS','ORGANIZATION_TYPE','VARCHAR2(64) DEFAULT ''DEPARTMENT'' NOT NULL');
    add_column('CX_ORGANIZATIONS','IS_LEGAL_ENTITY','CHAR(1) DEFAULT ''N'' NOT NULL');
    add_column('CX_ORGANIZATIONS','SORT_ORDER','NUMBER(19,0) DEFAULT 0 NOT NULL');
    add_column('CX_ORGANIZATIONS','RESPONSIBLE_PRINCIPAL_ID','VARCHAR2(128)');
    add_column('CX_ORGANIZATIONS','SECURITY_DOMAIN_ID','VARCHAR2(128)');
    add_column('CX_ORGANIZATIONS','VALID_FROM','TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    add_column('CX_ORGANIZATIONS','VALID_UNTIL','TIMESTAMP');
    add_column('CX_ORGANIZATIONS','SOURCE_TYPE','VARCHAR2(32) DEFAULT ''MANUAL'' NOT NULL');
    add_column('CX_ORGANIZATIONS','SOURCE_CONNECTOR_ID','VARCHAR2(128)');
    add_column('CX_ORGANIZATIONS','EXTERNAL_OBJECT_ID','VARCHAR2(512)');
    add_column('CX_ORGANIZATIONS','ROW_VERSION','NUMBER(19,0) DEFAULT 1 NOT NULL');
    add_column('CX_ORGANIZATIONS','UPDATED_AT','TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    add_column('CX_ORGANIZATIONS','UPDATED_BY','VARCHAR2(128)');
    add_column('CX_ORGANIZATION_MEMBERS','MEMBERSHIP_KIND','VARCHAR2(16) DEFAULT ''PRIMARY'' NOT NULL');
    add_column('CX_ORGANIZATION_MEMBERS','VALID_FROM','TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    add_column('CX_ORGANIZATION_MEMBERS','SOURCE_TYPE','VARCHAR2(32) DEFAULT ''MANUAL'' NOT NULL');
    add_column('CX_ORGANIZATION_MEMBERS','SOURCE_CONNECTOR_ID','VARCHAR2(128)');
    add_column('CX_ORGANIZATION_MEMBERS','EXTERNAL_OBJECT_ID','VARCHAR2(512)');
    add_column('CX_ORGANIZATION_MEMBERS','ROW_VERSION','NUMBER(19,0) DEFAULT 1 NOT NULL');
    add_column('CX_ORGANIZATION_MEMBERS','UPDATED_AT','TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    add_column('CX_ORGANIZATION_MEMBERS','UPDATED_BY','VARCHAR2(128)');
    add_column('CX_AGENT_RELATIONSHIPS','RESPONSIBLE_ORGANIZATION_ID','VARCHAR2(128)');
    add_constraint('CK_CX_ORG_LEGAL', 'ALTER TABLE CX_ORGANIZATIONS ADD CONSTRAINT CK_CX_ORG_LEGAL CHECK (IS_LEGAL_ENTITY IN (''Y'',''N''))');
    add_constraint('CK_CX_ORG_VALIDITY', 'ALTER TABLE CX_ORGANIZATIONS ADD CONSTRAINT CK_CX_ORG_VALIDITY CHECK (VALID_UNTIL IS NULL OR VALID_UNTIL > VALID_FROM)');
    add_constraint('CK_CX_ORG_SOURCE', 'ALTER TABLE CX_ORGANIZATIONS ADD CONSTRAINT CK_CX_ORG_SOURCE CHECK (SOURCE_TYPE IN (''MANUAL'',''CSV'',''JSON'',''LDAP'',''OIDC'',''SCIM'',''SYSTEM''))');
    add_constraint('CK_CX_ORG_MEMBER_KIND', 'ALTER TABLE CX_ORGANIZATION_MEMBERS ADD CONSTRAINT CK_CX_ORG_MEMBER_KIND CHECK (MEMBERSHIP_KIND IN (''PRIMARY'',''SECONDARY''))');
    add_constraint('CK_CX_ORG_MEMBER_VALID', 'ALTER TABLE CX_ORGANIZATION_MEMBERS ADD CONSTRAINT CK_CX_ORG_MEMBER_VALID CHECK (VALID_UNTIL IS NULL OR VALID_UNTIL > VALID_FROM)');
END;
/

DECLARE
    PROCEDURE create_table(p_name VARCHAR2, p_ddl VARCHAR2) IS l_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_name);
        IF l_count = 0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
    END;
BEGIN
    create_table('CX_REPORTING_RELATIONSHIPS', 'CREATE TABLE CX_REPORTING_RELATIONSHIPS (
        RELATIONSHIP_ID VARCHAR2(128) PRIMARY KEY, PRINCIPAL_ID VARCHAR2(128) NOT NULL,
        MANAGER_PRINCIPAL_ID VARCHAR2(128) NOT NULL, RELATIONSHIP_TYPE VARCHAR2(32) NOT NULL,
        VALID_FROM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP,
        SOURCE_TYPE VARCHAR2(32) DEFAULT ''MANUAL'' NOT NULL, SOURCE_CONNECTOR_ID VARCHAR2(128), EXTERNAL_OBJECT_ID VARCHAR2(512),
        STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, ROW_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(128),
        CONSTRAINT CK_CX_REPORT_TYPE CHECK (RELATIONSHIP_TYPE IN (''DIRECT'',''DOTTED'',''PROJECT_LEAD'')),
        CONSTRAINT CK_CX_REPORT_SELF CHECK (PRINCIPAL_ID <> MANAGER_PRINCIPAL_ID),
        CONSTRAINT CK_CX_REPORT_VALID CHECK (VALID_UNTIL IS NULL OR VALID_UNTIL > VALID_FROM))');
    create_table('CX_ORGANIZATION_CLOSURE', 'CREATE TABLE CX_ORGANIZATION_CLOSURE (
        ANCESTOR_ID VARCHAR2(128) NOT NULL, DESCENDANT_ID VARCHAR2(128) NOT NULL, DEPTH NUMBER(10,0) NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_CX_ORG_CLOSURE PRIMARY KEY (ANCESTOR_ID, DESCENDANT_ID),
        CONSTRAINT CK_CX_ORG_CLOSURE_DEPTH CHECK (DEPTH >= 0),
        CONSTRAINT CK_CX_ORG_CLOSURE_SELF CHECK ((DEPTH = 0 AND ANCESTOR_ID = DESCENDANT_ID) OR (DEPTH > 0 AND ANCESTOR_ID <> DESCENDANT_ID)))');
    create_table('CX_ORGANIZATION_VERSIONS', 'CREATE TABLE CX_ORGANIZATION_VERSIONS (
        VERSION_ID VARCHAR2(128) PRIMARY KEY, VERSION_NUMBER NUMBER(19,0) NOT NULL UNIQUE,
        PARENT_VERSION_ID VARCHAR2(128), CHANGE_SET_ID VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT ''CURRENT'' NOT NULL,
        EFFECTIVE_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONTENT_DIGEST VARCHAR2(128), REASON VARCHAR2(2000) NOT NULL,
        CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
    create_table('CX_ORGANIZATION_UNIT_HISTORY', 'CREATE TABLE CX_ORGANIZATION_UNIT_HISTORY (
        HISTORY_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL, ORGANIZATION_ID VARCHAR2(128) NOT NULL,
        OPERATION VARCHAR2(16) NOT NULL, VALID_FROM TIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP, FACT_JSON CLOB NOT NULL,
        FACT_DIGEST VARCHAR2(128) NOT NULL, ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL,
        RECORDED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_CX_ORG_HIST_OP CHECK (OPERATION IN (''INSERT'',''UPDATE'',''RETIRE'')))');
    create_table('CX_ORGANIZATION_MEMBER_HISTORY', 'CREATE TABLE CX_ORGANIZATION_MEMBER_HISTORY (
        HISTORY_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL, MEMBERSHIP_ID VARCHAR2(128) NOT NULL,
        PRINCIPAL_ID VARCHAR2(128) NOT NULL, ORGANIZATION_ID VARCHAR2(128) NOT NULL, OPERATION VARCHAR2(16) NOT NULL,
        VALID_FROM TIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP, FACT_JSON CLOB NOT NULL, FACT_DIGEST VARCHAR2(128) NOT NULL,
        ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL, RECORDED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_CX_MEM_HIST_OP CHECK (OPERATION IN (''INSERT'',''UPDATE'',''END'')))');
    create_table('CX_REPORTING_HISTORY', 'CREATE TABLE CX_REPORTING_HISTORY (
        HISTORY_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL, RELATIONSHIP_ID VARCHAR2(128) NOT NULL,
        PRINCIPAL_ID VARCHAR2(128) NOT NULL, MANAGER_PRINCIPAL_ID VARCHAR2(128) NOT NULL, OPERATION VARCHAR2(16) NOT NULL,
        VALID_FROM TIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP, FACT_JSON CLOB NOT NULL, FACT_DIGEST VARCHAR2(128) NOT NULL,
        ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL, RECORDED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_CX_RPT_HIST_OP CHECK (OPERATION IN (''INSERT'',''UPDATE'',''END'')))');
    create_table('CX_ORG_CHANGESETS', 'CREATE TABLE CX_ORG_CHANGESETS (
        CHANGE_SET_ID VARCHAR2(128) PRIMARY KEY, BASE_VERSION_ID VARCHAR2(128) NOT NULL, AUTHOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL,
        STATUS VARCHAR2(32) DEFAULT ''DRAFT'' NOT NULL, REASON VARCHAR2(2000) NOT NULL, RISK_LEVEL VARCHAR2(16) DEFAULT ''LOW'' NOT NULL,
        POLICY_SNAPSHOT CLOB, VALIDATION_JSON CLOB, IMPACT_JSON CLOB, ACTION_CARD_ID VARCHAR2(128), SCHEDULED_FOR TIMESTAMP,
        SUBMITTED_AT TIMESTAMP, PUBLISHED_AT TIMESTAMP, OUTCOME_JSON CLOB, IDEMPOTENCY_KEY VARCHAR2(256) NOT NULL UNIQUE,
        ROW_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_CX_ORG_CHANGE_RISK CHECK (RISK_LEVEL IN (''LOW'',''MEDIUM'',''HIGH'',''CRITICAL'')))');
    create_table('CX_ORG_CHANGE_OPERATIONS', 'CREATE TABLE CX_ORG_CHANGE_OPERATIONS (
        OPERATION_ID VARCHAR2(128) PRIMARY KEY, CHANGE_SET_ID VARCHAR2(128) NOT NULL, SEQUENCE_NUMBER NUMBER(10,0) NOT NULL,
        OPERATION_TYPE VARCHAR2(64) NOT NULL, TARGET_TYPE VARCHAR2(32) NOT NULL, TARGET_ID VARCHAR2(128),
        EXPECTED_ROW_VERSION NUMBER(19,0), COMMAND_JSON CLOB NOT NULL, BEFORE_DIGEST VARCHAR2(128), AFTER_DIGEST VARCHAR2(128) NOT NULL,
        STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT UK_CX_ORG_CHANGE_SEQ UNIQUE (CHANGE_SET_ID, SEQUENCE_NUMBER),
        CONSTRAINT CK_CX_ORG_CHANGE_SEQ CHECK (SEQUENCE_NUMBER > 0))');
    create_table('CX_DIRECTORY_SYNC_BATCHES', 'CREATE TABLE CX_DIRECTORY_SYNC_BATCHES (
        SYNC_BATCH_ID VARCHAR2(128) PRIMARY KEY, CONNECTOR_ID VARCHAR2(128) NOT NULL, CONNECTOR_TYPE VARCHAR2(16) NOT NULL,
        SOURCE_DIGEST VARCHAR2(128) NOT NULL, STATUS VARCHAR2(32) DEFAULT ''STAGING'' NOT NULL, REQUESTED_BY VARCHAR2(128) NOT NULL,
        CHANGE_SET_ID VARCHAR2(128), TOTAL_RECORDS NUMBER(19,0) DEFAULT 0 NOT NULL, ACCEPTED_RECORDS NUMBER(19,0) DEFAULT 0 NOT NULL,
        CONFLICT_RECORDS NUMBER(19,0) DEFAULT 0 NOT NULL, ERROR_RECORDS NUMBER(19,0) DEFAULT 0 NOT NULL,
        STARTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, SUMMARY_JSON CLOB,
        CONSTRAINT CK_CX_DIR_CONNECTOR CHECK (CONNECTOR_TYPE IN (''CSV'',''JSON'',''LDAP'',''OIDC'',''SCIM'')))');
    create_table('CX_DIRECTORY_SOURCE_RECORDS', 'CREATE TABLE CX_DIRECTORY_SOURCE_RECORDS (
        SOURCE_RECORD_ID VARCHAR2(128) PRIMARY KEY, SYNC_BATCH_ID VARCHAR2(128) NOT NULL, CONNECTOR_ID VARCHAR2(128) NOT NULL,
        EXTERNAL_OBJECT_ID VARCHAR2(512) NOT NULL, OBJECT_TYPE VARCHAR2(32) NOT NULL, SOURCE_DIGEST VARCHAR2(128) NOT NULL,
        NORMALIZED_JSON CLOB NOT NULL, STATUS VARCHAR2(32) DEFAULT ''STAGED'' NOT NULL, ERROR_JSON CLOB,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT UK_CX_DIR_SOURCE UNIQUE (SYNC_BATCH_ID, CONNECTOR_ID, EXTERNAL_OBJECT_ID, OBJECT_TYPE))');
    create_table('CX_DIRECTORY_CONFLICTS', 'CREATE TABLE CX_DIRECTORY_CONFLICTS (
        CONFLICT_ID VARCHAR2(128) PRIMARY KEY, SYNC_BATCH_ID VARCHAR2(128) NOT NULL, SOURCE_RECORD_ID VARCHAR2(128),
        OBJECT_TYPE VARCHAR2(32) NOT NULL, OBJECT_ID VARCHAR2(128), FIELD_NAME VARCHAR2(128) NOT NULL,
        AUTHORITY_SOURCE VARCHAR2(32) NOT NULL, SOURCE_DIGEST VARCHAR2(128), PLATFORM_DIGEST VARCHAR2(128),
        RISK_LEVEL VARCHAR2(16) DEFAULT ''MEDIUM'' NOT NULL, STATUS VARCHAR2(32) DEFAULT ''OPEN'' NOT NULL,
        RESOLUTION VARCHAR2(32), RESOLUTION_REASON VARCHAR2(2000), RESOLVED_BY VARCHAR2(128), OVERRIDE_UNTIL TIMESTAMP,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, RESOLVED_AT TIMESTAMP)');
    create_table('CX_ORG_LIFECYCLE_CASES', 'CREATE TABLE CX_ORG_LIFECYCLE_CASES (
        LIFECYCLE_CASE_ID VARCHAR2(128) PRIMARY KEY, SUBJECT_TYPE VARCHAR2(16) NOT NULL, SUBJECT_ID VARCHAR2(128) NOT NULL,
        LIFECYCLE_TYPE VARCHAR2(32) NOT NULL, SOURCE_TYPE VARCHAR2(32) NOT NULL, SOURCE_REFERENCE_ID VARCHAR2(128),
        STATUS VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL, REASON VARCHAR2(2000) NOT NULL, INVENTORY_JSON CLOB,
        DUE_AT TIMESTAMP, CANCELLED_AT TIMESTAMP, COMPLETED_AT TIMESTAMP, ROW_VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,
        CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CK_CX_ORG_LIFE_SUBJ CHECK (SUBJECT_TYPE IN (''PERSON'',''ORGANIZATION'')),
        CONSTRAINT CK_CX_ORG_LIFE_TYPE CHECK (LIFECYCLE_TYPE IN (''DEPARTURE'',''RETIREMENT'')))');
    create_table('CX_ORG_DISPOSITIONS', 'CREATE TABLE CX_ORG_DISPOSITIONS (
        DISPOSITION_ID VARCHAR2(128) PRIMARY KEY, LIFECYCLE_CASE_ID VARCHAR2(128), CHANGE_SET_ID VARCHAR2(128),
        SUBJECT_TYPE VARCHAR2(32) NOT NULL, SUBJECT_ID VARCHAR2(128) NOT NULL, DISPOSITION_TYPE VARCHAR2(32) NOT NULL,
        TARGET_PRINCIPAL_ID VARCHAR2(128), TARGET_ORGANIZATION_ID VARCHAR2(128), STATUS VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL,
        REASON VARCHAR2(2000) NOT NULL, DECISION_JSON CLOB, DECIDED_BY VARCHAR2(128), DECIDED_AT TIMESTAMP,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
END;
/

DECLARE
    PROCEDURE create_index(p_name VARCHAR2, p_ddl VARCHAR2) IS l_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO l_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_name);
        IF l_count = 0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
    END;
BEGIN
    create_index('IDX_CX_ORG_PARENT','CREATE INDEX IDX_CX_ORG_PARENT ON CX_ORGANIZATIONS(PARENT_ID, STATUS, SORT_ORDER, ORGANIZATION_ID)');
    create_index('IDX_CX_ORG_CODE','CREATE INDEX IDX_CX_ORG_CODE ON CX_ORGANIZATIONS(ORGANIZATION_CODE)');
    create_index('IDX_CX_ORG_EXTERNAL','CREATE INDEX IDX_CX_ORG_EXTERNAL ON CX_ORGANIZATIONS(SOURCE_CONNECTOR_ID, EXTERNAL_OBJECT_ID)');
    create_index('IDX_CX_ORG_MEMBER_PRINCIPAL','CREATE INDEX IDX_CX_ORG_MEMBER_PRINCIPAL ON CX_ORGANIZATION_MEMBERS(PRINCIPAL_ID, STATUS, MEMBERSHIP_KIND, VALID_UNTIL)');
    create_index('IDX_CX_ORG_MEMBER_EXTERNAL','CREATE INDEX IDX_CX_ORG_MEMBER_EXTERNAL ON CX_ORGANIZATION_MEMBERS(SOURCE_CONNECTOR_ID, EXTERNAL_OBJECT_ID)');
    create_index('IDX_CX_REPORTING_ACTIVE_DIRECT','CREATE UNIQUE INDEX IDX_CX_REPORTING_ACTIVE_DIRECT ON CX_REPORTING_RELATIONSHIPS(CASE WHEN RELATIONSHIP_TYPE = ''DIRECT'' AND STATUS = ''ACTIVE'' THEN PRINCIPAL_ID END)');
    create_index('IDX_CX_REPORT_MANAGER','CREATE INDEX IDX_CX_REPORT_MANAGER ON CX_REPORTING_RELATIONSHIPS(MANAGER_PRINCIPAL_ID, RELATIONSHIP_TYPE, STATUS, VALID_UNTIL)');
    create_index('IDX_CX_REPORT_EXTERNAL','CREATE INDEX IDX_CX_REPORT_EXTERNAL ON CX_REPORTING_RELATIONSHIPS(SOURCE_CONNECTOR_ID, EXTERNAL_OBJECT_ID)');
    create_index('IDX_CX_ORG_CLOSURE_DESC','CREATE INDEX IDX_CX_ORG_CLOSURE_DESC ON CX_ORGANIZATION_CLOSURE(DESCENDANT_ID, DEPTH, ANCESTOR_ID)');
    create_index('IDX_CX_ORG_CLOSURE_ANCESTOR','CREATE INDEX IDX_CX_ORG_CLOSURE_ANCESTOR ON CX_ORGANIZATION_CLOSURE(ANCESTOR_ID, DEPTH, DESCENDANT_ID)');
    create_index('IDX_CX_ORG_VERSION_EFF','CREATE INDEX IDX_CX_ORG_VERSION_EFF ON CX_ORGANIZATION_VERSIONS(EFFECTIVE_AT, VERSION_NUMBER)');
    create_index('IDX_CX_ORG_UNIT_HIST','CREATE INDEX IDX_CX_ORG_UNIT_HIST ON CX_ORGANIZATION_UNIT_HISTORY(ORGANIZATION_ID, VALID_FROM, RECORDED_AT)');
    create_index('IDX_CX_ORG_MEMBER_HIST','CREATE INDEX IDX_CX_ORG_MEMBER_HIST ON CX_ORGANIZATION_MEMBER_HISTORY(PRINCIPAL_ID, VALID_FROM, RECORDED_AT)');
    create_index('IDX_CX_REPORTING_HIST','CREATE INDEX IDX_CX_REPORTING_HIST ON CX_REPORTING_HISTORY(PRINCIPAL_ID, VALID_FROM, RECORDED_AT)');
    create_index('IDX_CX_ORG_CHANGESET_STATE','CREATE INDEX IDX_CX_ORG_CHANGESET_STATE ON CX_ORG_CHANGESETS(STATUS, SCHEDULED_FOR, UPDATED_AT)');
    create_index('IDX_CX_ORG_CHANGE_TARGET','CREATE INDEX IDX_CX_ORG_CHANGE_TARGET ON CX_ORG_CHANGE_OPERATIONS(TARGET_TYPE, TARGET_ID, STATUS)');
    create_index('IDX_CX_DIR_BATCH','CREATE INDEX IDX_CX_DIR_BATCH ON CX_DIRECTORY_SYNC_BATCHES(CONNECTOR_ID, STATUS, STARTED_AT)');
    create_index('IDX_CX_DIR_SOURCE_KEY','CREATE INDEX IDX_CX_DIR_SOURCE_KEY ON CX_DIRECTORY_SOURCE_RECORDS(CONNECTOR_ID, OBJECT_TYPE, EXTERNAL_OBJECT_ID)');
    create_index('IDX_CX_DIRECTORY_CONFLICT','CREATE INDEX IDX_CX_DIRECTORY_CONFLICT ON CX_DIRECTORY_CONFLICTS(SYNC_BATCH_ID, STATUS, RISK_LEVEL)');
    create_index('IDX_CX_DIR_CONFLICT_OBJ','CREATE INDEX IDX_CX_DIR_CONFLICT_OBJ ON CX_DIRECTORY_CONFLICTS(OBJECT_TYPE, OBJECT_ID, STATUS)');
    create_index('IDX_CX_ORG_LIFE_SUBJECT','CREATE INDEX IDX_CX_ORG_LIFE_SUBJECT ON CX_ORG_LIFECYCLE_CASES(SUBJECT_TYPE, SUBJECT_ID, STATUS)');
    create_index('IDX_CX_ORG_LIFE_QUEUE','CREATE INDEX IDX_CX_ORG_LIFE_QUEUE ON CX_ORG_LIFECYCLE_CASES(STATUS, DUE_AT, UPDATED_AT)');
    create_index('IDX_CX_ORG_DISP_QUEUE','CREATE INDEX IDX_CX_ORG_DISP_QUEUE ON CX_ORG_DISPOSITIONS(STATUS, SUBJECT_TYPE, SUBJECT_ID)');
    create_index('IDX_CX_ORG_DISP_CASE','CREATE INDEX IDX_CX_ORG_DISP_CASE ON CX_ORG_DISPOSITIONS(LIFECYCLE_CASE_ID, CHANGE_SET_ID)');
    create_index('IDX_CX_AGENT_REL_PRINCIPAL','CREATE INDEX IDX_CX_AGENT_REL_PRINCIPAL ON CX_AGENT_RELATIONSHIPS(PRINCIPAL_ID, RELATIONSHIP_ROLE, STATUS, AGENT_ID)');
    create_index('IDX_CX_AGENT_REL_ORG','CREATE INDEX IDX_CX_AGENT_REL_ORG ON CX_AGENT_RELATIONSHIPS(RESPONSIBLE_ORGANIZATION_ID, RELATIONSHIP_ROLE, STATUS, AGENT_ID)');
END;
/

DECLARE l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM (
        SELECT PRINCIPAL_ID FROM CX_ORGANIZATION_MEMBERS
         WHERE MEMBERSHIP_KIND = 'PRIMARY' AND STATUS = 'ACTIVE'
         GROUP BY PRINCIPAL_ID HAVING COUNT(*) > 1
    );
    IF l_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20031, 'v4.3.1 organization migration refused: a Human has multiple active primary memberships');
    END IF;
    SELECT COUNT(*) INTO l_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CX_ORG_ACTIVE_PRIMARY';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_CX_ORG_ACTIVE_PRIMARY ON CX_ORGANIZATION_MEMBERS(CASE WHEN MEMBERSHIP_KIND = ''PRIMARY'' AND STATUS = ''ACTIVE'' THEN PRINCIPAL_ID END)';
    END IF;
END;
/

DECLARE l_count NUMBER; l_duplicates NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_duplicates FROM (
        SELECT AGENT_ID FROM CX_AGENT_RELATIONSHIPS
         WHERE RELATIONSHIP_ROLE = 'PRIMARY_OWNER' AND STATUS = 'ACTIVE'
         GROUP BY AGENT_ID HAVING COUNT(*) > 1
    );
    IF l_duplicates > 0 THEN
        RAISE_APPLICATION_ERROR(-20032, 'v4.3.1 organization migration refused: an Agent has multiple active primary owners');
    END IF;
    SELECT COUNT(*) INTO l_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CX_AGENT_PRIMARY_OWNER';
    IF l_count > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX IDX_CX_AGENT_PRIMARY_OWNER'; END IF;
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_CX_AGENT_PRIMARY_OWNER ON CX_AGENT_RELATIONSHIPS(CASE WHEN RELATIONSHIP_ROLE = ''PRIMARY_OWNER'' AND STATUS = ''ACTIVE'' THEN AGENT_ID END)';
END;
/

DECLARE l_cycles NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_cycles FROM (
        SELECT CONNECT_BY_ISCYCLE IS_CYCLE FROM CX_ORGANIZATIONS
         START WITH ORGANIZATION_ID IS NOT NULL
        CONNECT BY NOCYCLE PRIOR ORGANIZATION_ID = PARENT_ID
    ) WHERE IS_CYCLE = 1;
    IF l_cycles > 0 THEN
        RAISE_APPLICATION_ERROR(-20033, 'v4.3.1 organization migration refused: hierarchy contains a cycle');
    END IF;
END;
/

DELETE FROM CX_ORGANIZATION_CLOSURE;
MERGE INTO CX_ORGANIZATION_CLOSURE dst
USING (
    SELECT ANCESTOR_ID, DESCENDANT_ID, MIN(DEPTH) DEPTH FROM (
        SELECT CONNECT_BY_ROOT ORGANIZATION_ID ANCESTOR_ID,
               ORGANIZATION_ID DESCENDANT_ID, LEVEL - 1 DEPTH
          FROM CX_ORGANIZATIONS START WITH ORGANIZATION_ID IS NOT NULL
        CONNECT BY NOCYCLE PRIOR ORGANIZATION_ID = PARENT_ID
    ) GROUP BY ANCESTOR_ID, DESCENDANT_ID
) src ON (dst.ANCESTOR_ID = src.ANCESTOR_ID AND dst.DESCENDANT_ID = src.DESCENDANT_ID)
WHEN MATCHED THEN UPDATE SET dst.DEPTH = src.DEPTH, dst.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (ANCESTOR_ID, DESCENDANT_ID, DEPTH)
VALUES (src.ANCESTOR_ID, src.DESCENDANT_ID, src.DEPTH);

MERGE INTO CX_REPORTING_RELATIONSHIPS dst
USING (
    SELECT 'V431-RPT-' || SUBSTR(MIN(m.MEMBERSHIP_ID), 1, 119) RELATIONSHIP_ID,
           m.PRINCIPAL_ID, MIN(m.MANAGER_PRINCIPAL_ID) MANAGER_PRINCIPAL_ID
      FROM CX_ORGANIZATION_MEMBERS m
      JOIN CX_PRINCIPALS p ON p.PRINCIPAL_ID = m.PRINCIPAL_ID AND p.PRINCIPAL_TYPE = 'HUMAN' AND p.STATUS = 'ACTIVE'
      JOIN CX_PRINCIPALS mgr ON mgr.PRINCIPAL_ID = m.MANAGER_PRINCIPAL_ID AND mgr.PRINCIPAL_TYPE = 'HUMAN' AND mgr.STATUS = 'ACTIVE'
     WHERE m.MANAGER_PRINCIPAL_ID IS NOT NULL AND m.MANAGER_PRINCIPAL_ID <> m.PRINCIPAL_ID
       AND m.STATUS = 'ACTIVE' AND (m.VALID_UNTIL IS NULL OR m.VALID_UNTIL > SYSTIMESTAMP)
     GROUP BY m.PRINCIPAL_ID HAVING COUNT(DISTINCT m.MANAGER_PRINCIPAL_ID) = 1
) src ON (dst.RELATIONSHIP_ID = src.RELATIONSHIP_ID)
WHEN NOT MATCHED THEN INSERT
    (RELATIONSHIP_ID, PRINCIPAL_ID, MANAGER_PRINCIPAL_ID, RELATIONSHIP_TYPE, SOURCE_TYPE, STATUS, UPDATED_BY)
VALUES (src.RELATIONSHIP_ID, src.PRINCIPAL_ID, src.MANAGER_PRINCIPAL_ID, 'DIRECT', 'SYSTEM', 'ACTIVE', 'MIGRATION_V4_3_1');

MERGE INTO CX_ORGANIZATION_VERSIONS dst
USING (SELECT 'V431-BASELINE' VERSION_ID FROM DUAL) src ON (dst.VERSION_ID = src.VERSION_ID)
WHEN NOT MATCHED THEN INSERT (VERSION_ID, VERSION_NUMBER, STATUS, REASON, CREATED_BY)
VALUES ('V431-BASELINE', 1, 'CURRENT', 'v4.3.1 baseline adopted from current organization facts', 'MIGRATION_V4_3_1');

-- Synchronize only system-managed templates. Service/profile capability gates
-- remain authoritative for Enterprise-only actions.
DECLARE
    FUNCTION same_clob(p_left CLOB, p_right CLOB) RETURN NUMBER IS
        l_length NUMBER; l_offset NUMBER := 1;
        l_left_chunk VARCHAR2(4000); l_right_chunk VARCHAR2(4000);
    BEGIN
        IF p_left IS NULL OR p_right IS NULL THEN
            IF p_left IS NULL AND p_right IS NULL THEN RETURN 1; END IF;
            RETURN 0;
        END IF;
        IF NVL(LENGTH(p_left), 0) <> NVL(LENGTH(p_right), 0) THEN RETURN 0; END IF;
        l_length := NVL(LENGTH(p_left), 0);
        WHILE l_offset <= l_length LOOP
            l_left_chunk := DBMS_LOB.SUBSTR(p_left, 4000, l_offset);
            l_right_chunk := DBMS_LOB.SUBSTR(p_right, 4000, l_offset);
            IF (l_left_chunk <> l_right_chunk)
               OR (l_left_chunk IS NULL AND l_right_chunk IS NOT NULL)
               OR (l_left_chunk IS NOT NULL AND l_right_chunk IS NULL) THEN RETURN 0; END IF;
            IF NVL(LENGTH(l_left_chunk), 0) = 0 THEN RETURN 0; END IF;
            l_offset := l_offset + LENGTH(l_left_chunk);
        END LOOP;
        RETURN 1;
    END;
    PROCEDURE sync_role(p_code VARCHAR2, p_name VARCHAR2, p_permissions CLOB, p_scopes CLOB) IS
        l_name CX_ROLE_TEMPLATES.DISPLAY_NAME%TYPE;
        l_permissions CX_ROLE_TEMPLATES.PERMISSIONS_JSON%TYPE;
        l_scopes CX_ROLE_TEMPLATES.DATA_SCOPES_JSON%TYPE;
        l_managed CX_ROLE_TEMPLATES.MANAGED%TYPE;
    BEGIN
        BEGIN
            SELECT DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON, MANAGED
              INTO l_name, l_permissions, l_scopes, l_managed
              FROM CX_ROLE_TEMPLATES WHERE ROLE_CODE = p_code FOR UPDATE;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            INSERT INTO CX_ROLE_TEMPLATES
                (ROLE_CODE, DISPLAY_NAME, PERMISSIONS_JSON, DATA_SCOPES_JSON, VERSION, MANAGED)
            VALUES (p_code, p_name, p_permissions, p_scopes, 1, 'Y');
            RETURN;
        END;
        IF l_managed = 'Y' AND (l_name <> p_name OR same_clob(l_permissions, p_permissions) = 0
                                OR same_clob(l_scopes, p_scopes) = 0) THEN
            UPDATE CX_ROLE_TEMPLATES SET DISPLAY_NAME = p_name, PERMISSIONS_JSON = p_permissions,
                   DATA_SCOPES_JSON = p_scopes, VERSION = NVL(VERSION, 1) + 1, UPDATED_AT = SYSTIMESTAMP
             WHERE ROLE_CODE = p_code;
        END IF;
    END;
BEGIN
    sync_role('END_USER','End User','["profile.read","profile.update","agents.enroll","agents.read","channels.read","channels.write","tasks.read","workspaces.read","knowledge.read","memory.read","skills.read","specs.read","branches.read","collab.read","loops.read","graphs.read","notifications.read","organizations.read"]','["OWNED","ASSIGNED"]');
    sync_role('SYSTEM_ADMIN','System Administrator','["*"]','["ALL"]');
    sync_role('SECURITY_ADMIN','Security Administrator','["security.*","sessions.revoke","domains.manage","profile.update","users.identity.link","users.security.manage","users.sessions.read","users.delegations.read","users.delegations.manage","agents.claim","channels.bridge","channels.lifecycle","channels.delete","channels.manage_members","channels.quarantine","memory.review","agents.transfer","agents.offboard","barriers.recover","notifications.manage","barriers.create","channels.actions.decide","organizations.read","organizations.changes.approve","organizations.emergency"]','["SECURITY_DOMAIN"]');
    sync_role('AGENT_MANAGER','Agent Manager','["agents.read","agents.enroll","agents.manage","agents.operate","agents.transfer","agents.offboard","channels.read","channels.create","channels.manage_members","channels.lifecycle","barriers.create","channels.actions.decide","users.read","notifications.manage","profile.update","organizations.read","organizations.agent_relationships.read"]','["ORG_SUBTREE"]');
    sync_role('ORG_MANAGER','Organization Manager','["organizations.read","organizations.manage","organizations.people.read","organizations.agents.read","organizations.anomalies.read","organizations.changes.create","organizations.changes.write","organizations.changes.submit","organizations.history.read","organizations.members.manage","organizations.reporting.manage","organizations.sync.manage","agents.read","users.read","profile.update"]','["ORG_SUBTREE"]');
    sync_role('USER_ADMIN','User Administrator','["users.read","users.read.all","users.approve","users.roles.manage","users.permissions.manage","users.identity.link","users.security.manage","users.sessions.read","users.delegations.read","users.delegations.manage","organizations.read","organizations.members.manage","organizations.reporting.manage","organizations.sync.manage"]','["ORG_SUBTREE"]');
    sync_role('APPROVER','Approver','["approvals.read","approvals.decide","channels.actions.decide","barriers.release","barriers.recover","memory.review","profile.update","organizations.read","organizations.changes.approve"]','["ASSIGNED"]');
    sync_role('AUDITOR','Auditor','["audit.read","audit.export","users.read","profile.update","organizations.read","organizations.history.read","organizations.export"]','["SECURITY_DOMAIN"]');
END;
/
