PROMPT ============================================================
PROMPT AI Agent Infra v3.10.2 - YashanDB Community Edition - Schema Deployment
PROMPT ============================================================

PROMPT Creating helper procedures...

CREATE OR REPLACE PROCEDURE safe_ddl(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SAFE_DDL skipped: ' || p_sql || ' - ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE safe_idx(p_sql IN VARCHAR2) IS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            DBMS_OUTPUT.PUT_LINE('SAFE_IDX error: ' || p_sql || ' - ' || SQLERRM);
        END IF;
END;
/

PROMPT Dropping old property graph...
BEGIN safe_ddl('DROP PROPERTY GRAPH IF EXISTS YASHAN_MEMORY_GRAPH'); END;
/

PROMPT Dropping old views...
BEGIN safe_ddl('DROP VIEW IF EXISTS MEMORY_DV'); END;
/
BEGIN safe_ddl('DROP VIEW IF EXISTS KNOWLEDGE_DV'); END;
/
BEGIN safe_ddl('DROP VIEW IF EXISTS WORKSPACE_DV'); END;
/
BEGIN safe_ddl('DROP VIEW IF EXISTS CONTEXT_DV'); END;
/
BEGIN safe_ddl('DROP VIEW IF EXISTS SPEC_DV'); END;
/
BEGIN safe_ddl('DROP VIEW IF EXISTS COLLAB_GROUP_DV'); END;
/

PROMPT Dropping all tables...
BEGIN
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name != 'DBTOOLS$MCP_LOG') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Skip: ' || r.table_name || ' - ' || SQLERRM);
        END;
    END LOOP;
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name != 'DBTOOLS$MCP_LOG') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

PROMPT ============================================================
PROMPT 1. ENTITIES (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE ENTITIES (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    TITLE           VARCHAR2(512) NOT NULL,
    CONTENT         CLOB,
    SUMMARY         VARCHAR2(2000),
    CATEGORY        VARCHAR2(64),
    STATUS          VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    OWNED_BY_AGENT  VARCHAR2(64),
    SOURCE_AGENT    VARCHAR2(64),
    VISIBILITY      VARCHAR2(16)  DEFAULT 'PRIVATE' NOT NULL,
    IMPORTANCE      NUMBER(3,0)   DEFAULT 5 NOT NULL,
    RETRIEVAL_COUNT NUMBER(10,0)  DEFAULT 0 NOT NULL,
    WORKSPACE_ID    VARCHAR2(64),
    EXPIRES_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITIES PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_ENTITIES_STATUS CHECK (STATUS IN ('ACTIVE','ARCHIVED','DELETED','DRAFT')),
    CONSTRAINT CK_ENTITIES_VISIBILITY CHECK (VISIBILITY IN ('PRIVATE','SHARED','PUBLIC')),
    CONSTRAINT CK_ENTITIES_IMPORTANCE CHECK (IMPORTANCE BETWEEN 1 AND 10),
    CONSTRAINT CK_ENTITIES_TYPE CHECK (ENTITY_TYPE IN ('MEMORY','KNOWLEDGE','TASK_OUTPUT','EXPERIENCE','HARNESS_TEMPLATE','SPEC','SKILL','LOOP_DEFINITION','AGENT','TASK_STEP','APPROVAL','LOOP_ITERATION','OTHER'))
) PARTITION BY LIST (ENTITY_TYPE)
(
    PARTITION P_MEMORY        VALUES ('MEMORY'),
    PARTITION P_KNOWLEDGE     VALUES ('KNOWLEDGE'),
    PARTITION P_TASK_OUTPUT   VALUES ('TASK_OUTPUT'),
    PARTITION P_EXPERIENCE    VALUES ('EXPERIENCE'),
    PARTITION P_HARNESS       VALUES ('HARNESS_TEMPLATE'),
    PARTITION P_SPEC         VALUES ('SPEC'),
    PARTITION P_SKILL        VALUES ('SKILL'),
    PARTITION P_OTHERS        VALUES (DEFAULT)
);

ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES_ID UNIQUE (ENTITY_ID);

PROMPT ============================================================
PROMPT 2. ENTITY_EDGES (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EDGES (
    EDGE_ID       VARCHAR2(64)  NOT NULL,
    SOURCE_ID     VARCHAR2(64)  NOT NULL,
    SOURCE_TYPE   VARCHAR2(32)  NOT NULL,
    TARGET_ID     VARCHAR2(64)  NOT NULL,
    EDGE_TYPE     VARCHAR2(64)  NOT NULL,
    STRENGTH      NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CONFIDENCE    NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    METADATA      JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EDGES PRIMARY KEY (EDGE_ID, SOURCE_ID),
    CONSTRAINT CK_EDGE_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1),
    CONSTRAINT CK_EDGE_CONFIDENCE CHECK (CONFIDENCE BETWEEN 0 AND 1)
);

ALTER TABLE ENTITY_EDGES ADD CONSTRAINT UK_EDGES_ID UNIQUE (EDGE_ID);

PROMPT ============================================================
PROMPT 3. KNOWLEDGE_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE KNOWLEDGE_META (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  DEFAULT 'KNOWLEDGE' NOT NULL,
    DOMAIN          VARCHAR2(128),
    TOPIC           VARCHAR2(256),
    DIFFICULTY      VARCHAR2(16)  DEFAULT 'INTERMEDIATE' NOT NULL,
    REVIEW_COUNT    NUMBER(10,0)  DEFAULT 0 NOT NULL,
    LAST_REVIEWED   TIMESTAMP,
    NEXT_REVIEW     TIMESTAMP,
    CONSTRAINT PK_KNOWLEDGE_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_KM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'KNOWLEDGE'),
    CONSTRAINT CK_KM_DIFFICULTY CHECK (DIFFICULTY IN ('BEGINNER','INTERMEDIATE','ADVANCED','EXPERT'))
);

PROMPT ============================================================
PROMPT 4. ENTITY_EMBEDDINGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_EMBEDDINGS (
    ENTITY_ID       VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE     VARCHAR2(32)  NOT NULL,
    EMBEDDING       VECTOR(1024) NOT NULL,
    EMBEDDING_MODEL VARCHAR2(128),
    EMBEDDING_DIM   NUMBER(5,0)   NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_EMBEDDINGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE)
);

PROMPT ============================================================
PROMPT 5. HARNESS_META (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE HARNESS_META (
    ENTITY_ID         VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE       VARCHAR2(32)  DEFAULT 'HARNESS_TEMPLATE' NOT NULL,
    TEMPLATE_VERSION  VARCHAR2(32)  NOT NULL,
    INPUT_SCHEMA      JSON,
    OUTPUT_SCHEMA     JSON,
    EXECUTION_MODE    VARCHAR2(32)  DEFAULT 'SEQUENTIAL' NOT NULL,
    CONSTRAINT PK_HARNESS_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_HM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'HARNESS_TEMPLATE'),
    CONSTRAINT CK_HM_EXEC_MODE CHECK (EXECUTION_MODE IN ('SEQUENTIAL','PARALLEL','CONDITIONAL'))
);


PROMPT ============================================================
PROMPT 11b. CONTEXT_BRANCHES (Non-Partitioned) [NEW v3.3.0]
PROMPT ============================================================

CREATE TABLE CONTEXT_BRANCHES (
    BRANCH_ID        VARCHAR2(64)  PRIMARY KEY,
    WORKSPACE_ID     VARCHAR2(64)  NOT NULL,
    PARENT_BRANCH_ID VARCHAR2(64),
    FORK_CONTEXT_ID  VARCHAR2(64),
    FORK_SESSION_ID  VARCHAR2(64),
    BRANCH_NAME      VARCHAR2(256) NOT NULL,
    BRANCH_TYPE      VARCHAR2(32)  NOT NULL,
    BRANCH_STATUS    VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    AGENT_ID         VARCHAR2(64),
    SOURCE_AGENT_ID  VARCHAR2(64),
    BRANCH_PURPOSE   VARCHAR2(1000),
    METADATA         JSON,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CLOSED_AT        TIMESTAMP,
    CONSTRAINT CK_CB_TYPE CHECK (BRANCH_TYPE IN ('EXPLORATION','ROLLBACK','HANDOFF','PARALLEL')),
    CONSTRAINT CK_CB_STATUS CHECK (BRANCH_STATUS IN ('ACTIVE','MERGED','ABANDONED','PAUSED'))
);

PROMPT ============================================================

PROMPT 5b. SPEC_META (Reference Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE SPEC_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'SPEC' NOT NULL,
    SPEC_VERSION        NUMBER(6,0)   DEFAULT 1 NOT NULL,
    SPEC_STATUS         VARCHAR2(32)  DEFAULT 'DRAFT' NOT NULL,
    ACCEPTANCE_CRITERIA JSON,
    "CONSTRAINTS"         JSON,
    SPEC_SCOPE          VARCHAR2(64),
    COMPLEXITY          VARCHAR2(16)  DEFAULT 'MEDIUM' NOT NULL,
    BRANCH_ID           VARCHAR2(64),
    PARENT_SPEC_ID      VARCHAR2(64),
    CONSTRAINT PK_SPEC_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_SM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'SPEC'),
    CONSTRAINT CK_SM_SPEC_STATUS CHECK (SPEC_STATUS IN ('DRAFT','REVIEWED','APPROVED','IMPLEMENTED','DEPRECATED')),
    CONSTRAINT CK_SM_COMPLEXITY CHECK (COMPLEXITY IN ('LOW','MEDIUM','HIGH','CRITICAL'))
);

PROMPT ============================================================
PROMPT 5c. SKILL_META (Reference Partitioned) [NEW v3.1.0]
PROMPT ============================================================

CREATE TABLE SKILL_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'SKILL' NOT NULL,
    SKILL_NAME          VARCHAR2(256) NOT NULL,
    SKILL_VERSION       VARCHAR2(32)  DEFAULT '1.0.0' NOT NULL,
    SKILL_TYPE          VARCHAR2(32)  DEFAULT 'CUSTOM' NOT NULL,
    SKILL_FORMAT        VARCHAR2(32)  DEFAULT 'TEXT' NOT NULL,
    TEXT_CONTENT        CLOB,
    RESOURCE_URI        VARCHAR2(2048),
    RESOURCE_CHECKSUM   VARCHAR2(128),
    RUNTIME             VARCHAR2(32)  DEFAULT 'PYTHON' NOT NULL,
    PARAMETERS          JSON,
    DEPENDENCIES        JSON,
    SKILL_STATUS        VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    RESOURCE_FILENAME   VARCHAR2(512),
    RESOURCE_SIZE       NUMBER,
    RESOURCE_MIME_TYPE  VARCHAR2(128),
    RESOURCE_SERVER_HOST VARCHAR2(512),
    SKILL_DESCRIPTION   CLOB,
    CONSTRAINT PK_SKILL_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_SKM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'SKILL'),
    CONSTRAINT CK_SKM_TYPE CHECK (SKILL_TYPE IN ('BUILTIN','CUSTOM')),
    CONSTRAINT CK_SKM_FORMAT CHECK (SKILL_FORMAT IN ('TEXT','SCRIPT','HYBRID')),
    CONSTRAINT CK_SKM_RUNTIME CHECK (RUNTIME IN ('PYTHON','BASH','NODE','OTHER')),
    CONSTRAINT CK_SKM_STATUS CHECK (SKILL_STATUS IN ('ACTIVE','DEPRECATED','DISABLED'))
);

PROMPT ============================================================
PROMPT 6. TAGS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TAGS (
    TAG_ID    NUMBER(10,0)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TAG_NAME  VARCHAR2(128) NOT NULL,
    TAG_GROUP VARCHAR2(64),
    CONSTRAINT UK_TAGS_NAME UNIQUE (TAG_NAME)
);

PROMPT ============================================================
PROMPT 7. ENTITY_TAGS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE ENTITY_TAGS (
    ENTITY_ID   VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE VARCHAR2(32)  NOT NULL,
    TAG_ID      NUMBER(10,0)  NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ENTITY_TAGS PRIMARY KEY (ENTITY_ID, ENTITY_TYPE, TAG_ID)
);

PROMPT ============================================================
PROMPT 8. SYSTEM_USERS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_USERS (
    USER_ID     VARCHAR2(64)  PRIMARY KEY,
    USERNAME    VARCHAR2(128) NOT NULL,
    PASSWORD_HASH VARCHAR2(256),
    ROLE        VARCHAR2(64)  DEFAULT 'USER' NOT NULL,
    STATUS      VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    AUTH_SOURCE VARCHAR2(16)  DEFAULT '' NOT NULL,
    LDAP_DN     VARCHAR2(512),
    LAST_LDAP_SYNC TIMESTAMP,
    LAST_LOGIN  TIMESTAMP,
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SU_ROLE CHECK (ROLE IN ('ADMIN','USER','SERVICE')),
    CONSTRAINT CK_SU_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','LOCKED')),
    CONSTRAINT CK_SU_AUTH_SOURCE CHECK (AUTH_SOURCE IN ('','LDAP'))
);

PROMPT ============================================================
PROMPT 9. AGENT_REGISTRY (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_REGISTRY (
    AGENT_ID       VARCHAR2(64)  PRIMARY KEY,
    AGENT_NAME     VARCHAR2(256) NOT NULL,
    AGENT_TYPE     VARCHAR2(64),
    DESCRIPTION    VARCHAR2(2000),
    CAPABILITIES   JSON,
    CONFIG         JSON,
    WM_ENTITY_ID   VARCHAR2(64),
    STATUS         VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    LAST_SEEN_AT   TIMESTAMP,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY_AGENT_ID VARCHAR2(64),
    AGENT_ROLE        VARCHAR2(32)  DEFAULT 'WORKER' NOT NULL,
    CURRENT_USER_ID   VARCHAR2(64),
    POOL_CONFIG       JSON,
    LAST_ACTIVE_AT    TIMESTAMP,
    CONSTRAINT CK_APRV_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','SUSPENDED','DECOMMISSIONED','DORMANT','POOL')),
    CONSTRAINT CK_AR_ROLE CHECK (AGENT_ROLE IN ('WORKER','COORDINATOR','SYSTEM'))
);


PROMPT ============================================================
PROMPT 9b. AGENT_CREDENTIALS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE AGENT_CREDENTIALS (
    CREDENTIAL_ID    VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID         VARCHAR2(64)  NOT NULL,
    USER_ID          VARCHAR2(64)  NOT NULL,
    CREDENTIAL_TYPE  VARCHAR2(32)  NOT NULL,
    CREDENTIAL_VALUE VARCHAR2(512) NOT NULL,
    SCOPE            JSON          NOT NULL,
    EXPIRES_AT       TIMESTAMP,
    IS_ACTIVE        VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_AC_TYPE CHECK (CREDENTIAL_TYPE IN ('ACCESS_TOKEN','SESSION_KEY','PASSWORD_HASH')),
    CONSTRAINT CK_AC_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

PROMPT ============================================================
PROMPT 10. WORKSPACES (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACES (
    WORKSPACE_ID       VARCHAR2(64)  PRIMARY KEY,
    OWNER_USER_ID      VARCHAR2(64),
    WORKSPACE_NAME     VARCHAR2(256) NOT NULL,
    WORKSPACE_TYPE     VARCHAR2(32)  DEFAULT 'CONVERSATION' NOT NULL,
    STATUS             VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    ISOLATION_MODE     VARCHAR2(16)  DEFAULT 'SHARED' NOT NULL,
    CURRENT_AGENT_ID   VARCHAR2(64),
    CURRENT_SESSION_ID VARCHAR2(64),
    SUMMARY            VARCHAR2(2000),
    METADATA           JSON,
    CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    WORKSPACE_ALIAS    VARCHAR2(256),
    CONSTRAINT CK_WS_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED','COMPLETED','ABANDONED')),
    CONSTRAINT CK_WS_TYPE CHECK (WORKSPACE_TYPE IN ('CONVERSATION','PROJECT','TASK_CHAIN','AUTONOMOUS','COLLAB_GROUP','PERSONAL_IN_GROUP')),
    CONSTRAINT CK_WS_ISOLATION CHECK (ISOLATION_MODE IN ('SHARED','ISOLATED'))
);

PROMPT ============================================================
PROMPT 11. WORKSPACE_CONTEXT (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACE_CONTEXT (
    CONTEXT_ID        VARCHAR2(64)  PRIMARY KEY,
    WORKSPACE_ID      VARCHAR2(64)  NOT NULL,
    AGENT_ID          VARCHAR2(64)  NOT NULL,
    SESSION_ID        VARCHAR2(64),
    CONTEXT_TYPE      VARCHAR2(32)  NOT NULL,
    CONTEXT_DATA      JSON          NOT NULL,
    PARENT_CONTEXT_ID VARCHAR2(64),
    BRANCH_ID         VARCHAR2(64),
    VISIBILITY        VARCHAR2(20)  DEFAULT 'SHARED' NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_WC_TYPE CHECK (CONTEXT_TYPE IN ('CHECKPOINT','HANDOFF','SUMMARY','ERROR_STATE','AUTO_SAVE','CHAT_MESSAGE','BRANCH_POINT')),
    CONSTRAINT CK_WS_CTX_VISIBILITY CHECK (VISIBILITY IN ('PRIVATE', 'SHARED', 'PUBLIC'))
);

PROMPT ============================================================
PROMPT 11c. BRANCH_MERGE_LOG (Non-Partitioned) [NEW v3.3.0]
PROMPT ============================================================

CREATE TABLE BRANCH_MERGE_LOG (
    MERGE_ID         VARCHAR2(64)  PRIMARY KEY,
    SOURCE_BRANCH_ID VARCHAR2(64)  NOT NULL,
    TARGET_BRANCH_ID VARCHAR2(64)  NOT NULL,
    MERGE_TYPE       VARCHAR2(32)  NOT NULL,
    MERGED_BY_AGENT  VARCHAR2(64),
    MERGE_CONTEXT_ID VARCHAR2(64),
    CONFLICTS        JSON,
    MERGE_RESULT     VARCHAR2(32)  DEFAULT 'SUCCESS' NOT NULL,
    CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_BML_TYPE CHECK (MERGE_TYPE IN ('MERGE','CHERRY_PICK','REBASE')),
    CONSTRAINT CK_BML_RESULT CHECK (MERGE_RESULT IN ('SUCCESS','PARTIAL','CONFLICT','ABORTED'))
);

PROMPT ============================================================
PROMPT 12. WORKSPACE_TASKS - deferred after TASK_PLANS
PROMPT ============================================================

PROMPT ============================================================
PROMPT 13. AGENT_SESSION (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE AGENT_SESSION (
    SESSION_ID             VARCHAR2(64)  NOT NULL,
    AGENT_ID               VARCHAR2(64)  NOT NULL,
    WM_ENTITY_ID           VARCHAR2(64),
    OWNER_USER_ID          VARCHAR2(64),
    WORKSPACE_ID           VARCHAR2(64),
    PREDECESSOR_SESSION_ID VARCHAR2(64),
    BRANCH_ID              VARCHAR2(64),
    IS_ACTIVE              VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    START_TIME             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    END_TIME               TIMESTAMP,
    CONTEXT                JSON,
    LAST_ACTIVE_AT         TIMESTAMP,
    CONSTRAINT PK_AGENT_SESSION PRIMARY KEY (SESSION_ID, IS_ACTIVE),
    CONSTRAINT CK_AS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

ALTER TABLE AGENT_SESSION ENABLE ROW MOVEMENT;

ALTER TABLE AGENT_SESSION ADD CONSTRAINT UK_SESSION_ID UNIQUE (SESSION_ID);
ALTER TABLE AGENT_SESSION ADD CONSTRAINT FK_SESSION_PREDECESSOR FOREIGN KEY (PREDECESSOR_SESSION_ID) REFERENCES AGENT_SESSION(SESSION_ID);

PROMPT ============================================================
PROMPT 14. ENTITY_ACCESS_LOG (Partitioned by RANGE + HASH)
PROMPT ============================================================

CREATE TABLE ENTITY_ACCESS_LOG (
    LOG_ID        VARCHAR2(64)  NOT NULL,
    ENTITY_ID     VARCHAR2(64)  NOT NULL,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    ACCESS_TYPE   VARCHAR2(32)  NOT NULL,
    ACCESS_TIME   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    SESSION_ID    VARCHAR2(64),
    CONTEXT       JSON,
    CONSTRAINT CK_EAL_ACCESS_TYPE CHECK (ACCESS_TYPE IN ('READ','WRITE','DELETE','SEARCH','EMBED'))
);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT UK_ACCESS_LOG_ID UNIQUE (LOG_ID);

ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);
ALTER TABLE ENTITY_ACCESS_LOG ADD CONSTRAINT FK_EAL_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID);

PROMPT ============================================================
PROMPT 15. AGENT_PERMISSION_LOG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_PERMISSION_LOG (
    LOG_ID        VARCHAR2(64)  PRIMARY KEY,
    AGENT_ID      VARCHAR2(64)  NOT NULL,
    GRANTED_BY    VARCHAR2(64),
    PERMISSION    VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE VARCHAR2(64)  NOT NULL,
    RESOURCE_ID   VARCHAR2(64)  NOT NULL,
    ACTION        VARCHAR2(32)  NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_APL_ACTION CHECK (ACTION IN ('GRANT','REVOKE','DENY'))
);

PROMPT ============================================================
PROMPT 16. AGENT_COLLABORATION (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE AGENT_COLLABORATION (
    COL_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_AGENT_ID VARCHAR2(64)  NOT NULL,
    TARGET_AGENT_ID VARCHAR2(64)  NOT NULL,
    COL_TYPE        VARCHAR2(64)  NOT NULL,
    ENTITY_ID       VARCHAR2(64),
    CONTEXT         JSON,
    STRENGTH        NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_COL_STRENGTH CHECK (STRENGTH BETWEEN 0 AND 1)
);


PROMPT ============================================================
PROMPT 16b. COLLAB_GROUPS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE COLLAB_GROUPS (
    GROUP_ID             VARCHAR2(64)  PRIMARY KEY,
    GROUP_NAME           VARCHAR2(256) NOT NULL,
    GROUP_TYPE           VARCHAR2(32)  NOT NULL,
    DESCRIPTION          VARCHAR2(2000),
    WORKSPACE_ID         VARCHAR2(64),
    COORDINATOR_AGENT_ID VARCHAR2(64),
    SHARING_POLICY       VARCHAR2(32)  DEFAULT 'OPEN' NOT NULL,
    STATUS               VARCHAR2(32)  DEFAULT 'ACTIVE' NOT NULL,
    METADATA             JSON,
    BRANCH_ID            VARCHAR2(64),
    SPEC_ID              VARCHAR2(64),
    CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CG_TYPE CHECK (GROUP_TYPE IN ('PROJECT','TEAM','AD_HOC','PIPELINE')),
    CONSTRAINT CK_CG_POLICY CHECK (SHARING_POLICY IN ('OPEN','MODERATED','RESTRICTED')),
    CONSTRAINT CK_CG_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED','ARCHIVED'))
);

PROMPT ============================================================
PROMPT 16c. COLLAB_GROUP_MEMBERS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE COLLAB_GROUP_MEMBERS (
    MEMBER_ID               VARCHAR2(64)  PRIMARY KEY,
    GROUP_ID                VARCHAR2(64)  NOT NULL,
    AGENT_ID                VARCHAR2(64)  NOT NULL,
    ROLE                    VARCHAR2(32)  DEFAULT 'MEMBER' NOT NULL,
    PERSONAL_WORKSPACE_ID   VARCHAR2(64),
    BRANCH_ID               VARCHAR2(64),
    JOINED_AT               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS                  VARCHAR2(16)  DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT CK_CGM_ROLE CHECK (ROLE IN ('LEAD','MEMBER','OBSERVER','CONTRIBUTOR')),
    CONSTRAINT CK_CGM_STATUS CHECK (STATUS IN ('ACTIVE','LEFT','REMOVED')),
    CONSTRAINT UK_CGM_MEMBERSHIP UNIQUE (GROUP_ID, AGENT_ID)
);

PROMPT ============================================================
PROMPT 17. TASK_PLANS (Partitioned by LIST + RANGE)
PROMPT ============================================================

CREATE TABLE TASK_PLANS (
    PLAN_ID        VARCHAR2(64)   NOT NULL,
    AGENT_ID       VARCHAR2(64)   NOT NULL,
    GOAL           VARCHAR2(2000) NOT NULL,
    STATUS         VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    PRIORITY       NUMBER(3,0)    DEFAULT 5 NOT NULL,
    STRATEGY       VARCHAR2(64),
    RESULT_SUMMARY VARCHAR2(2000),
    BRANCH_ID      VARCHAR2(64),
    CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT   TIMESTAMP,
    CONSTRAINT PK_TASK_PLANS PRIMARY KEY (PLAN_ID, STATUS),
    CONSTRAINT CK_TP_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','CANCELLED')),
    CONSTRAINT CK_TP_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 10)
);

ALTER TABLE TASK_PLANS ADD CONSTRAINT UK_TASK_PLANS_ID UNIQUE (PLAN_ID);

ALTER TABLE TASK_PLANS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 18. TASK_STEPS (Reference Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_STEPS (
    STEP_ID       VARCHAR2(64)   NOT NULL,
    PLAN_ID       VARCHAR2(64)   NOT NULL,
    PLAN_STATUS   VARCHAR2(30)   NOT NULL,
    STEP_ORDER    NUMBER(5,0)    NOT NULL,
    DESCRIPTION   VARCHAR2(2000) NOT NULL,
    TOOL_NAME     VARCHAR2(128),
    TOOL_INPUT    JSON,
    TOOL_OUTPUT   JSON,
    ASSIGNED_AGENT_ID VARCHAR2(64),
    STATUS        VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    STARTED_AT    TIMESTAMP,
    COMPLETED_AT  TIMESTAMP,
    LOOP_ID       VARCHAR2(64),
    STEP_COMPLETION_TYPE VARCHAR2(20) DEFAULT 'MANUAL',
    CONSTRAINT PK_TASK_STEPS PRIMARY KEY (STEP_ID, PLAN_ID),
    CONSTRAINT CK_TS_STATUS CHECK (STATUS IN ('PENDING','RUNNING','BLOCKED','SUCCESS','FAILED','SKIPPED','WAITING_LOOP')),
    CONSTRAINT CK_TS_COMPLETION CHECK (STEP_COMPLETION_TYPE IN ('MANUAL','LOOP','SPEC'))
) ENABLE ROW MOVEMENT;

ALTER TABLE TASK_STEPS ADD CONSTRAINT UK_TASK_STEPS_ID UNIQUE (STEP_ID);
ALTER TABLE TASK_STEPS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 19. TASK_CONTEXT_SNAPSHOTS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_CONTEXT_SNAPSHOTS (
    SNAPSHOT_ID   VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID       VARCHAR2(64)  NOT NULL,
    SNAPSHOT_TYPE VARCHAR2(64)  NOT NULL,
    CONTEXT_DATA  JSON,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT ============================================================
PROMPT 20. TASK_TOOL_CALLS (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_TOOL_CALLS (
    CALL_ID      VARCHAR2(64)  PRIMARY KEY,
    PLAN_ID      VARCHAR2(64)  NOT NULL,
    STEP_ID      VARCHAR2(64),
    TOOL_NAME    VARCHAR2(128) NOT NULL,
    TOOL_INPUT   JSON,
    TOOL_OUTPUT  JSON,
    STATUS       VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
    DURATION_MS  NUMBER(10,0),
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_TTC_STATUS CHECK (STATUS IN ('PENDING','RUNNING','SUCCESS','FAILED','TIMEOUT'))
);

PROMPT ============================================================
PROMPT 21. TASK_DEPENDENCIES (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE TASK_DEPENDENCIES (
    DEP_ID          VARCHAR2(64)  PRIMARY KEY,
    SOURCE_PLAN_ID  VARCHAR2(64)  NOT NULL,
    TARGET_PLAN_ID  VARCHAR2(64)  NOT NULL,
    DEP_TYPE        VARCHAR2(64)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_DEP_TYPE CHECK (DEP_TYPE IN ('BLOCKS','DEPENDS_ON','TRIGGERS','RELATES_TO'))
);

PROMPT ============================================================
PROMPT 21a. TASK_LOOP_BINDING (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE TASK_LOOP_BINDING (
    BINDING_ID    VARCHAR2(64)  PRIMARY KEY,
    STEP_ID       VARCHAR2(64)  NOT NULL,
    LOOP_ID       VARCHAR2(64)  NOT NULL,
    BINDING_TYPE  VARCHAR2(20)  DEFAULT 'COMPLETION',
    AUTO_START    VARCHAR2(1)   DEFAULT 'N',
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_TLB_TYPE CHECK (BINDING_TYPE IN ('COMPLETION','VALIDATION')),
    CONSTRAINT CK_TLB_AUTO CHECK (AUTO_START IN ('Y','N'))
);


PROMPT ============================================================
PROMPT 21b. SPEC_PLAN_LINKS (Non-Partitioned) [NEW v2.3.0]
PROMPT ============================================================

CREATE TABLE SPEC_PLAN_LINKS (
    LINK_ID        VARCHAR2(64)  PRIMARY KEY,
    SPEC_ID        VARCHAR2(64)  NOT NULL,
    PLAN_ID        VARCHAR2(64)  NOT NULL,
    LINK_TYPE      VARCHAR2(32)  NOT NULL,
    LINK_STRENGTH  NUMBER(5,4)   DEFAULT 1.0000 NOT NULL,
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SPL_TYPE CHECK (LINK_TYPE IN ('DRIVES','VALIDATES','CONSTRAINS','EXTENDS')),
    CONSTRAINT CK_SPL_STRENGTH CHECK (LINK_STRENGTH BETWEEN 0 AND 1),
    CONSTRAINT UK_SPL_LINK UNIQUE (SPEC_ID, PLAN_ID, LINK_TYPE)
);

PROMPT ============================================================
PROMPT 22. WORKSPACE_TASKS (Non-Partitioned) [NEW v2.2.0]
PROMPT ============================================================

CREATE TABLE WORKSPACE_TASKS (
    WORKSPACE_ID  VARCHAR2(64) NOT NULL,
    PLAN_ID       VARCHAR2(64) NOT NULL,
    ASSIGNED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKSPACE_TASKS PRIMARY KEY (WORKSPACE_ID, PLAN_ID)
);







PROMPT ============================================================
PROMPT 23. SYSTEM_CONFIG (Non-Partitioned)
PROMPT ============================================================

CREATE TABLE SYSTEM_CONFIG (
    CONFIG_KEY   VARCHAR2(128) PRIMARY KEY,
    CONFIG_VALUE VARCHAR2(4000) NOT NULL,
    DESCRIPTION  VARCHAR2(2000),
    UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

PROMPT ============================================================
PROMPT 24. LOOP_META (Reference Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_META (
    ENTITY_ID           VARCHAR2(64)  NOT NULL,
    ENTITY_TYPE         VARCHAR2(32)  DEFAULT 'LOOP_DEFINITION' NOT NULL,
    LOOP_VERSION        VARCHAR2(32)  DEFAULT '1.0' NOT NULL,
    GOAL_DEFINITION     JSON          NOT NULL,
    STOP_CONDITIONS     JSON          NOT NULL,
    EVALUATION_CONFIG   JSON          NOT NULL,
    TRIGGER_CONFIG      JSON,
    HARNESS_TEMPLATE_ID VARCHAR2(64),
    WORKSPACE_ID        VARCHAR2(64),
    BRANCH_ID           VARCHAR2(64),
    SPEC_ID             VARCHAR2(64),
    PARENT_LOOP_ID      VARCHAR2(64),
    COLLAB_GROUP_ID     VARCHAR2(64),
    CONSTRAINT PK_LOOP_META PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
    CONSTRAINT CK_LM_ENTITY_TYPE CHECK (ENTITY_TYPE = 'LOOP_DEFINITION')
);

PROMPT ============================================================
PROMPT 25. LOOP_RUNS (Partitioned by LIST + RANGE) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_RUNS (
    RUN_ID            VARCHAR2(64)   NOT NULL,
    LOOP_ID           VARCHAR2(64)   NOT NULL,
    AGENT_ID          VARCHAR2(64)   NOT NULL,
    TRIGGER_TYPE      VARCHAR2(32)   DEFAULT 'MANUAL' NOT NULL,
    TRIGGER_SOURCE    VARCHAR2(256),
    STATUS            VARCHAR2(30)   DEFAULT 'PENDING' NOT NULL,
    ITERATION_COUNT   NUMBER(5,0)    DEFAULT 0 NOT NULL,
    TOTAL_TOKENS      NUMBER(12,0)   DEFAULT 0 NOT NULL,
    FINAL_RESULT      VARCHAR2(4000),
    ERROR_MESSAGE     VARCHAR2(2000),
    STARTED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT      TIMESTAMP,
    PARENT_RUN_ID     VARCHAR2(64),
    CONSTRAINT PK_LOOP_RUNS PRIMARY KEY (RUN_ID, STATUS),
    CONSTRAINT UK_LOOP_RUNS_ID UNIQUE (RUN_ID),
    CONSTRAINT CK_LR_STATUS CHECK (STATUS IN ('PENDING','RUNNING','PAUSED','COMPLETED','STOPPED','FAILED','TIMEOUT')),
    CONSTRAINT CK_LR_TRIGGER CHECK (TRIGGER_TYPE IN ('MANUAL','SCHEDULE','EVENT','HOOK'))
);

ALTER TABLE LOOP_RUNS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 26. LOOP_ITERATIONS (Reference Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_ITERATIONS (
    ITERATION_ID      VARCHAR2(64)   NOT NULL,
    RUN_ID            VARCHAR2(64)   NOT NULL,
    ITERATION_ORDER   NUMBER(5,0)    NOT NULL,
    PLAN_DATA         JSON,
    ACTIONS           JSON,
    OBSERVATIONS      JSON,
    EVALUATION_RESULT JSON,
    EVALUATION_PASSED VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    ADJUSTMENT        JSON,
    TOKEN_USAGE       NUMBER(12,0)   DEFAULT 0 NOT NULL,
    STARTED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT      TIMESTAMP,
    CONSTRAINT PK_LOOP_ITERATIONS PRIMARY KEY (ITERATION_ID, RUN_ID),
    CONSTRAINT CK_LI_PASSED CHECK (EVALUATION_PASSED IN ('Y','N'))
);

ALTER TABLE LOOP_ITERATIONS ADD CONSTRAINT UK_LOOP_ITER_ID UNIQUE (ITERATION_ID);
ALTER TABLE LOOP_ITERATIONS ENABLE ROW MOVEMENT;

PROMPT ============================================================
PROMPT 27. LOOP_HOOKS (Non-Partitioned) [NEW v3.7.5]
PROMPT ============================================================

CREATE TABLE LOOP_HOOKS (
    HOOK_ID       VARCHAR2(64)  PRIMARY KEY,
    LOOP_ID       VARCHAR2(64)  NOT NULL,
    HOOK_EVENT    VARCHAR2(32)  NOT NULL,
    HOOK_TYPE     VARCHAR2(32)  NOT NULL,
    HOOK_CONFIG   JSON,
    PRIORITY      NUMBER(3,0)   DEFAULT 5 NOT NULL,
    ENABLED       VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_LH_EVENT CHECK (HOOK_EVENT IN ('PRE_RUN','POST_ITERATION','ON_STOP','ON_FAIL','ON_TIMEOUT','ON_START')),
    CONSTRAINT CK_LH_TYPE CHECK (HOOK_TYPE IN ('WEBHOOK','SCRIPT','NOTIFICATION','LOG','MCP_CALL')),
    CONSTRAINT CK_LH_ENABLED CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT CK_LH_PRIORITY CHECK (PRIORITY BETWEEN 1 AND 10)
);


PROMPT ============================================================
PROMPT Local Indexes on ENTITIES
PROMPT ============================================================

CREATE INDEX IDX_ENTITIES_CATEGORY ON ENTITIES(CATEGORY) ;
CREATE INDEX IDX_ENTITIES_STATUS ON ENTITIES(STATUS) ;
CREATE INDEX IDX_ENTITIES_OWNED_BY ON ENTITIES(OWNED_BY_AGENT) ;
CREATE INDEX IDX_ENTITIES_VISIBILITY ON ENTITIES(VISIBILITY) ;
CREATE INDEX IDX_ENTITIES_WORKSPACE ON ENTITIES(WORKSPACE_ID) ;

PROMPT ============================================================
PROMPT Local Indexes on ENTITY_EDGES
PROMPT ============================================================

CREATE INDEX IDX_EDGES_TARGET ON ENTITY_EDGES(TARGET_ID) ;
CREATE INDEX IDX_EDGES_TYPE ON ENTITY_EDGES(EDGE_TYPE) ;
CREATE INDEX IDX_EDGES_TARGET_TYPE ON ENTITY_EDGES(TARGET_ID, EDGE_TYPE) ;

PROMPT ============================================================
PROMPT Other Indexes
PROMPT ============================================================

CREATE INDEX IDX_KM_DOMAIN ON KNOWLEDGE_META(DOMAIN) ;
CREATE INDEX IDX_KM_TOPIC ON KNOWLEDGE_META(TOPIC) ;
CREATE INDEX IDX_KM_NEXT_REVIEW ON KNOWLEDGE_META(NEXT_REVIEW) ;

CREATE INDEX IDX_EE_MODEL ON ENTITY_EMBEDDINGS(EMBEDDING_MODEL) ;

CREATE INDEX IDX_ET_TAG ON ENTITY_TAGS(TAG_ID) ;

CREATE INDEX IDX_AR_STATUS ON AGENT_REGISTRY(STATUS);
CREATE INDEX IDX_AR_TYPE ON AGENT_REGISTRY(AGENT_TYPE);

CREATE INDEX IDX_AS_AGENT ON AGENT_SESSION(AGENT_ID) ;

CREATE INDEX IDX_EAL_ENTITY ON ENTITY_ACCESS_LOG(ENTITY_ID) ;
CREATE INDEX IDX_EAL_TIME ON ENTITY_ACCESS_LOG(ACCESS_TIME) ;

CREATE INDEX IDX_APL_AGENT ON AGENT_PERMISSION_LOG(AGENT_ID);

CREATE INDEX IDX_COL_SOURCE ON AGENT_COLLABORATION(SOURCE_AGENT_ID);
CREATE INDEX IDX_COL_TARGET ON AGENT_COLLABORATION(TARGET_AGENT_ID);

CREATE INDEX IDX_TP_AGENT ON TASK_PLANS(AGENT_ID) ;
CREATE INDEX IDX_TP_BRANCH ON TASK_PLANS(BRANCH_ID);
CREATE INDEX IDX_TS_PLAN ON TASK_STEPS(PLAN_ID) ;
CREATE INDEX IDX_TS_ASSIGNED_AGENT ON TASK_STEPS(ASSIGNED_AGENT_ID);

CREATE INDEX IDX_TCS_PLAN ON TASK_CONTEXT_SNAPSHOTS(PLAN_ID);
CREATE INDEX IDX_TTC_PLAN ON TASK_TOOL_CALLS(PLAN_ID);
CREATE INDEX IDX_TTC_STEP ON TASK_TOOL_CALLS(STEP_ID);

CREATE INDEX IDX_TD_SOURCE ON TASK_DEPENDENCIES(SOURCE_PLAN_ID);
CREATE INDEX IDX_TD_TARGET ON TASK_DEPENDENCIES(TARGET_PLAN_ID);

ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID);

ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES WORKSPACES(WORKSPACE_ID) ON DELETE CASCADE;
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_FORK_CTX FOREIGN KEY (FORK_CONTEXT_ID) REFERENCES WORKSPACE_CONTEXT(CONTEXT_ID) ON DELETE SET NULL;
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);
ALTER TABLE CONTEXT_BRANCHES ADD CONSTRAINT FK_CB_SRC_AGENT FOREIGN KEY (SOURCE_AGENT_ID) REFERENCES AGENT_REGISTRY(AGENT_ID);

CREATE INDEX IDX_WS_OWNER ON WORKSPACES(OWNER_USER_ID);
CREATE INDEX IDX_WS_STATUS ON WORKSPACES(STATUS);
CREATE INDEX IDX_WS_ALIAS ON WORKSPACES(WORKSPACE_ALIAS);

CREATE INDEX IDX_WC_WORKSPACE ON WORKSPACE_CONTEXT(WORKSPACE_ID);
CREATE INDEX IDX_WC_AGENT ON WORKSPACE_CONTEXT(AGENT_ID);
CREATE INDEX IDX_WC_TYPE ON WORKSPACE_CONTEXT(CONTEXT_TYPE);
CREATE INDEX IDX_WC_VISIBILITY ON WORKSPACE_CONTEXT(VISIBILITY);

CREATE INDEX IDX_AS_WORKSPACE ON AGENT_SESSION(WORKSPACE_ID) ;
CREATE INDEX IDX_AS_PREDECESSOR ON AGENT_SESSION(PREDECESSOR_SESSION_ID) ;
CREATE INDEX IDX_AS_OWNER ON AGENT_SESSION(OWNER_USER_ID) ;


CREATE INDEX IDX_SM_SCOPE ON SPEC_META(SPEC_SCOPE) ;
CREATE INDEX IDX_SM_STATUS ON SPEC_META(SPEC_STATUS) ;
CREATE INDEX IDX_SM_PARENT ON SPEC_META(PARENT_SPEC_ID) ;
CREATE INDEX IDX_SM_BRANCH ON SPEC_META(BRANCH_ID);

CREATE INDEX IDX_SPL_SPEC ON SPEC_PLAN_LINKS(SPEC_ID);
CREATE INDEX IDX_SPL_PLAN ON SPEC_PLAN_LINKS(PLAN_ID);

CREATE INDEX IDX_AC_AGENT ON AGENT_CREDENTIALS(AGENT_ID);
CREATE INDEX IDX_AC_USER ON AGENT_CREDENTIALS(USER_ID);
CREATE INDEX IDX_AC_ACTIVE ON AGENT_CREDENTIALS(IS_ACTIVE);

CREATE INDEX IDX_CG_WORKSPACE ON COLLAB_GROUPS(WORKSPACE_ID);
CREATE INDEX IDX_CG_STATUS ON COLLAB_GROUPS(STATUS);
CREATE INDEX IDX_CG_TYPE ON COLLAB_GROUPS(GROUP_TYPE);

CREATE INDEX IDX_CGM_GROUP ON COLLAB_GROUP_MEMBERS(GROUP_ID);
CREATE INDEX IDX_CGM_AGENT ON COLLAB_GROUP_MEMBERS(AGENT_ID);

CREATE INDEX IDX_AR_ROLE ON AGENT_REGISTRY(AGENT_ROLE);
CREATE INDEX IDX_AR_USER ON AGENT_REGISTRY(CURRENT_USER_ID);
CREATE INDEX IDX_AR_CREATED_BY ON AGENT_REGISTRY(CREATED_BY_AGENT_ID);








CREATE INDEX IDX_SKM_NAME ON SKILL_META(SKILL_NAME) ;
CREATE INDEX IDX_SKM_TYPE ON SKILL_META(SKILL_TYPE) ;
CREATE INDEX IDX_SKM_STATUS ON SKILL_META(SKILL_STATUS) ;
CREATE INDEX IDX_SKM_RUNTIME ON SKILL_META(RUNTIME) ;

















CREATE INDEX IDX_CB_WORKSPACE ON CONTEXT_BRANCHES(WORKSPACE_ID);
CREATE INDEX IDX_CB_PARENT ON CONTEXT_BRANCHES(PARENT_BRANCH_ID);
CREATE INDEX IDX_CB_FORK_CTX ON CONTEXT_BRANCHES(FORK_CONTEXT_ID);
CREATE INDEX IDX_CB_AGENT ON CONTEXT_BRANCHES(AGENT_ID);
CREATE INDEX IDX_CB_STATUS ON CONTEXT_BRANCHES(BRANCH_STATUS);
CREATE INDEX IDX_CB_TYPE ON CONTEXT_BRANCHES(BRANCH_TYPE);

CREATE INDEX IDX_WC_BRANCH ON WORKSPACE_CONTEXT(BRANCH_ID);

CREATE INDEX IDX_BML_SRC ON BRANCH_MERGE_LOG(SOURCE_BRANCH_ID);
CREATE INDEX IDX_BML_TGT ON BRANCH_MERGE_LOG(TARGET_BRANCH_ID);
CREATE INDEX IDX_BML_RESULT ON BRANCH_MERGE_LOG(MERGE_RESULT);

CREATE INDEX IDX_LR_LOOP ON LOOP_RUNS(LOOP_ID) ;
CREATE INDEX IDX_LR_AGENT ON LOOP_RUNS(AGENT_ID) ;
CREATE INDEX IDX_LR_STATUS ON LOOP_RUNS(STATUS) ;

CREATE INDEX IDX_LI_RUN ON LOOP_ITERATIONS(RUN_ID) ;
CREATE INDEX IDX_LI_ORDER ON LOOP_ITERATIONS(ITERATION_ORDER) ;

CREATE INDEX IDX_LH_LOOP ON LOOP_HOOKS(LOOP_ID);
CREATE INDEX IDX_LH_EVENT ON LOOP_HOOKS(HOOK_EVENT);
CREATE INDEX IDX_LH_ENABLED ON LOOP_HOOKS(ENABLED);

PROMPT ============================================================
PROMPT Property Graph: YASHAN_MEMORY_GRAPH
PROMPT ============================================================

CREATE PROPERTY GRAPH YASHAN_MEMORY_GRAPH
  VERTEX TABLES (
    ENTITIES KEY (ENTITY_ID, ENTITY_TYPE) LABEL entity
      PROPERTIES (ENTITY_ID, ENTITY_TYPE, TITLE, CATEGORY, STATUS)
  )
  EDGE TABLES (
    ENTITY_EDGES KEY (EDGE_ID)
      SOURCE KEY (SOURCE_ID) REFERENCES ENTITIES (ENTITY_ID)
      DESTINATION KEY (TARGET_ID) REFERENCES ENTITIES (ENTITY_ID)
      LABEL edge PROPERTIES (EDGE_TYPE, STRENGTH)
  )
/

-- CTX_DDL not needed for YashanDB (uses SEARCH INDEX)

CREATE SEARCH INDEX ENTITIES_SEARCH_CTX ON ENTITIES(TITLE);

PROMPT ============================================================
PROMPT Drop helper procedures
PROMPT ============================================================

DROP PROCEDURE IF EXISTS safe_ddl;
DROP PROCEDURE IF EXISTS safe_idx;

PROMPT ============================================================
PROMPT AI Agent Infra v3.10.2 - Community Edition Schema Deployment Complete
PROMPT ============================================================

-- Grant DBMS_CRYPTO for DB_CRYPTO package
-- GRANT EXECUTE ON SYS.DBMS_CRYPTO TO AIADMIN;
