-- v4.3.1 one account, one Human Principal, one organization person.

DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CX_PRINCIPALS' AND COLUMN_NAME = 'ORGANIZATION_REQUIRED';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_PRINCIPALS ADD (ORGANIZATION_REQUIRED CHAR(1) DEFAULT ''Y'' NOT NULL)';
    END IF;
    SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'CX_PRINCIPALS' AND CONSTRAINT_NAME = 'CK_CX_PRINCIPAL_ORG_REQ';
    IF l_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CX_PRINCIPALS ADD CONSTRAINT CK_CX_PRINCIPAL_ORG_REQ CHECK (ORGANIZATION_REQUIRED IN (''Y'',''N''))';
    END IF;
END;
/

UPDATE CX_PRINCIPALS p SET ORGANIZATION_REQUIRED = 'N'
 WHERE EXISTS (
       SELECT 1 FROM CX_HUMAN_IDENTITIES i JOIN CX_USER_ROLES r ON r.PRINCIPAL_ID = i.PRINCIPAL_ID
        WHERE i.PRINCIPAL_ID = p.PRINCIPAL_ID AND i.IDENTITY_TYPE = 'LOCAL'
          AND i.SUBJECT_KEY = 'admin' AND i.STATUS = 'ACTIVE'
          AND r.ROLE_CODE = 'SYSTEM_ADMIN' AND r.STATUS = 'ACTIVE' AND r.SOURCE = 'BOOTSTRAP_ADMIN'
 );

UPDATE CX_ORGANIZATION_MEMBERS m
   SET STATUS = 'ENDED', VALID_UNTIL = SYSTIMESTAMP, UPDATED_AT = SYSTIMESTAMP
 WHERE m.STATUS = 'ACTIVE' AND EXISTS (
       SELECT 1 FROM CX_PRINCIPALS p
        WHERE p.PRINCIPAL_ID = m.PRINCIPAL_ID AND p.ORGANIZATION_REQUIRED = 'N'
 );

UPDATE CX_ORGANIZATIONS o SET RESPONSIBLE_PRINCIPAL_ID = NULL, UPDATED_AT = SYSTIMESTAMP
 WHERE EXISTS (
       SELECT 1 FROM CX_PRINCIPALS p
        WHERE p.PRINCIPAL_ID = o.RESPONSIBLE_PRINCIPAL_ID AND p.ORGANIZATION_REQUIRED = 'N'
 );

CREATE OR REPLACE TRIGGER TRG_CX_ORG_MEMBER_ACCOUNT
BEFORE INSERT OR UPDATE OF PRINCIPAL_ID, STATUS ON CX_ORGANIZATION_MEMBERS
FOR EACH ROW
WHEN (NEW.STATUS = 'ACTIVE')
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_count FROM CX_PRINCIPALS p
     WHERE p.PRINCIPAL_ID = :NEW.PRINCIPAL_ID AND p.PRINCIPAL_TYPE = 'HUMAN'
       AND p.STATUS = 'ACTIVE' AND p.ORGANIZATION_REQUIRED = 'Y'
       AND EXISTS (SELECT 1 FROM CX_HUMAN_IDENTITIES i
                    WHERE i.PRINCIPAL_ID = p.PRINCIPAL_ID AND i.STATUS = 'ACTIVE');
    IF l_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20041, 'organization person requires one active platform account');
    END IF;
END;
/
