-- v4.3.2: bind a Runtime Memory Snapshot to the live authorization subject.
DECLARE
  PROCEDURE add_column(p_name VARCHAR2, p_type VARCHAR2) IS BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE CX_MEMORY_SNAPSHOTS ADD (' || p_name || ' ' || p_type || ')';
  EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
BEGIN
  add_column('PRINCIPAL_ID', 'VARCHAR2(128)');
  add_column('PRINCIPAL_PERMISSION_VERSION', 'NUMBER(19,0)');
  add_column('AGENT_INSTANCE_ID', 'VARCHAR2(128)');
  add_column('AGENT_FENCING_TOKEN', 'NUMBER(19,0)');
END;
/
CREATE INDEX IDX_CX_MEM_SNAP_SUBJECT ON CX_MEMORY_SNAPSHOTS(PRINCIPAL_ID, AGENT_INSTANCE_ID, STATE);
