-- v4.3.2 completion: additive governed evidence and worker-result facts.
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MEMORY_VERSION_ARTIFACTS (LINK_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL, ARTIFACT_ID VARCHAR2(128) NOT NULL, RELATION_TYPE VARCHAR2(32) DEFAULT ''SOURCE'' NOT NULL, CREATED_BY VARCHAR2(128), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT CX_MEM_VER_ART_UK UNIQUE(VERSION_ID,ARTIFACT_ID,RELATION_TYPE))'; EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955,4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MEMORY_INGESTION_FINDINGS (FINDING_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL, FINDING_TYPE VARCHAR2(48) NOT NULL, SEVERITY VARCHAR2(16) DEFAULT ''LOW'' NOT NULL, CONTENT_DIGEST VARCHAR2(64) NOT NULL, EVIDENCE_JSON CLOB DEFAULT ''{}'' NOT NULL, STATUS VARCHAR2(24) DEFAULT ''OPEN'' NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT CX_MEM_FINDING_UK UNIQUE(VERSION_ID,FINDING_TYPE,CONTENT_DIGEST))'; EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955,4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CX_MEMORY_WORKER_RESULTS (RESULT_ID VARCHAR2(128) PRIMARY KEY, JOB_ITEM_ID VARCHAR2(128) NOT NULL, WORKER_ID VARCHAR2(256) NOT NULL, FENCING_TOKEN NUMBER(19,0) NOT NULL, INPUT_DIGEST VARCHAR2(64) NOT NULL, OUTPUT_DIGEST VARCHAR2(64) NOT NULL, SCHEMA_VERSION VARCHAR2(64) NOT NULL, RESULT_JSON CLOB NOT NULL, VALIDATION_STATE VARCHAR2(24) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT CX_MEM_WORKER_RESULT_UK UNIQUE(JOB_ITEM_ID,FENCING_TOKEN,OUTPUT_DIGEST))'; EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955,4207) THEN RAISE; END IF; END;
/
DECLARE PROCEDURE add_column(n VARCHAR2,t VARCHAR2) IS BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_MEMORY_REPRESENTATIONS ADD ('||n||' '||t||')'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1430 THEN RAISE; END IF; END; BEGIN
  add_column('PURPOSE_SCOPE','VARCHAR2(128) DEFAULT ''RUNTIME_CONTEXT'' NOT NULL'); add_column('ARCHIVED_AT','TIMESTAMP');
  EXECUTE IMMEDIATE 'ALTER TABLE CX_MEMORY_VERSIONS ADD (EXPIRY_REVIEW_AT TIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1430 THEN RAISE; END IF; END;
/
DECLARE BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CX_MEMORY_VERSIONS ADD (SECURITY_STATE VARCHAR2(24) DEFAULT ''CLEAR'' NOT NULL)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_MEM_FINDING_VERSION ON CX_MEMORY_INGESTION_FINDINGS(VERSION_ID,STATUS,SEVERITY)'; EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955,4207) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_MEM_ARTIFACT_VERSION ON CX_MEMORY_VERSION_ARTIFACTS(VERSION_ID,ARTIFACT_ID)'; EXCEPTION WHEN OTHERS THEN IF ABS(SQLCODE) NOT IN (955,4207) THEN RAISE; END IF; END;
/
