-- v4.4.1 additive approval evidence for the controlled-upgrade protocol.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
BEGIN
  ddl('CREATE TABLE CX_UPGRADE_APPROVALS (APPROVAL_ID VARCHAR2(128) PRIMARY KEY,UPGRADE_ID VARCHAR2(128) NOT NULL,APPROVAL_KIND VARCHAR2(32) NOT NULL,PRINCIPAL_ID VARCHAR2(128) NOT NULL,DECISION VARCHAR2(32) NOT NULL,TERM NUMBER(19,0),FENCING_TOKEN NUMBER(19,0),REASON VARCHAR2(2000) NOT NULL,CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,CONSTRAINT UK_UPGRADE_APPROVAL UNIQUE(UPGRADE_ID,APPROVAL_KIND,PRINCIPAL_ID))');
  ddl('CREATE INDEX IDX_UPGRADE_APPROVAL_PLAN ON CX_UPGRADE_APPROVALS(UPGRADE_ID,APPROVAL_KIND,DECISION)');
END;
/
