-- v4.4.2 additive Embedding activation evidence and Graph capability profile.
-- Provider secrets and customer payloads are deliberately absent from this schema.
DECLARE PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
        PROCEDURE add_column(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
          l_count NUMBER;
        BEGIN
          SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
           WHERE TABLE_NAME = UPPER(p_table) AND COLUMN_NAME = UPPER(p_column);
          IF l_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
          END IF;
        END;
BEGIN
  ddl('CREATE TABLE CX_GRAPH_CAPABILITY_PROFILES (PROFILE_KEY VARCHAR2(64) PRIMARY KEY,PROFILE_VERSION VARCHAR2(32) NOT NULL,STATUS VARCHAR2(24) DEFAULT ''ACTIVE'' NOT NULL,REASON VARCHAR2(2000) NOT NULL,CREATED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  ddl('CREATE TABLE CX_GRAPH_CAPABILITY_MATRIX (PROFILE_KEY VARCHAR2(64) NOT NULL,CAPABILITY_KEY VARCHAR2(64) NOT NULL,STATE VARCHAR2(16) NOT NULL CHECK (STATE IN (''ENABLED'',''CONTROLLED'',''DISABLED'',''UNAVAILABLE'')),VERSION NUMBER(19,0) DEFAULT 1 NOT NULL CHECK (VERSION > 0),MANDATORY CHAR(1) DEFAULT ''N'' NOT NULL CHECK (MANDATORY IN (''Y'',''N'')),EVIDENCE_REF VARCHAR2(256),REASON VARCHAR2(2000) NOT NULL,EFFECTIVE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,UPDATED_BY VARCHAR2(128) NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,PRIMARY KEY(PROFILE_KEY,CAPABILITY_KEY))');
  ddl('CREATE TABLE CX_GRAPH_CAPABILITY_HISTORY (HISTORY_ID VARCHAR2(128) PRIMARY KEY,PROFILE_KEY VARCHAR2(64) NOT NULL,CAPABILITY_KEY VARCHAR2(64) NOT NULL,FROM_STATE VARCHAR2(16) NOT NULL,TO_STATE VARCHAR2(16) NOT NULL,EXPECTED_VERSION NUMBER(19,0) NOT NULL,EVIDENCE_REF VARCHAR2(256),REASON VARCHAR2(2000) NOT NULL,CHANGED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  ddl('CREATE TABLE CX_EMBEDDING_ACTIVATION_EVIDENCE (ACTIVATION_ID VARCHAR2(128) PRIMARY KEY,PROFILE_ID VARCHAR2(128) NOT NULL,PROFILE_VERSION NUMBER(19,0) NOT NULL,OBSERVED_DIMENSION NUMBER(19,0) NOT NULL,OBSERVED_MODEL VARCHAR2(256),RESPONSE_DIGEST VARCHAR2(128) NOT NULL,PROBE_STATUS VARCHAR2(32) NOT NULL,ACTIVATION_STATUS VARCHAR2(32) NOT NULL,CONTRACT_ID VARCHAR2(128),SPACE_ID VARCHAR2(128),BINDING_ID VARCHAR2(128),MIGRATION_STATE VARCHAR2(32) DEFAULT ''NONE'' NOT NULL,REASON VARCHAR2(2000) NOT NULL,ACTOR VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  ddl('CREATE TABLE CX_ADMIN_NODE_TARGETS (TARGET_ID VARCHAR2(128) PRIMARY KEY,NODE_ID VARCHAR2(256) NOT NULL,HOST_REFERENCE VARCHAR2(256) NOT NULL,SSH_PORT NUMBER(5,0) DEFAULT 22 NOT NULL,OS_USER VARCHAR2(128) DEFAULT ''root'' NOT NULL,DEPLOYMENT_TARGET VARCHAR2(128) DEFAULT ''LOCAL'' NOT NULL,SSH_TRUST_MODE VARCHAR2(32) NOT NULL,PUBLIC_KEY_DIGEST VARCHAR2(128),FAILURE_DOMAIN VARCHAR2(128),STATUS VARCHAR2(32) DEFAULT ''CANDIDATE'' NOT NULL,REASON VARCHAR2(2000) NOT NULL,CREATED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  add_column('CX_ADMIN_NODE_TARGETS', 'SSH_PORT', 'NUMBER(5,0) DEFAULT 22 NOT NULL');
  add_column('CX_ADMIN_NODE_TARGETS', 'OS_USER', 'VARCHAR2(128) DEFAULT ''root'' NOT NULL');
  add_column('CX_ADMIN_NODE_TARGETS', 'DEPLOYMENT_TARGET', 'VARCHAR2(128) DEFAULT ''LOCAL'' NOT NULL');
  ddl('CREATE TABLE CX_ADMIN_DEPLOYMENT_ATTEMPTS (ATTEMPT_ID VARCHAR2(128) PRIMARY KEY,TARGET_ID VARCHAR2(128) NOT NULL,ATTEMPT_DIGEST VARCHAR2(128) NOT NULL,VERIFICATION_STATE VARCHAR2(32) NOT NULL,RESULT_DIGEST VARCHAR2(128),FAILURE_CODE VARCHAR2(64),REASON VARCHAR2(2000) NOT NULL,CREATED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  ddl('CREATE INDEX IDX_CX_GRAPH_MATRIX_STATE ON CX_GRAPH_CAPABILITY_MATRIX(PROFILE_KEY,STATE)');
  ddl('CREATE INDEX IDX_CX_EMBEDDING_ACTIVATION ON CX_EMBEDDING_ACTIVATION_EVIDENCE(PROFILE_ID,CREATED_AT)');
END;
/
MERGE INTO CX_GRAPH_CAPABILITY_PROFILES d USING (SELECT 'PRODUCTION' PROFILE_KEY FROM DUAL) s ON (d.PROFILE_KEY=s.PROFILE_KEY) WHEN MATCHED THEN UPDATE SET d.PROFILE_VERSION='4.4.2',d.STATUS='ACTIVE' WHEN NOT MATCHED THEN INSERT(PROFILE_KEY,PROFILE_VERSION,STATUS,REASON,CREATED_BY) VALUES('PRODUCTION','4.4.2','ACTIVE','Initial v4.4.2 capability-level production profile','SYSTEM');
DECLARE PROCEDURE seed(k VARCHAR2,s VARCHAR2,m CHAR,r VARCHAR2) IS BEGIN MERGE INTO CX_GRAPH_CAPABILITY_MATRIX d USING (SELECT 'PRODUCTION' PROFILE_KEY,k CAPABILITY_KEY FROM DUAL) x ON (d.PROFILE_KEY=x.PROFILE_KEY AND d.CAPABILITY_KEY=x.CAPABILITY_KEY) WHEN NOT MATCHED THEN INSERT(PROFILE_KEY,CAPABILITY_KEY,STATE,MANDATORY,REASON,UPDATED_BY) VALUES('PRODUCTION',k,s,m,r,'SYSTEM'); END;
BEGIN
  seed('graph_runtime_core','ENABLED','Y','Database-authoritative runtime core'); seed('graph_inspection','ENABLED','N','Authorized graph inspection'); seed('graph_manifest_draft_import','CONTROLLED','N','Signed imports remain Draft'); seed('graph_slo_readonly','CONTROLLED','N','Read-only SLO evidence'); seed('graph_checkpoint_fork','CONTROLLED','N','Protected checkpoint fork'); seed('graph_replay','DISABLED','N','Side effects and compensation evidence incomplete'); seed('a2a_gateway','DISABLED','N','A2A conformance evidence incomplete'); seed('otel_export','DISABLED','N','OTLP delivery evidence incomplete'); seed('graph_dynamic_migration','DISABLED','N','Migration rollback evidence incomplete'); seed('framework_adapter_execution','DISABLED','N','Framework imports remain non-executable');
END;
/
