-- v4.4.4 additive binding of shared storage to managed runtime nodes.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
BEGIN
  ddl('CREATE TABLE CX_MANAGED_NODE_STORAGE_BINDINGS (BINDING_ID VARCHAR2(128) PRIMARY KEY,NODE_ID VARCHAR2(128) NOT NULL,STORAGE_ID VARCHAR2(128) NOT NULL,MOUNT_REFERENCE VARCHAR2(512) NOT NULL,ROLE_SCOPE VARCHAR2(64) NOT NULL,STATUS VARCHAR2(32) NOT NULL,REASON VARCHAR2(2000) NOT NULL,CREATED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UQ_CX_NODE_STORAGE_SCOPE UNIQUE(NODE_ID,STORAGE_ID,ROLE_SCOPE))');
END;
/
