-- v4.4.4 additive separation of Admin Agent and Agent Pool shared storage.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
BEGIN
  ddl('ALTER TABLE CX_SHARED_STORAGE_PROFILES ADD (STORAGE_PURPOSE VARCHAR2(32) DEFAULT ''ADMIN_RUNTIME'' NOT NULL)');
END;
/
