-- v4.4.4 Agent Pool host-node onboarding completion.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE s;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  ddl('CREATE TABLE CX_AGENT_POOL_NODE_ONBOARDINGS (ONBOARDING_ID VARCHAR2(128) PRIMARY KEY,NODE_ID VARCHAR2(128) NOT NULL,INTEGRATION_KIND VARCHAR2(32) NOT NULL,TOKEN_DIGEST VARCHAR2(128) NOT NULL,STATUS VARCHAR2(32) NOT NULL,EXPIRES_AT TIMESTAMP NOT NULL,CHECKED_IN_AT TIMESTAMP,LAST_HEARTBEAT_AT TIMESTAMP,RUNTIME_VERSION VARCHAR2(128),RESULT_JSON CLOB NOT NULL,CREATED_BY VARCHAR2(128) NOT NULL,REASON VARCHAR2(2000) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)');
  ddl('CREATE INDEX IDX_CX_POOL_ONBOARDING_NODE ON CX_AGENT_POOL_NODE_ONBOARDINGS(NODE_ID,STATUS,EXPIRES_AT)');
END;
/
