-- v4.4.4 correction: local Agent files belong to the managed node, not shared storage.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
BEGIN
  ddl('ALTER TABLE CX_MANAGED_NODES ADD (AGENT_INFO_PATH VARCHAR2(512))');
END;
/
UPDATE CX_MANAGED_NODE_STORAGE_BINDINGS
SET STATUS='REMOVED', REASON='Obsolete local-directory profile; local path is now stored on the managed node'
WHERE STORAGE_ID IN (SELECT STORAGE_ID FROM CX_SHARED_STORAGE_PROFILES WHERE STORAGE_PURPOSE IN ('ADMIN_AGENT_RUNTIME','AGENT_POOL_AGENT_RUNTIME'))
  AND STATUS <> 'REMOVED';
UPDATE CX_SHARED_STORAGE_PROFILES
SET STATUS='REMOVED', VALIDATION_STATE='DEPRECATED', REASON='Local directory is now configured on the managed node'
WHERE STORAGE_PURPOSE IN ('ADMIN_AGENT_RUNTIME','AGENT_POOL_AGENT_RUNTIME');
COMMIT;
