PROMPT v4.4.5 immutable Graph Run contract snapshot

DECLARE
  PROCEDURE add_column(sql_text VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE sql_text;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -1430 THEN RAISE; END IF;
  END;
BEGIN
  add_column('ALTER TABLE GRAPH_RUNS ADD (DEFINITION_DIGEST VARCHAR2(128))');
  add_column('ALTER TABLE GRAPH_RUNS ADD (PLAN_DIGEST VARCHAR2(128))');
  add_column('ALTER TABLE GRAPH_RUNS ADD (COMPATIBILITY_LEVEL VARCHAR2(32))');
  add_column('ALTER TABLE GRAPH_RUNS ADD (STATE_SCHEMA_VERSION VARCHAR2(64))');
  add_column('ALTER TABLE GRAPH_RUNS ADD (BUDGET_SCHEMA_VERSION VARCHAR2(64))');
END;
/

UPDATE GRAPH_RUNS r
SET DEFINITION_DIGEST = (SELECT p.DEFINITION_DIGEST FROM GRAPH_COMPILE_PLANS p WHERE p.PLAN_ID = r.PLAN_ID),
    PLAN_DIGEST = (SELECT p.PLAN_DIGEST FROM GRAPH_COMPILE_PLANS p WHERE p.PLAN_ID = r.PLAN_ID),
    COMPATIBILITY_LEVEL = 'COMPATIBLE',
    STATE_SCHEMA_VERSION = (SELECT v.SCHEMA_VERSION FROM GRAPH_VERSIONS v WHERE v.GRAPH_VERSION_ID = r.GRAPH_VERSION_ID),
    BUDGET_SCHEMA_VERSION = 'graph-budget/1'
WHERE EXISTS (
  SELECT 1 FROM GRAPH_COMPILE_PLANS p
  WHERE p.PLAN_ID = r.PLAN_ID
    AND p.GRAPH_VERSION_ID = r.GRAPH_VERSION_ID
    AND p.DEFINITION_DIGEST = (SELECT v.DEFINITION_DIGEST FROM GRAPH_VERSIONS v WHERE v.GRAPH_VERSION_ID = r.GRAPH_VERSION_ID)
);

COMMIT;
