-- v4.4.8 platform command registry, governed autonomy, and private knowledge.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS BEGIN EXECUTE IMMEDIATE s; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
  PROCEDURE add_column(t VARCHAR2, c VARCHAR2, d VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME=t AND COLUMN_NAME=c;
    IF v_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE '||t||' ADD '||c||' '||d; END IF;
  END;
BEGIN
  ddl('CREATE TABLE CX_PLATFORM_COMMANDS (COMMAND_ID VARCHAR2(128) PRIMARY KEY,COMMAND_KEY VARCHAR2(64) NOT NULL,VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,STATUS VARCHAR2(24) DEFAULT ''PUBLISHED'' NOT NULL,RISK_LEVEL VARCHAR2(32) NOT NULL,EXECUTION_MODE VARCHAR2(32) NOT NULL,PARAMETER_SCHEMA CLOB DEFAULT ''{}'' NOT NULL,TARGET_SCHEMA CLOB DEFAULT ''{}'' NOT NULL,EXAMPLE_TEXT VARCHAR2(1000) NOT NULL,LOCALIZED_METADATA CLOB DEFAULT ''{}'' NOT NULL,REQUIRED_ACTION VARCHAR2(128) NOT NULL,CAPABILITY_SCOPE VARCHAR2(128) NOT NULL,RESOURCE_SCOPE CLOB DEFAULT ''{}'' NOT NULL,DOMAIN_POLICY VARCHAR2(32) DEFAULT ''MANAGEMENT_ONLY'' NOT NULL,APPROVAL_POLICY VARCHAR2(64) NOT NULL,EXPIRY_SECONDS NUMBER(10,0) DEFAULT 900 NOT NULL,IDEMPOTENCY_POLICY CLOB DEFAULT ''{}'' NOT NULL,COMPENSATION_CONTRACT CLOB DEFAULT ''{}'' NOT NULL,EVIDENCE_POLICY CLOB DEFAULT ''{}'' NOT NULL,CONTENT_DIGEST VARCHAR2(64) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_PLATFORM_COMMAND UNIQUE(COMMAND_KEY,VERSION),CONSTRAINT CK_CX_CMD_STATUS CHECK(STATUS IN (''DRAFT'',''PUBLISHED'',''DEPRECATED'',''RETIRED'')),CONSTRAINT CK_CX_CMD_RISK CHECK(RISK_LEVEL IN (''READ'',''SAFE_MAINTENANCE'',''PROPOSED_CHANGE'',''HIGH_RISK_CHANGE'',''EMERGENCY_CONTAINMENT'')),CONSTRAINT CK_CX_CMD_EXEC CHECK(EXECUTION_MODE IN (''DIRECT_READ'',''PROPOSAL_ONLY'',''GOVERNED_EXECUTOR'',''UNAVAILABLE'')),CONSTRAINT CK_CX_CMD_DOMAIN CHECK(DOMAIN_POLICY IN (''MANAGEMENT_ONLY'',''CHANNEL_DOMAIN'',''ANY_DOMAIN'')))');
  ddl('CREATE TABLE CX_PLATFORM_COMMAND_EXECUTORS (EXECUTOR_ID VARCHAR2(128) PRIMARY KEY,COMMAND_KEY VARCHAR2(64) NOT NULL,COMMAND_VERSION NUMBER(10,0) NOT NULL,EXECUTOR_KEY VARCHAR2(128) NOT NULL,STATE VARCHAR2(24) DEFAULT ''DISABLED'' NOT NULL,EXPECTED_DIGEST VARCHAR2(64) NOT NULL,RATE_LIMIT_PER_MINUTE NUMBER(10,0) DEFAULT 10 NOT NULL,FAILURE_BUDGET NUMBER(10,0) DEFAULT 1 NOT NULL,REASON VARCHAR2(2000) NOT NULL,UPDATED_BY VARCHAR2(128) NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_PLATFORM_EXECUTOR UNIQUE(COMMAND_KEY,COMMAND_VERSION),CONSTRAINT CK_CX_EXEC_STATE CHECK(STATE IN (''ENABLED'',''DISABLED'',''DEGRADED'',''UNAVAILABLE'')))');
  ddl('CREATE TABLE CX_PLATFORM_MAINTENANCE_TASKS (TASK_ID VARCHAR2(128) PRIMARY KEY,COMMAND_ID VARCHAR2(128) NOT NULL,COMMAND_INSTANCE_ID VARCHAR2(128),TASK_KIND VARCHAR2(64) NOT NULL,STATUS VARCHAR2(32) DEFAULT ''DISCOVERED'' NOT NULL,RISK_LEVEL VARCHAR2(32) NOT NULL,AUTONOMOUS CHAR(1) DEFAULT ''N'' NOT NULL,SCOPE_JSON CLOB DEFAULT ''{}'' NOT NULL,FINDING_JSON CLOB DEFAULT ''{}'' NOT NULL,PLAN_JSON CLOB DEFAULT ''{}'' NOT NULL,POSTFLIGHT_JSON CLOB DEFAULT ''{}'' NOT NULL,EVIDENCE_JSON CLOB DEFAULT ''{}'' NOT NULL,IDEMPOTENCY_KEY VARCHAR2(256),GRAPH_RUN_ID VARCHAR2(128),SECURITY_DOMAIN_ID VARCHAR2(128),CREATED_BY VARCHAR2(128) NOT NULL,LEASE_OWNER VARCHAR2(128),LEASE_EXPIRES_AT TIMESTAMP,FENCING_TOKEN NUMBER(19,0) DEFAULT 1 NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_MAINT_TASK_IDEMP UNIQUE(IDEMPOTENCY_KEY),CONSTRAINT CK_CX_MAINT_STATUS CHECK(STATUS IN (''DISCOVERED'',''ANALYZED'',''PROPOSED'',''AUTHORIZED'',''EXECUTING'',''VERIFYING'',''COMPLETED'',''VERIFY_FAILED'',''COMPENSATED'',''FAILED'',''CANCELLED'',''EXPIRED'')))');
  add_column('CX_PLATFORM_MAINTENANCE_TASKS','GRAPH_RUN_ID','VARCHAR2(128)');
  ddl('CREATE TABLE CX_PLATFORM_MAINTENANCE_ATTEMPTS (ATTEMPT_ID VARCHAR2(128) PRIMARY KEY,TASK_ID VARCHAR2(128) NOT NULL,ATTEMPT_NO NUMBER(10,0) DEFAULT 1 NOT NULL,STATUS VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL,STARTED_AT TIMESTAMP,COMPLETED_AT TIMESTAMP,LEASE_OWNER VARCHAR2(128),FENCING_TOKEN NUMBER(19,0) DEFAULT 1 NOT NULL,OUTPUT_JSON CLOB DEFAULT ''{}'' NOT NULL,FAILURE_REASON VARCHAR2(2000),CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_MAINT_ATTEMPT UNIQUE(TASK_ID,ATTEMPT_NO))');
  ddl('CREATE TABLE CX_PLATFORM_SAFE_AUTONOMY_POLICIES (POLICY_ID VARCHAR2(64) PRIMARY KEY,STATE VARCHAR2(24) DEFAULT ''DISABLED'' NOT NULL,ALLOWED_COMMAND_JSON CLOB DEFAULT ''[]'' NOT NULL,RESOURCE_SCOPE_JSON CLOB DEFAULT ''{}'' NOT NULL,EXECUTION_PRINCIPAL VARCHAR2(128),RATE_LIMIT_PER_MINUTE NUMBER(10,0) DEFAULT 10 NOT NULL,MAX_CONCURRENCY NUMBER(10,0) DEFAULT 1 NOT NULL,FAILURE_BUDGET NUMBER(10,0) DEFAULT 1 NOT NULL,EVIDENCE_RETENTION_DAYS NUMBER(10,0) DEFAULT 365 NOT NULL,VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,REASON VARCHAR2(2000) NOT NULL,UPDATED_BY VARCHAR2(128) NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT CK_CX_AUTONOMY_STATE CHECK(STATE IN (''ENABLED'',''DISABLED'',''PAUSED'')))');
  ddl('CREATE TABLE CX_PLATFORM_KNOWLEDGE (KNOWLEDGE_ID VARCHAR2(128) PRIMARY KEY,KNOWLEDGE_KEY VARCHAR2(128) NOT NULL,VERSION NUMBER(10,0) DEFAULT 1 NOT NULL,KNOWLEDGE_KIND VARCHAR2(64) NOT NULL,AUDIENCE VARCHAR2(64) NOT NULL,SCOPE_TYPE VARCHAR2(32) NOT NULL,SECURITY_DOMAIN_ID VARCHAR2(128),OWNER_PRINCIPAL_ID VARCHAR2(128),CLASSIFICATION VARCHAR2(32) DEFAULT ''RESTRICTED'' NOT NULL,CONTENT_JSON CLOB NOT NULL,CONTENT_DIGEST VARCHAR2(64) NOT NULL,SIGNATURE VARCHAR2(256) NOT NULL,SIGNATURE_STATUS VARCHAR2(32) DEFAULT ''UNVERIFIED'' NOT NULL,STATUS VARCHAR2(24) DEFAULT ''DRAFT'' NOT NULL,VALID_FROM TIMESTAMP,VALID_UNTIL TIMESTAMP,SOURCE_MANIFEST_ID VARCHAR2(128),CREATED_BY VARCHAR2(128) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_PLATFORM_KNOWLEDGE UNIQUE(KNOWLEDGE_KEY,VERSION),CONSTRAINT CK_CX_PK_AUDIENCE CHECK(AUDIENCE IN (''PLATFORM_ADMIN'',''COMPLIANCE_ADMIN'',''MANAGEMENT_AGENTS'',''SECURITY_DOMAIN'',''PRINCIPAL'',''PUBLIC'')),CONSTRAINT CK_CX_PK_SCOPE CHECK(SCOPE_TYPE IN (''PLATFORM_GLOBAL'',''SECURITY_DOMAIN'',''PRINCIPAL'',''MANAGEMENT_AGENT'',''COMPLIANCE_AGENT'',''PUBLIC'')),CONSTRAINT CK_CX_PK_SIGNATURE CHECK(SIGNATURE_STATUS IN (''UNVERIFIED'',''VERIFIED_BUILTIN'',''INVALID'')),CONSTRAINT CK_CX_PK_STATUS CHECK(STATUS IN (''DRAFT'',''PUBLISHED'',''SUPERSEDED'',''REVOKED'')))');
  ddl('CREATE TABLE CX_PLATFORM_KNOWLEDGE_CHUNKS (CHUNK_ID VARCHAR2(128) PRIMARY KEY,KNOWLEDGE_ID VARCHAR2(128) NOT NULL,CHUNK_NO NUMBER(10,0) NOT NULL,CHUNK_TEXT CLOB NOT NULL,CHUNK_DIGEST VARCHAR2(64) NOT NULL,REPRESENTATION_JSON CLOB DEFAULT ''{}'' NOT NULL,AUDIENCE VARCHAR2(64) NOT NULL,SCOPE_TYPE VARCHAR2(32) NOT NULL,SECURITY_DOMAIN_ID VARCHAR2(128),OWNER_PRINCIPAL_ID VARCHAR2(128),CLASSIFICATION VARCHAR2(32) NOT NULL,STATUS VARCHAR2(24) DEFAULT ''ACTIVE'' NOT NULL,CONSTRAINT UK_CX_KNOWLEDGE_CHUNK UNIQUE(KNOWLEDGE_ID,CHUNK_NO))');
  ddl('CREATE TABLE CX_PLATFORM_KNOWLEDGE_GRANTS (GRANT_ID VARCHAR2(128) PRIMARY KEY,KNOWLEDGE_ID VARCHAR2(128) NOT NULL,PRINCIPAL_ID VARCHAR2(128),SECURITY_DOMAIN_ID VARCHAR2(128),GRANT_SCOPE VARCHAR2(32) NOT NULL,STATUS VARCHAR2(24) DEFAULT ''ACTIVE'' NOT NULL,VALID_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,VALID_UNTIL TIMESTAMP,GRANTED_BY VARCHAR2(128) NOT NULL,REASON VARCHAR2(2000) NOT NULL,CONSTRAINT CK_CX_KNOWLEDGE_GRANT_SCOPE CHECK(GRANT_SCOPE IN (''MANAGEMENT_CONTEXT'',''COMPLIANCE_CONTEXT'',''SECURITY_DOMAIN'',''PRINCIPAL'')))');
  ddl('CREATE TABLE CX_DATABASE_ISOLATION_INVENTORY (INVENTORY_ID VARCHAR2(128) PRIMARY KEY,OBJECT_TYPE VARCHAR2(128) NOT NULL,OBJECT_NAME VARCHAR2(128) NOT NULL,SCOPE_KEYS_JSON CLOB DEFAULT ''[]'' NOT NULL,HUMAN_PATH VARCHAR2(512),AGENT_PATH VARCHAR2(512),SHARING_MODEL VARCHAR2(64) NOT NULL,DERIVED_INHERITANCE VARCHAR2(256) NOT NULL,MOVE_POLICY VARCHAR2(64) NOT NULL,ORACLE_ENFORCEMENT VARCHAR2(256) NOT NULL,PG_ENFORCEMENT VARCHAR2(256) NOT NULL,YASHAN_ENFORCEMENT VARCHAR2(256) NOT NULL,VERIFICATION_REF VARCHAR2(256),STATUS VARCHAR2(24) DEFAULT ''PENDING'' NOT NULL,VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,REASON VARCHAR2(2000) NOT NULL,UPDATED_BY VARCHAR2(128) NOT NULL,UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT UK_CX_ISOLATION_INVENTORY UNIQUE(OBJECT_TYPE,OBJECT_NAME),CONSTRAINT CK_CX_ISOLATION_STATUS CHECK(STATUS IN (''PENDING'',''IMPLEMENTED'',''EXCEPTION_APPROVED'',''UNAVAILABLE'')))');
  ddl('CREATE INDEX IDX_CX_PLATFORM_COMMAND_KEY ON CX_PLATFORM_COMMANDS(COMMAND_KEY,STATUS,VERSION DESC)');
  ddl('CREATE INDEX IDX_CX_MAINTENANCE_STATUS ON CX_PLATFORM_MAINTENANCE_TASKS(STATUS,LEASE_EXPIRES_AT,CREATED_AT)');
  ddl('CREATE INDEX IDX_CX_PLATFORM_KNOWLEDGE_SCOPE ON CX_PLATFORM_KNOWLEDGE(AUDIENCE,SCOPE_TYPE,STATUS,VALID_UNTIL)');
  ddl('CREATE INDEX IDX_CX_KNOWLEDGE_CHUNK_SCOPE ON CX_PLATFORM_KNOWLEDGE_CHUNKS(AUDIENCE,SCOPE_TYPE,STATUS)');
END;
/
MERGE INTO CX_PLATFORM_SAFE_AUTONOMY_POLICIES d USING (SELECT 'DEFAULT' POLICY_ID FROM DUAL) s ON (d.POLICY_ID=s.POLICY_ID)
WHEN NOT MATCHED THEN INSERT(POLICY_ID,STATE,REASON,UPDATED_BY) VALUES('DEFAULT','DISABLED','v4.4.8 safe autonomy is disabled by default','SYSTEM_BOOTSTRAP');
-- YashanDB does not implement Oracle Data Grants. Fail closed by revoking the
-- broad business-Agent role from these human/built-in management tables.
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_KNOWLEDGE FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_KNOWLEDGE_CHUNKS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_KNOWLEDGE_GRANTS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_COMMANDS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_COMMAND_EXECUTORS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_MAINTENANCE_TASKS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_MAINTENANCE_ATTEMPTS FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_PLATFORM_SAFE_AUTONOMY_POLICIES FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON AIADMIN.CX_DATABASE_ISOLATION_INVENTORY FROM DEEP_SEC_SESSION_ROLE';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
-- Legacy collaboration groups are history, not authorization boundaries.
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT ON AIADMIN.COLLAB_GROUPS FROM AGENT_API';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
DECLARE
  not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
  missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
BEGIN
  EXECUTE IMMEDIATE 'REVOKE SELECT ON AIADMIN.COLLAB_GROUP_MEMBERS FROM AGENT_API';
EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
END;
/
