-- ============================================================
-- 4_grants.sql — Restricted Database User & Access Control
-- AI Agent Infra with YashanDB v3.8.0
-- ============================================================
-- 
-- This script creates a restricted database user (AGENT_API) that
-- Agents should use for runtime connections instead of the schema
-- owner (AIADMIN). The restricted user:
--   - Can EXECUTE PL/SQL API packages (AUTHID DEFINER)
--   - Can SELECT on tables (read-only access)
--   - CANNOT INSERT/UPDATE/DELETE directly on tables
--   - CANNOT CREATE/ALTER/DROP tables, views, or procedures
--   - CANNOT perform DDL of any kind
--
-- Prerequisites:
--   - Run as SYSDBA: yasql sys/password@//host:port/service as sysdba @4_grants.sql
--   - Schema owner (AIADMIN) must already exist with all objects deployed
--
-- ============================================================

-- ============================================================
-- Schema owner configuration (adjust if not using default AIADMIN)
-- ============================================================
DEFINE SCHEMA_OWNER = 'AIADMIN'
DEFINE AGENT_USER = 'AGENT_API'

PROMPT ============================================================
PROMPT Creating restricted database user: AGENT_API
PROMPT ============================================================

-- Create user using the schema owner's default tablespace (auto-detected)
DECLARE
    v_ts VARCHAR2(128);
BEGIN
    SELECT DEFAULT_TABLESPACE INTO v_ts
    FROM DBA_USERS WHERE USERNAME = UPPER('&&SCHEMA_OWNER');
    EXECUTE IMMEDIATE 'CREATE USER AGENT_API IDENTIFIED BY "agent_api_2026" DEFAULT TABLESPACE ' || v_ts || ' QUOTA 0 ON ' || v_ts;
EXCEPTION
    WHEN OTHERS THEN
        EXECUTE IMMEDIATE 'ALTER USER AGENT_API IDENTIFIED BY "agent_api_2026"';
END;
/
GRANT CREATE SESSION TO AGENT_API;

PROMPT ============================================================
PROMPT Granting EXECUTE on PL/SQL API packages
PROMPT ============================================================
-- These packages use AUTHID DEFINER (default), so they execute
-- with AIADMIN privileges while enforcing business logic.

GRANT EXECUTE ON &&SCHEMA_OWNER..MEMORY_FUSION_ENGINE TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..KNOWLEDGE_BASE_API TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..AGENT_PERMISSION_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SESSION_CLEANUP TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..WORKSPACE_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SPEC_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..COLLAB_GROUP_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..EMBEDDING_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..LDAP_AUTH_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SKILL_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..CONTEXT_AUDIT_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..DB_CRYPTO TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..BRANCH_MANAGER TO AGENT_API;

PROMPT ============================================================
PROMPT Granting SELECT on tables (read-only access)
PROMPT ============================================================
-- Agents can query data directly but cannot modify it.
-- All modifications must go through PL/SQL packages.

GRANT SELECT ON &&SCHEMA_OWNER..ENTITIES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_EDGES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..KNOWLEDGE_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_EMBEDDINGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..HARNESS_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_BRANCHES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SPEC_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SKILL_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TAGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_TAGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SYSTEM_USERS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_REGISTRY TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_CREDENTIALS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACE_CONTEXT TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..BRANCH_MERGE_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_SESSION TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_ACCESS_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_PERMISSION_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_COLLABORATION TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_GROUPS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_GROUP_MEMBERS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_PLANS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_STEPS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_CONTEXT_SNAPSHOTS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_TOOL_CALLS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_DEPENDENCIES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SPEC_PLAN_LINKS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACE_TASKS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..LDAP_CONFIG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..LDAP_SYNC_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SKILL_ACCESS_TOKEN TO AGENT_API;
-- SYSTEM_CONFIG: NOT granted — protected by Deep Sec Data Grant (admin_data_role only)
-- Agents must access config through PL/SQL packages (DB_CRYPTO)
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_AUDIT_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_AUDIT_RULES TO AGENT_API;

PROMPT ============================================================
PROMPT Granting SELECT on views
PROMPT ============================================================

GRANT SELECT ON &&SCHEMA_OWNER..BRANCH_COMPARISON TO AGENT_API;

PROMPT ============================================================
PROMPT Creating synonyms for convenience
PROMPT ============================================================
-- Allows AGENT_API to reference objects without &&SCHEMA_OWNER.. prefix

CREATE SYNONYM AGENT_API.MEMORY_FUSION_ENGINE FOR &&SCHEMA_OWNER..MEMORY_FUSION_ENGINE;
CREATE SYNONYM AGENT_API.KNOWLEDGE_BASE_API FOR &&SCHEMA_OWNER..KNOWLEDGE_BASE_API;
CREATE SYNONYM AGENT_API.AGENT_PERMISSION_MANAGER FOR &&SCHEMA_OWNER..AGENT_PERMISSION_MANAGER;
CREATE SYNONYM AGENT_API.SESSION_CLEANUP FOR &&SCHEMA_OWNER..SESSION_CLEANUP;
CREATE SYNONYM AGENT_API.WORKSPACE_MANAGER FOR &&SCHEMA_OWNER..WORKSPACE_MANAGER;
CREATE SYNONYM AGENT_API.SPEC_MANAGER FOR &&SCHEMA_OWNER..SPEC_MANAGER;
CREATE SYNONYM AGENT_API.COLLAB_GROUP_MANAGER FOR &&SCHEMA_OWNER..COLLAB_GROUP_MANAGER;
CREATE SYNONYM AGENT_API.EMBEDDING_MANAGER FOR &&SCHEMA_OWNER..EMBEDDING_MANAGER;
CREATE SYNONYM AGENT_API.LDAP_AUTH_MANAGER FOR &&SCHEMA_OWNER..LDAP_AUTH_MANAGER;
CREATE SYNONYM AGENT_API.SKILL_MANAGER FOR &&SCHEMA_OWNER..SKILL_MANAGER;
CREATE SYNONYM AGENT_API.CONTEXT_AUDIT_MANAGER FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_MANAGER;
CREATE SYNONYM AGENT_API.DB_CRYPTO FOR &&SCHEMA_OWNER..DB_CRYPTO;
CREATE SYNONYM AGENT_API.BRANCH_MANAGER FOR &&SCHEMA_OWNER..BRANCH_MANAGER;

CREATE SYNONYM AGENT_API.ENTITIES FOR &&SCHEMA_OWNER..ENTITIES;
CREATE SYNONYM AGENT_API.ENTITY_EDGES FOR &&SCHEMA_OWNER..ENTITY_EDGES;
CREATE SYNONYM AGENT_API.KNOWLEDGE_META FOR &&SCHEMA_OWNER..KNOWLEDGE_META;
CREATE SYNONYM AGENT_API.ENTITY_EMBEDDINGS FOR &&SCHEMA_OWNER..ENTITY_EMBEDDINGS;
CREATE SYNONYM AGENT_API.HARNESS_META FOR &&SCHEMA_OWNER..HARNESS_META;
CREATE SYNONYM AGENT_API.CONTEXT_BRANCHES FOR &&SCHEMA_OWNER..CONTEXT_BRANCHES;
CREATE SYNONYM AGENT_API.SPEC_META FOR &&SCHEMA_OWNER..SPEC_META;
CREATE SYNONYM AGENT_API.SKILL_META FOR &&SCHEMA_OWNER..SKILL_META;
CREATE SYNONYM AGENT_API.TAGS FOR &&SCHEMA_OWNER..TAGS;
CREATE SYNONYM AGENT_API.ENTITY_TAGS FOR &&SCHEMA_OWNER..ENTITY_TAGS;
CREATE SYNONYM AGENT_API.SYSTEM_USERS FOR &&SCHEMA_OWNER..SYSTEM_USERS;
CREATE SYNONYM AGENT_API.AGENT_REGISTRY FOR &&SCHEMA_OWNER..AGENT_REGISTRY;
CREATE SYNONYM AGENT_API.AGENT_CREDENTIALS FOR &&SCHEMA_OWNER..AGENT_CREDENTIALS;
CREATE SYNONYM AGENT_API.WORKSPACES FOR &&SCHEMA_OWNER..WORKSPACES;
CREATE SYNONYM AGENT_API.WORKSPACE_CONTEXT FOR &&SCHEMA_OWNER..WORKSPACE_CONTEXT;
CREATE SYNONYM AGENT_API.BRANCH_MERGE_LOG FOR &&SCHEMA_OWNER..BRANCH_MERGE_LOG;
CREATE SYNONYM AGENT_API.AGENT_SESSION FOR &&SCHEMA_OWNER..AGENT_SESSION;
CREATE SYNONYM AGENT_API.ENTITY_ACCESS_LOG FOR &&SCHEMA_OWNER..ENTITY_ACCESS_LOG;
CREATE SYNONYM AGENT_API.AGENT_PERMISSION_LOG FOR &&SCHEMA_OWNER..AGENT_PERMISSION_LOG;
CREATE SYNONYM AGENT_API.AGENT_COLLABORATION FOR &&SCHEMA_OWNER..AGENT_COLLABORATION;
CREATE SYNONYM AGENT_API.COLLAB_GROUPS FOR &&SCHEMA_OWNER..COLLAB_GROUPS;
CREATE SYNONYM AGENT_API.COLLAB_GROUP_MEMBERS FOR &&SCHEMA_OWNER..COLLAB_GROUP_MEMBERS;
CREATE SYNONYM AGENT_API.TASK_PLANS FOR &&SCHEMA_OWNER..TASK_PLANS;
CREATE SYNONYM AGENT_API.TASK_STEPS FOR &&SCHEMA_OWNER..TASK_STEPS;
CREATE SYNONYM AGENT_API.TASK_CONTEXT_SNAPSHOTS FOR &&SCHEMA_OWNER..TASK_CONTEXT_SNAPSHOTS;
CREATE SYNONYM AGENT_API.TASK_TOOL_CALLS FOR &&SCHEMA_OWNER..TASK_TOOL_CALLS;
CREATE SYNONYM AGENT_API.TASK_DEPENDENCIES FOR &&SCHEMA_OWNER..TASK_DEPENDENCIES;
CREATE SYNONYM AGENT_API.SPEC_PLAN_LINKS FOR &&SCHEMA_OWNER..SPEC_PLAN_LINKS;
CREATE SYNONYM AGENT_API.WORKSPACE_TASKS FOR &&SCHEMA_OWNER..WORKSPACE_TASKS;
CREATE SYNONYM AGENT_API.LDAP_CONFIG FOR &&SCHEMA_OWNER..LDAP_CONFIG;
CREATE SYNONYM AGENT_API.LDAP_SYNC_LOG FOR &&SCHEMA_OWNER..LDAP_SYNC_LOG;
CREATE SYNONYM AGENT_API.SKILL_ACCESS_TOKEN FOR &&SCHEMA_OWNER..SKILL_ACCESS_TOKEN;
-- SYSTEM_CONFIG synonym intentionally NOT created (protected by Deep Sec)
CREATE SYNONYM AGENT_API.CONTEXT_AUDIT_LOG FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_LOG;
CREATE SYNONYM AGENT_API.CONTEXT_AUDIT_RULES FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_RULES;

CREATE SYNONYM AGENT_API.BRANCH_COMPARISON FOR &&SCHEMA_OWNER..BRANCH_COMPARISON;

PROMPT ============================================================
PROMPT Revoking dangerous privileges (safety net)
PROMPT ============================================================
-- AGENT_API should NEVER have these. These REVOKE statements
-- are a safety net in case they were accidentally granted.

REVOKE CREATE TABLE FROM AGENT_API;
REVOKE CREATE VIEW FROM AGENT_API;
REVOKE CREATE PROCEDURE FROM AGENT_API;
REVOKE CREATE TRIGGER FROM AGENT_API;
REVOKE CREATE SEQUENCE FROM AGENT_API;
REVOKE CREATE TYPE FROM AGENT_API;
REVOKE ALTER ANY TABLE FROM AGENT_API;
REVOKE DROP ANY TABLE FROM AGENT_API;
REVOKE INSERT ANY TABLE FROM AGENT_API;
REVOKE UPDATE ANY TABLE FROM AGENT_API;
REVOKE DELETE ANY TABLE FROM AGENT_API;

PROMPT ============================================================
PROMPT Granting Deep Data Security privileges to AIADMIN
PROMPT ============================================================

GRANT CREATE END USER TO &&SCHEMA_OWNER;
GRANT CREATE END USER CONTEXT TO &&SCHEMA_OWNER;
GRANT CREATE ANY END USER CONTEXT TO &&SCHEMA_OWNER;
GRANT CREATE END USER SECURITY CONTEXT TO &&SCHEMA_OWNER;
GRANT CREATE DATA GRANT TO &&SCHEMA_OWNER;
GRANT CREATE ANY DATA GRANT TO &&SCHEMA_OWNER;
GRANT ADMINISTER ANY DATA GRANT TO &&SCHEMA_OWNER;
GRANT CREATE DATA ROLE TO &&SCHEMA_OWNER;
GRANT DROP DATA ROLE TO &&SCHEMA_OWNER;
GRANT GRANT ANY DATA ROLE TO &&SCHEMA_OWNER;
GRANT SET USE DATA GRANTS ONLY TO &&SCHEMA_OWNER;
GRANT ALTER END USER TO &&SCHEMA_OWNER;
GRANT DROP END USER TO &&SCHEMA_OWNER;
GRANT CREATE ANY CONTEXT TO &&SCHEMA_OWNER;

PROMPT ============================================================
PROMPT Creating DEEP_SEC_SESSION_ROLE for End User login
PROMPT ============================================================
-- This role carries CREATE SESSION for Deep Sec End Users.
-- End Users connect via Direct Logon with this role granted
-- through their Data Role (agent_data_role / admin_data_role / pool_agent_data_role).

CREATE ROLE DEEP_SEC_SESSION_ROLE;
GRANT CREATE SESSION TO DEEP_SEC_SESSION_ROLE;
GRANT DEEP_SEC_SESSION_ROLE TO &&SCHEMA_OWNER WITH ADMIN OPTION;

PROMPT ============================================================
PROMPT AGENT_API user setup complete
PROMPT ============================================================
PROMPT 
PROMPT Connection string for Agents:
PROMPT   user=AGENT_API, password=agent_api_2026, dsn=<same_as_aiadmin>
PROMPT 
PROMPT IMPORTANT: Update config.json to use AGENT_API credentials
PROMPT           for runtime Agent connections. Keep AIADMIN
PROMPT           credentials for deployment only.
PROMPT ============================================================

-- v3.8.0: Updated table grants
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_MESSAGES TO AGENT_API;
CREATE SYNONYM AGENT_API.COLLAB_MESSAGES FOR &&SCHEMA_OWNER..COLLAB_MESSAGES;

GRANT SELECT, INSERT, UPDATE ON STEP_RETRY_POLICY TO AGENT_API;
CREATE SYNONYM AGENT_API.STEP_RETRY_POLICY FOR &&SCHEMA_OWNER..STEP_RETRY_POLICY;

GRANT SELECT, INSERT, UPDATE ON STEP_EXECUTION_PLAN TO AGENT_API;
CREATE SYNONYM AGENT_API.STEP_EXECUTION_PLAN FOR &&SCHEMA_OWNER..STEP_EXECUTION_PLAN;

GRANT SELECT ON &&SCHEMA_OWNER..EVENT_LOG TO AGENT_API;
CREATE SYNONYM AGENT_API.EVENT_LOG FOR &&SCHEMA_OWNER..EVENT_LOG;

GRANT SELECT, INSERT, UPDATE ON EVENT_SUBSCRIPTIONS TO AGENT_API;
CREATE SYNONYM AGENT_API.EVENT_SUBSCRIPTIONS FOR &&SCHEMA_OWNER..EVENT_SUBSCRIPTIONS;

GRANT SELECT ON &&SCHEMA_OWNER..AGENT_CAPABILITY_INDEX TO AGENT_API;
CREATE SYNONYM AGENT_API.AGENT_CAPABILITY_INDEX FOR &&SCHEMA_OWNER..AGENT_CAPABILITY_INDEX;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_REGISTRY TO AGENT_API;
CREATE SYNONYM AGENT_API.TOOL_REGISTRY FOR &&SCHEMA_OWNER..TOOL_REGISTRY;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_CHAINS TO AGENT_API;
CREATE SYNONYM AGENT_API.TOOL_CHAINS FOR &&SCHEMA_OWNER..TOOL_CHAINS;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_CHAIN_STEPS TO AGENT_API;
CREATE SYNONYM AGENT_API.TOOL_CHAIN_STEPS FOR &&SCHEMA_OWNER..TOOL_CHAIN_STEPS;
