-- ============================================================
-- 4_grants.sql — Restricted Database User & Access Control
-- AI Agent Infra with YashanDB v3.8.0
-- ============================================================
-- 
-- This script creates a restricted database user (AGENT_API) that
-- Admin/runtime services may use instead of the schema owner (AIADMIN).
-- Business Agents MUST use independently provisioned users. This account:
--   - Can EXECUTE PL/SQL API packages (AUTHID DEFINER)
--   - Can SELECT on tables (read-only access)
--   - CANNOT INSERT/UPDATE/DELETE directly on tables
--   - CANNOT CREATE/ALTER/DROP tables, views, or procedures
--   - CANNOT perform DDL of any kind
--
-- Prerequisites:
--   - Run as SYSDBA: yasql sys/password@//host:port/service as sysdba @4_grants.sql
--   - Schema owner (AIADMIN) must already exist with all objects deployed
--
-- ============================================================

-- ============================================================
-- Schema owner configuration (adjust if not using default AIADMIN)
-- ============================================================
DEFINE SCHEMA_OWNER = 'AIADMIN'
DEFINE AGENT_USER = 'AGENT_API'

PROMPT ============================================================
PROMPT Creating restricted database user: AGENT_API
PROMPT ============================================================

-- Create user using the schema owner's default tablespace (auto-detected)
DECLARE
    v_ts VARCHAR2(128);
    v_count NUMBER;
    v_password VARCHAR2(64);
BEGIN
    SELECT DEFAULT_TABLESPACE INTO v_ts
    FROM DBA_USERS WHERE USERNAME = UPPER('&&SCHEMA_OWNER');
    SELECT COUNT(*) INTO v_count FROM DBA_USERS WHERE USERNAME = UPPER('&&AGENT_USER');
    IF v_count = 0 THEN
        v_password := RAWTOHEX(SYS_GUID()) || RAWTOHEX(SYS_GUID());
        EXECUTE IMMEDIATE 'CREATE USER &&AGENT_USER IDENTIFIED BY "' || v_password || '" DEFAULT TABLESPACE ' || v_ts || ' QUOTA 0 ON ' || v_ts;
    END IF;
END;
/
GRANT CREATE SESSION TO AGENT_API;

PROMPT ============================================================
PROMPT Granting EXECUTE on PL/SQL API packages
PROMPT ============================================================
-- These packages use AUTHID DEFINER (default), so they execute
-- with AIADMIN privileges while enforcing business logic.

GRANT EXECUTE ON &&SCHEMA_OWNER..MEMORY_FUSION_ENGINE TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..KNOWLEDGE_BASE_API TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..AGENT_PERMISSION_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SESSION_CLEANUP TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..WORKSPACE_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SPEC_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..COLLAB_GROUP_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..EMBEDDING_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..LDAP_AUTH_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..SKILL_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..CONTEXT_AUDIT_MANAGER TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..DB_CRYPTO TO AGENT_API;
GRANT EXECUTE ON &&SCHEMA_OWNER..BRANCH_MANAGER TO AGENT_API;

PROMPT ============================================================
PROMPT Granting SELECT on tables (read-only access)
PROMPT ============================================================
-- Agents can query data directly but cannot modify it.
-- All modifications must go through PL/SQL packages.

GRANT SELECT ON &&SCHEMA_OWNER..ENTITIES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_EDGES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..KNOWLEDGE_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_EMBEDDINGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..HARNESS_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_BRANCHES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SPEC_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SKILL_META TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TAGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_TAGS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SYSTEM_USERS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_REGISTRY TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_CREDENTIALS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACE_CONTEXT TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..BRANCH_MERGE_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_SESSION TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..ENTITY_ACCESS_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_PERMISSION_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..AGENT_COLLABORATION TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_GROUPS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_GROUP_MEMBERS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_PLANS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_STEPS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_CONTEXT_SNAPSHOTS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_TOOL_CALLS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..TASK_DEPENDENCIES TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SPEC_PLAN_LINKS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..WORKSPACE_TASKS TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..LDAP_CONFIG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..LDAP_SYNC_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..SKILL_ACCESS_TOKEN TO AGENT_API;
-- SYSTEM_CONFIG: NOT granted — protected by Deep Sec Data Grant (admin_data_role only)
-- Agents must access config through PL/SQL packages (DB_CRYPTO)
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_AUDIT_LOG TO AGENT_API;
GRANT SELECT ON &&SCHEMA_OWNER..CONTEXT_AUDIT_RULES TO AGENT_API;

PROMPT ============================================================
PROMPT Granting SELECT on views
PROMPT ============================================================


PROMPT ============================================================
PROMPT Creating synonyms for convenience
PROMPT ============================================================
-- Allows AGENT_API to reference objects without &&SCHEMA_OWNER.. prefix

CREATE OR REPLACE SYNONYM AGENT_API.MEMORY_FUSION_ENGINE FOR &&SCHEMA_OWNER..MEMORY_FUSION_ENGINE;
CREATE OR REPLACE SYNONYM AGENT_API.KNOWLEDGE_BASE_API FOR &&SCHEMA_OWNER..KNOWLEDGE_BASE_API;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_PERMISSION_MANAGER FOR &&SCHEMA_OWNER..AGENT_PERMISSION_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.SESSION_CLEANUP FOR &&SCHEMA_OWNER..SESSION_CLEANUP;
CREATE OR REPLACE SYNONYM AGENT_API.WORKSPACE_MANAGER FOR &&SCHEMA_OWNER..WORKSPACE_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.SPEC_MANAGER FOR &&SCHEMA_OWNER..SPEC_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.COLLAB_GROUP_MANAGER FOR &&SCHEMA_OWNER..COLLAB_GROUP_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.EMBEDDING_MANAGER FOR &&SCHEMA_OWNER..EMBEDDING_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.LDAP_AUTH_MANAGER FOR &&SCHEMA_OWNER..LDAP_AUTH_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.SKILL_MANAGER FOR &&SCHEMA_OWNER..SKILL_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.CONTEXT_AUDIT_MANAGER FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_MANAGER;
CREATE OR REPLACE SYNONYM AGENT_API.DB_CRYPTO FOR &&SCHEMA_OWNER..DB_CRYPTO;
CREATE OR REPLACE SYNONYM AGENT_API.BRANCH_MANAGER FOR &&SCHEMA_OWNER..BRANCH_MANAGER;

CREATE OR REPLACE SYNONYM AGENT_API.ENTITIES FOR &&SCHEMA_OWNER..ENTITIES;
CREATE OR REPLACE SYNONYM AGENT_API.ENTITY_EDGES FOR &&SCHEMA_OWNER..ENTITY_EDGES;
CREATE OR REPLACE SYNONYM AGENT_API.KNOWLEDGE_META FOR &&SCHEMA_OWNER..KNOWLEDGE_META;
CREATE OR REPLACE SYNONYM AGENT_API.ENTITY_EMBEDDINGS FOR &&SCHEMA_OWNER..ENTITY_EMBEDDINGS;
CREATE OR REPLACE SYNONYM AGENT_API.HARNESS_META FOR &&SCHEMA_OWNER..HARNESS_META;
CREATE OR REPLACE SYNONYM AGENT_API.CONTEXT_BRANCHES FOR &&SCHEMA_OWNER..CONTEXT_BRANCHES;
CREATE OR REPLACE SYNONYM AGENT_API.SPEC_META FOR &&SCHEMA_OWNER..SPEC_META;
CREATE OR REPLACE SYNONYM AGENT_API.SKILL_META FOR &&SCHEMA_OWNER..SKILL_META;
CREATE OR REPLACE SYNONYM AGENT_API.TAGS FOR &&SCHEMA_OWNER..TAGS;
CREATE OR REPLACE SYNONYM AGENT_API.ENTITY_TAGS FOR &&SCHEMA_OWNER..ENTITY_TAGS;
CREATE OR REPLACE SYNONYM AGENT_API.SYSTEM_USERS FOR &&SCHEMA_OWNER..SYSTEM_USERS;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_REGISTRY FOR &&SCHEMA_OWNER..AGENT_REGISTRY;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_CREDENTIALS FOR &&SCHEMA_OWNER..AGENT_CREDENTIALS;
CREATE OR REPLACE SYNONYM AGENT_API.WORKSPACES FOR &&SCHEMA_OWNER..WORKSPACES;
CREATE OR REPLACE SYNONYM AGENT_API.WORKSPACE_CONTEXT FOR &&SCHEMA_OWNER..WORKSPACE_CONTEXT;
CREATE OR REPLACE SYNONYM AGENT_API.BRANCH_MERGE_LOG FOR &&SCHEMA_OWNER..BRANCH_MERGE_LOG;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_SESSION FOR &&SCHEMA_OWNER..AGENT_SESSION;
CREATE OR REPLACE SYNONYM AGENT_API.ENTITY_ACCESS_LOG FOR &&SCHEMA_OWNER..ENTITY_ACCESS_LOG;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_PERMISSION_LOG FOR &&SCHEMA_OWNER..AGENT_PERMISSION_LOG;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_COLLABORATION FOR &&SCHEMA_OWNER..AGENT_COLLABORATION;
CREATE OR REPLACE SYNONYM AGENT_API.COLLAB_GROUPS FOR &&SCHEMA_OWNER..COLLAB_GROUPS;
CREATE OR REPLACE SYNONYM AGENT_API.COLLAB_GROUP_MEMBERS FOR &&SCHEMA_OWNER..COLLAB_GROUP_MEMBERS;
CREATE OR REPLACE SYNONYM AGENT_API.TASK_PLANS FOR &&SCHEMA_OWNER..TASK_PLANS;
CREATE OR REPLACE SYNONYM AGENT_API.TASK_STEPS FOR &&SCHEMA_OWNER..TASK_STEPS;
CREATE OR REPLACE SYNONYM AGENT_API.TASK_CONTEXT_SNAPSHOTS FOR &&SCHEMA_OWNER..TASK_CONTEXT_SNAPSHOTS;
CREATE OR REPLACE SYNONYM AGENT_API.TASK_TOOL_CALLS FOR &&SCHEMA_OWNER..TASK_TOOL_CALLS;
CREATE OR REPLACE SYNONYM AGENT_API.TASK_DEPENDENCIES FOR &&SCHEMA_OWNER..TASK_DEPENDENCIES;
CREATE OR REPLACE SYNONYM AGENT_API.SPEC_PLAN_LINKS FOR &&SCHEMA_OWNER..SPEC_PLAN_LINKS;
CREATE OR REPLACE SYNONYM AGENT_API.WORKSPACE_TASKS FOR &&SCHEMA_OWNER..WORKSPACE_TASKS;
CREATE OR REPLACE SYNONYM AGENT_API.LDAP_CONFIG FOR &&SCHEMA_OWNER..LDAP_CONFIG;
CREATE OR REPLACE SYNONYM AGENT_API.LDAP_SYNC_LOG FOR &&SCHEMA_OWNER..LDAP_SYNC_LOG;
CREATE OR REPLACE SYNONYM AGENT_API.SKILL_ACCESS_TOKEN FOR &&SCHEMA_OWNER..SKILL_ACCESS_TOKEN;
-- SYSTEM_CONFIG synonym intentionally NOT created (protected by Deep Sec)
CREATE OR REPLACE SYNONYM AGENT_API.CONTEXT_AUDIT_LOG FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_LOG;
CREATE OR REPLACE SYNONYM AGENT_API.CONTEXT_AUDIT_RULES FOR &&SCHEMA_OWNER..CONTEXT_AUDIT_RULES;


PROMPT ============================================================
PROMPT Revoking dangerous privileges (safety net)
PROMPT ============================================================
-- AGENT_API should NEVER have these. These REVOKE statements
-- are a safety net in case they were accidentally granted.

BEGIN
    FOR r IN (
        SELECT PRIVILEGE FROM DBA_SYS_PRIVS
        WHERE GRANTEE = 'AGENT_API'
          AND PRIVILEGE IN (
              'CREATE TABLE', 'CREATE VIEW', 'CREATE PROCEDURE', 'CREATE TRIGGER',
              'CREATE SEQUENCE', 'CREATE TYPE', 'ALTER ANY TABLE', 'DROP ANY TABLE',
              'INSERT ANY TABLE', 'UPDATE ANY TABLE', 'DELETE ANY TABLE'
          )
    ) LOOP
        EXECUTE IMMEDIATE 'REVOKE ' || r.PRIVILEGE || ' FROM AGENT_API';
    END LOOP;
END;
/

PROMPT ============================================================
PROMPT Granting independent-user management privileges to AIADMIN
PROMPT ============================================================

GRANT CREATE USER TO &&SCHEMA_OWNER;
GRANT ALTER USER TO &&SCHEMA_OWNER;
GRANT DROP USER TO &&SCHEMA_OWNER;
GRANT CREATE ANY CONTEXT TO &&SCHEMA_OWNER;

PROMPT ============================================================
PROMPT Creating DEEP_SEC_SESSION_ROLE for End User login
PROMPT ============================================================
-- This role carries CREATE SESSION for Deep Sec End Users.
-- End Users connect via Direct Logon with this role granted
-- through their Data Role (agent_data_role / admin_data_role / pool_agent_data_role).

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM DBA_ROLES WHERE ROLE = 'DEEP_SEC_SESSION_ROLE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE DEEP_SEC_SESSION_ROLE';
    END IF;
END;
/
GRANT CREATE SESSION TO DEEP_SEC_SESSION_ROLE;
GRANT ALTER SESSION TO DEEP_SEC_SESSION_ROLE;
GRANT DEEP_SEC_SESSION_ROLE TO &&SCHEMA_OWNER WITH ADMIN OPTION;

PROMPT Granting least-privilege Business Agent access

DECLARE
    v_sql VARCHAR2(4000);
BEGIN
    FOR r IN (
        SELECT TABLE_NAME
        FROM DBA_TABLES
        WHERE OWNER = UPPER('&&SCHEMA_OWNER')
          AND TABLE_NAME NOT IN (
              'SYSTEM_CONFIG', 'SYSTEM_USERS', 'AGENT_CREDENTIALS',
              'AGENT_PERMISSION_LOG', 'ENTITY_ACCESS_LOG', 'CONTEXT_AUDIT_LOG',
              'CONTEXT_AUDIT_RULES', 'EXECUTION_AUDIT', 'APPROVAL_REQUESTS',
              'LDAP_CONFIG', 'LDAP_SYNC_LOG', 'SKILL_ACCESS_TOKEN'
          )
    ) LOOP
        v_sql := 'GRANT SELECT, INSERT, UPDATE, DELETE ON &&SCHEMA_OWNER..' ||
                 r.TABLE_NAME || ' TO DEEP_SEC_SESSION_ROLE';
        EXECUTE IMMEDIATE v_sql;
    END LOOP;
END;
/

GRANT EXECUTE ON &&SCHEMA_OWNER..MEMORY_FUSION_ENGINE TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..KNOWLEDGE_BASE_API TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..AGENT_PERMISSION_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..SESSION_CLEANUP TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..WORKSPACE_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..SPEC_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..COLLAB_GROUP_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..EMBEDDING_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..SKILL_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..CONTEXT_AUDIT_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..BRANCH_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..TRACE_MANAGER TO DEEP_SEC_SESSION_ROLE;
GRANT EXECUTE ON &&SCHEMA_OWNER..MONITOR_MANAGER TO DEEP_SEC_SESSION_ROLE;

PROMPT ============================================================
PROMPT AGENT_API user setup complete
PROMPT ============================================================
PROMPT 
PROMPT AGENT_API is an internal restricted principal with a generated password.
PROMPT Business Agents must use independently provisioned database users.
PROMPT ============================================================

-- v3.8.0: Updated table grants
GRANT SELECT ON &&SCHEMA_OWNER..COLLAB_MESSAGES TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.COLLAB_MESSAGES FOR &&SCHEMA_OWNER..COLLAB_MESSAGES;

GRANT SELECT, INSERT, UPDATE ON &&SCHEMA_OWNER..STEP_RETRY_POLICY TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.STEP_RETRY_POLICY FOR &&SCHEMA_OWNER..STEP_RETRY_POLICY;

GRANT SELECT, INSERT, UPDATE ON &&SCHEMA_OWNER..STEP_EXECUTION_PLAN TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.STEP_EXECUTION_PLAN FOR &&SCHEMA_OWNER..STEP_EXECUTION_PLAN;

GRANT SELECT ON &&SCHEMA_OWNER..EVENT_LOG TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.EVENT_LOG FOR &&SCHEMA_OWNER..EVENT_LOG;

GRANT SELECT, INSERT, UPDATE ON &&SCHEMA_OWNER..EVENT_SUBSCRIPTIONS TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.EVENT_SUBSCRIPTIONS FOR &&SCHEMA_OWNER..EVENT_SUBSCRIPTIONS;

GRANT SELECT ON &&SCHEMA_OWNER..AGENT_CAPABILITY_INDEX TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.AGENT_CAPABILITY_INDEX FOR &&SCHEMA_OWNER..AGENT_CAPABILITY_INDEX;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_REGISTRY TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.TOOL_REGISTRY FOR &&SCHEMA_OWNER..TOOL_REGISTRY;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_CHAINS TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.TOOL_CHAINS FOR &&SCHEMA_OWNER..TOOL_CHAINS;

GRANT SELECT ON &&SCHEMA_OWNER..TOOL_CHAIN_STEPS TO AGENT_API;
CREATE OR REPLACE SYNONYM AGENT_API.TOOL_CHAIN_STEPS FOR &&SCHEMA_OWNER..TOOL_CHAIN_STEPS;
