-- v4.4.9: YashanDB treats empty strings as NULL; local identity must be explicit.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE SYSTEM_USERS DROP CONSTRAINT CK_SU_AUTH_SOURCE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TABLE SYSTEM_USERS ADD CONSTRAINT CK_SU_AUTH_SOURCE CHECK (AUTH_SOURCE IN ('LOCAL','LDAP'));
