-- v4.4.9 Enterprise audit-page contract alignment.
DECLARE
  PROCEDURE ddl(s VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE s;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  ddl('CREATE TABLE CONTEXT_AUDIT_LOG (AUDIT_ID VARCHAR2(64) PRIMARY KEY,ENTITY_ID VARCHAR2(128) NOT NULL,ENTITY_TYPE VARCHAR2(64) NOT NULL,AUDIT_TYPE VARCHAR2(32) NOT NULL,RULE_ID VARCHAR2(128),SIMILARITY_SCORE NUMBER(8,6),THRESHOLD_SCORE NUMBER(8,6),VIOLATION_DETAIL CLOB,AGENT_ID VARCHAR2(128),SESSION_ID VARCHAR2(128),WORKSPACE_ID VARCHAR2(128),RESOLUTION_STATUS VARCHAR2(32) DEFAULT ''OPEN'' NOT NULL,RESOLVED_BY VARCHAR2(128),RESOLVED_AT TIMESTAMP,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT CK_CTX_AUDIT_TYPE CHECK(AUDIT_TYPE IN (''RULE_VIOLATION'',''CONTEXT_SIMILARITY'',''IDLE_PATTERN'',''ACCESS_ANOMALY'',''DATA_LEAK'')),CONSTRAINT CK_CTX_AUDIT_STATUS CHECK(RESOLUTION_STATUS IN (''OPEN'',''ACKNOWLEDGED'',''RESOLVED'',''FALSE_POSITIVE'',''ESCALATED'')))');
  ddl('CREATE INDEX IDX_CONTEXT_AUDIT_STATUS ON CONTEXT_AUDIT_LOG(RESOLUTION_STATUS,CREATED_AT)');
  ddl('CREATE INDEX IDX_CONTEXT_AUDIT_TYPE ON CONTEXT_AUDIT_LOG(AUDIT_TYPE,CREATED_AT)');
END;
/
