-- v4.4.10 fresh-baseline knowledge visibility policy.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CX_KNOWLEDGE_ACCESS_POLICIES (POLICY_ID VARCHAR2(128) PRIMARY KEY, ENTITY_ID VARCHAR2(128) NOT NULL, SCOPE_TYPE VARCHAR2(32) NOT NULL, ORGANIZATION_ID VARCHAR2(128), PRINCIPAL_ID VARCHAR2(128), HIERARCHY_DEPTH NUMBER(10), STATUS VARCHAR2(16) DEFAULT ''ACTIVE'' NOT NULL, VALID_FROM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, VALID_UNTIL TIMESTAMP, REASON VARCHAR2(2000) DEFAULT ''initial policy'' NOT NULL, CREATED_BY VARCHAR2(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
CREATE INDEX IDX_CX_KAP_ENTITY ON CX_KNOWLEDGE_ACCESS_POLICIES(ENTITY_ID,STATUS,VALID_UNTIL);
CREATE INDEX IDX_CX_KAP_ORG ON CX_KNOWLEDGE_ACCESS_POLICIES(ORGANIZATION_ID,SCOPE_TYPE,STATUS);
