-- v4.4.10 Agent knowledge provenance: relational org/group snapshot plus graph trace.
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CX_KNOWLEDGE_CONTEXTS (CONTEXT_ID VARCHAR2(128) PRIMARY KEY, ENTITY_ID VARCHAR2(128) NOT NULL UNIQUE, AGENT_ID VARCHAR2(128) NOT NULL, PRINCIPAL_ID VARCHAR2(128), ORGANIZATION_ID VARCHAR2(128), ORGANIZATION_CHAIN_JSON CLOB NOT NULL, RESPONSIBLE_GROUPS_JSON CLOB NOT NULL, EXECUTION_GROUPS_JSON CLOB NOT NULL, SHARING_SCOPE VARCHAR2(32) NOT NULL, GRAPH_SNAPSHOT_DIGEST VARCHAR2(64) NOT NULL, REASON VARCHAR2(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT CK_CX_KCTX_SCOPE CHECK (SHARING_SCOPE IN (''PUBLIC_COMPANY'',''ORGANIZATION_SUBTREE'',''ORGANIZATION_LEVEL'',''PRINCIPAL_PRIVATE'')) )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
CREATE INDEX IDX_CX_KCTX_AGENT ON CX_KNOWLEDGE_CONTEXTS(AGENT_ID,CREATED_AT);
CREATE INDEX IDX_CX_KCTX_ORG ON CX_KNOWLEDGE_CONTEXTS(ORGANIZATION_ID,SHARING_SCOPE);
