-- v4.4.10 organization approval closure. Additive so initialized baselines remain upgradeable.
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_APPROVAL_ENTITY';
  IF n > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE APPROVAL_REQUESTS DROP CONSTRAINT CK_APPROVAL_ENTITY'; END IF;
END;
/
ALTER TABLE APPROVAL_REQUESTS ADD CONSTRAINT CK_APPROVAL_ENTITY
  CHECK (ENTITY_TYPE IN ('STEP','LOOP','TOOL','ORGANIZATION_CHANGE'));

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'CX_AGENT_RELATIONSHIP_HISTORY';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_RELATIONSHIP_HISTORY (
    HISTORY_ID VARCHAR2(128) PRIMARY KEY, VERSION_ID VARCHAR2(128) NOT NULL,
    RELATIONSHIP_ID VARCHAR2(128) NOT NULL, AGENT_ID VARCHAR2(128) NOT NULL,
    PRINCIPAL_ID VARCHAR2(128) NOT NULL, RELATIONSHIP_ROLE VARCHAR2(32) NOT NULL,
    RESPONSIBLE_ORGANIZATION_ID VARCHAR2(128), OPERATION VARCHAR2(16) NOT NULL,
    FACT_JSON CLOB NOT NULL, FACT_DIGEST VARCHAR2(128) NOT NULL,
    ACTOR_PRINCIPAL_ID VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL,
    RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_AGENT_REL_HIST_OP CHECK (OPERATION IN (''INSERT'',''UPDATE'',''END'')))'; END IF;
END;
/
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CX_AGENT_REL_HISTORY';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_AGENT_REL_HISTORY ON CX_AGENT_RELATIONSHIP_HISTORY(AGENT_ID, RECORDED_AT)'; END IF;
END;
/
