-- v4.4.10 external Agent Embedding authorization. External access is deny-by-default in the service.
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'CX_EMBEDDING_ACCESS_GRANTS';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CX_EMBEDDING_ACCESS_GRANTS (
    GRANT_ID VARCHAR2(128) PRIMARY KEY, GRANT_KEY VARCHAR2(64) UNIQUE NOT NULL,
    SUBJECT_TYPE VARCHAR2(32) NOT NULL, SUBJECT_ID VARCHAR2(128) NOT NULL,
    EFFECT VARCHAR2(16) NOT NULL, ALLOWED_PROFILE_ID VARCHAR2(128),
    MAX_BATCH_SIZE NUMBER(5) DEFAULT 1 NOT NULL, MAX_INPUT_CHARS NUMBER(10) DEFAULT 16000 NOT NULL,
    VALID_FROM TIMESTAMP, VALID_UNTIL TIMESTAMP, STATUS VARCHAR2(24) DEFAULT ''ACTIVE'' NOT NULL,
    VERSION NUMBER(19) DEFAULT 1 NOT NULL, APPROVED_BY VARCHAR2(128) NOT NULL,
    REASON VARCHAR2(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_CX_EAG_SUBJECT CHECK (SUBJECT_TYPE IN (''AGENT'',''TEMPLATE'',''ORGANIZATION'',''SECURITY_DOMAIN'')),
    CONSTRAINT CK_CX_EAG_EFFECT CHECK (EFFECT IN (''ALLOW'',''DENY'')),
    CONSTRAINT CK_CX_EAG_STATUS CHECK (STATUS IN (''ACTIVE'',''REVOKED'')),
    CONSTRAINT CK_CX_EAG_BATCH CHECK (MAX_BATCH_SIZE BETWEEN 1 AND 16),
    CONSTRAINT CK_CX_EAG_CHARS CHECK (MAX_INPUT_CHARS BETWEEN 1 AND 64000),
    CONSTRAINT CK_CX_EAG_VALIDITY CHECK (VALID_UNTIL IS NULL OR VALID_FROM IS NULL OR VALID_UNTIL > VALID_FROM))'; END IF;
END;
/
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CX_EAG_SUBJECT';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_EAG_SUBJECT ON CX_EMBEDDING_ACCESS_GRANTS(SUBJECT_TYPE,SUBJECT_ID,STATUS,VALID_UNTIL)'; END IF;
END;
/
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CX_EAG_PROFILE';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_EAG_PROFILE ON CX_EMBEDDING_ACCESS_GRANTS(ALLOWED_PROFILE_ID,STATUS)'; END IF;
END;
/
