-- v4.4.10 external Agent Embedding execution declaration and Contract evidence.
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='AGENT_REGISTRATIONS';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE AGENT_REGISTRATIONS (AGENT_ID VARCHAR2(128) PRIMARY KEY, OWNER_REF VARCHAR2(256) NOT NULL, RUNTIME VARCHAR2(128) NOT NULL, ENVIRONMENT VARCHAR2(128) NOT NULL, NODE_ID VARCHAR2(128), CAPABILITIES_JSON CLOB, CREDENTIAL_VERSION VARCHAR2(64) NOT NULL, CREDENTIAL_HASH VARCHAR2(128) NOT NULL, STATUS VARCHAR2(32) DEFAULT ''ACTIVE'' NOT NULL, REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, LAST_SEEN_AT TIMESTAMP, EXPIRES_AT TIMESTAMP, IDEMPOTENCY_KEY VARCHAR2(160) NOT NULL UNIQUE, CREATED_BY VARCHAR2(256) NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, EMBEDDING_MODE VARCHAR2(24) DEFAULT ''PLATFORM_MANAGED'' NOT NULL, EMBEDDING_MODEL_ID VARCHAR2(256), EMBEDDING_FINGERPRINT VARCHAR2(256), EMBEDDING_DIMENSION NUMBER(8), EMBEDDING_DISTANCE_METRIC VARCHAR2(32) DEFAULT ''COSINE'' NOT NULL, EMBEDDING_NORMALIZE CHAR(1) DEFAULT ''Y'' NOT NULL)'; END IF;
END;
/
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='AGENT_REGISTRATIONS' AND COLUMN_NAME='EMBEDDING_MODE';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE AGENT_REGISTRATIONS ADD (EMBEDDING_MODE VARCHAR2(24) DEFAULT ''PLATFORM_MANAGED'' NOT NULL, EMBEDDING_MODEL_ID VARCHAR2(256), EMBEDDING_FINGERPRINT VARCHAR2(256), EMBEDDING_DIMENSION NUMBER(8), EMBEDDING_DISTANCE_METRIC VARCHAR2(32) DEFAULT ''COSINE'' NOT NULL, EMBEDDING_NORMALIZE CHAR(1) DEFAULT ''Y'' NOT NULL)'; END IF;
END;
/
