-- v4.4.11 runtime isolation evidence and database-mediated Agent collaboration.
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE CX_RUNTIME_ISOLATION_CONTRACTS (
  CONTRACT_ID VARCHAR2(128) PRIMARY KEY, AGENT_ID VARCHAR2(128) NOT NULL,
  INSTANCE_ID VARCHAR2(128) NOT NULL, ISOLATION_LEVEL VARCHAR2(32) NOT NULL,
  ENFORCEMENT_MODE VARCHAR2(32) NOT NULL, RUNTIME_ADAPTER VARCHAR2(128) NOT NULL,
  RUNTIME_IDENTITY VARCHAR2(256), BOUNDARIES_JSON CLOB NOT NULL,
  POLICY_DIGEST VARCHAR2(256), ROOTFS_DIGEST VARCHAR2(256), EVIDENCE_REF VARCHAR2(512),
  STATUS VARCHAR2(32) NOT NULL, VERSION NUMBER(19,0) DEFAULT 1 NOT NULL,
  CREATED_BY VARCHAR2(128) NOT NULL, UPDATED_BY VARCHAR2(128) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT UK_CX_RUNTIME_ISO UNIQUE(AGENT_ID,INSTANCE_ID),
  CONSTRAINT CK_CX_RUNTIME_LEVEL CHECK(ISOLATION_LEVEL IN (''SHARED'',''DOMAIN_ISOLATED'',''DEDICATED_RUNTIME'',''DEDICATED_CONTAINER'',''DEDICATED_VM'')),
  CONSTRAINT CK_CX_RUNTIME_MODE CHECK(ENFORCEMENT_MODE IN (''VERIFIED'',''UNVERIFIED'',''NOT_APPLICABLE'')))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE CX_DB4A2A_DISPATCHES (
  DISPATCH_ID VARCHAR2(128) PRIMARY KEY, TASK_ID VARCHAR2(256) NOT NULL,
  SENDER_PRINCIPAL_ID VARCHAR2(128) NOT NULL, RECEIVER_AGENT_ID VARCHAR2(128) NOT NULL,
  CONTEXT_REF VARCHAR2(256) NOT NULL, SNAPSHOT_DIGEST VARCHAR2(256) NOT NULL,
  EXPECTED_VERSION NUMBER(19,0) NOT NULL, SCOPE_REF VARCHAR2(256) NOT NULL,
  SOURCE_BRANCH VARCHAR2(256), BRANCH_POLICY VARCHAR2(32) NOT NULL,
  TRANSPORT VARCHAR2(32) NOT NULL, STATUS VARCHAR2(32) NOT NULL,
  CHILD_BRANCH_ID VARCHAR2(128), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CK_CX_DB4A2A_VERSION CHECK(EXPECTED_VERSION>0),
  CONSTRAINT CK_CX_DB4A2A_BRANCH CHECK(BRANCH_POLICY IN (''READ_ONLY'',''CHILD_BRANCH_WRITE'')),
  CONSTRAINT CK_CX_DB4A2A_TRANSPORT CHECK(TRANSPORT IN (''DB_MEDIATED'',''A2A_PAYLOAD'')))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_RUNTIME_ISO_AGENT ON CX_RUNTIME_ISOLATION_CONTRACTS(AGENT_ID,STATUS)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_DB4A2A_PARTICIPANT ON CX_DB4A2A_DISPATCHES(SENDER_PRINCIPAL_ID,RECEIVER_AGENT_ID,CREATED_AT)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
