-- v4.4.11 durable runtime execution admission evidence.
DECLARE c NUMBER; BEGIN
 SELECT COUNT(*) INTO c FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CX_RUNTIME_EXECUTIONS' AND COLUMN_NAME='ISOLATION_EVIDENCE_JSON';
 IF c=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CX_RUNTIME_EXECUTIONS ADD (ISOLATION_EVIDENCE_JSON CLOB)'; END IF;
 SELECT COUNT(*) INTO c FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CX_RUNTIME_EXECUTIONS' AND COLUMN_NAME='ISOLATION_EVIDENCE_REF';
 IF c=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CX_RUNTIME_EXECUTIONS ADD (ISOLATION_EVIDENCE_REF VARCHAR2(512))'; END IF;
 SELECT COUNT(*) INTO c FROM USER_TAB_COLUMNS WHERE TABLE_NAME='CX_RUNTIME_EXECUTIONS' AND COLUMN_NAME='ISOLATION_ADMITTED_AT';
 IF c=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE CX_RUNTIME_EXECUTIONS ADD (ISOLATION_ADMITTED_AT TIMESTAMP)'; END IF;
END;
/
