-- v4.4.11 root bootstrap, Host Manager, and runtime identity leases.
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE CX_RUNTIME_HOST_PROFILES (
  NODE_ID VARCHAR2(128) PRIMARY KEY, HOST_MANAGER_VERSION VARCHAR2(128),
  BOOTSTRAP_STATE VARCHAR2(32) NOT NULL, ROOT_REMOTE_LOGIN VARCHAR2(16) NOT NULL,
  RECOVERY_CHANNEL VARCHAR2(512), UID_MIN NUMBER(10,0) NOT NULL,
  UID_MAX NUMBER(10,0) NOT NULL, PREFLIGHT_DIGEST VARCHAR2(128),
  CREATED_BY VARCHAR2(128) NOT NULL, UPDATED_BY VARCHAR2(128) NOT NULL,
  LAST_PREFLIGHT_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CK_CX_RHP_STATE CHECK(BOOTSTRAP_STATE IN (''PREFLIGHT_FAILED'',''PREFLIGHT_PASSED'',''VERIFIED'',''DRAIN'',''REVOKED'')),
  CONSTRAINT CK_CX_RHP_ROOT CHECK(ROOT_REMOTE_LOGIN IN (''ENABLED'',''DISABLED'')),
  CONSTRAINT CK_CX_RHP_UID CHECK(UID_MIN>=100000 AND UID_MAX>UID_MIN))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE CX_RUNTIME_UID_LEASES (
  LEASE_ID VARCHAR2(128) PRIMARY KEY, NODE_ID VARCHAR2(128) NOT NULL,
  AGENT_ID VARCHAR2(128) NOT NULL, INSTANCE_ID VARCHAR2(128) NOT NULL,
  RUNTIME_UID NUMBER(10,0) NOT NULL, RUNTIME_GID NUMBER(10,0) NOT NULL,
  STATUS VARCHAR2(32) NOT NULL, CREATED_BY VARCHAR2(128) NOT NULL,
  REASON VARCHAR2(2000) NOT NULL, RELEASED_BY VARCHAR2(128),
  RELEASE_REASON VARCHAR2(2000), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  RELEASED_AT TIMESTAMP,
  CONSTRAINT UK_CX_RUL_IDENTITY UNIQUE(NODE_ID,RUNTIME_UID),
  CONSTRAINT UK_CX_RUL_INSTANCE UNIQUE(NODE_ID,AGENT_ID,INSTANCE_ID),
  CONSTRAINT CK_CX_RUL_STATUS CHECK(STATUS IN (''ACTIVE'',''RELEASED'',''REVOKED'')),
  CONSTRAINT CK_CX_RUL_NONROOT CHECK(RUNTIME_UID>0 AND RUNTIME_GID>0))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CX_RUL_AGENT ON CX_RUNTIME_UID_LEASES(AGENT_ID,INSTANCE_ID,STATUS)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
MERGE INTO CX_ROLE_TEMPLATES dst USING (SELECT 'HOST_PROVISIONER' ROLE_CODE FROM DUAL) src ON (dst.ROLE_CODE=src.ROLE_CODE)
WHEN MATCHED THEN UPDATE SET dst.DISPLAY_NAME='Host Provisioner',dst.PERMISSIONS_JSON='["hosts.read","hosts.manage","agents.read","agents.manage","agents.operate","approvals.read","audit.read"]',dst.DATA_SCOPES_JSON='["ALL"]',dst.VERSION=dst.VERSION+1,dst.UPDATED_AT=CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (ROLE_CODE,DISPLAY_NAME,PERMISSIONS_JSON,DATA_SCOPES_JSON) VALUES ('HOST_PROVISIONER','Host Provisioner','["hosts.read","hosts.manage","agents.read","agents.manage","agents.operate","approvals.read","audit.read"]','["ALL"]');
