-- Database-enforced context reads. Missing mappings deny access.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_AGENT_DB_IDENTITIES';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE CX_AGENT_DB_IDENTITIES (AGENT_ID VARCHAR2(128) PRIMARY KEY, DB_USERNAME VARCHAR2(128) UNIQUE NOT NULL)';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_CONTEXT_READ_GRANTS';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE CX_CONTEXT_READ_GRANTS (CONTEXT_ID VARCHAR2(64) NOT NULL, AGENT_ID VARCHAR2(128) NOT NULL, PRIMARY KEY(CONTEXT_ID,AGENT_ID))';
  END IF;
END;
/
CREATE OR REPLACE VIEW CX_AGENT_CONTEXT_READ AS
SELECT c.* FROM WORKSPACE_CONTEXT c
WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_DB_IDENTITIES i
  WHERE i.DB_USERNAME=SYS_CONTEXT('USERENV','SESSION_USER')
    AND EXISTS (SELECT 1 FROM CX_PRINCIPALS p WHERE p.PRINCIPAL_ID=i.AGENT_ID AND p.STATUS='ACTIVE')
    AND (c.AGENT_ID=i.AGENT_ID OR c.VISIBILITY='PUBLIC'
      OR (c.VISIBILITY='SHARED' AND EXISTS (
        SELECT 1 FROM CX_CONTEXT_READ_GRANTS g
        WHERE g.CONTEXT_ID=c.CONTEXT_ID AND g.AGENT_ID=i.AGENT_ID)))
);
GRANT SELECT ON CX_AGENT_CONTEXT_READ TO DEEP_SEC_SESSION_ROLE;
DECLARE
  PROCEDURE revoke_access(p_priv VARCHAR2, p_object VARCHAR2, p_grantee VARCHAR2) IS
    not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
    missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
  BEGIN
    EXECUTE IMMEDIATE 'REVOKE ' || p_priv || ' ON ' || p_object || ' FROM ' || p_grantee;
  EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
  END;
BEGIN
  -- USER_TAB_PRIVS does not enumerate grants made to roles on YashanDB 23.5.
  revoke_access('SELECT, INSERT, UPDATE, DELETE','WORKSPACE_CONTEXT','DEEP_SEC_SESSION_ROLE');
  revoke_access('SELECT, INSERT, UPDATE, DELETE','WORKSPACE_CONTEXT','AGENT_API');
  revoke_access('SELECT, INSERT, UPDATE, DELETE','WORKSPACE_CONTEXT','PUBLIC');
  revoke_access('EXECUTE','WORKSPACE_MANAGER','DEEP_SEC_SESSION_ROLE');
  revoke_access('EXECUTE','WORKSPACE_MANAGER','AGENT_API');
  revoke_access('EXECUTE','BRANCH_MANAGER','DEEP_SEC_SESSION_ROLE');
  revoke_access('EXECUTE','BRANCH_MANAGER','AGENT_API');
END;
/
