-- Independent logins read database-filtered projections, never raw entities.
CREATE OR REPLACE VIEW CX_AGENT_ENTITY_READ AS
SELECT e.* FROM ENTITIES e WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_DB_IDENTITIES i
  JOIN CX_PRINCIPALS p ON p.PRINCIPAL_ID=i.AGENT_ID AND p.STATUS='ACTIVE'
  WHERE i.DB_USERNAME=SYS_CONTEXT('USERENV','SESSION_USER') AND (
    (e.ENTITY_TYPE<>'KNOWLEDGE' AND (e.OWNED_BY_AGENT=i.AGENT_ID OR e.VISIBILITY='PUBLIC'))
    OR (e.ENTITY_TYPE='KNOWLEDGE' AND (
      EXISTS (SELECT 1 FROM CX_KNOWLEDGE_ACCESS_POLICIES k
        WHERE k.ENTITY_ID=e.ENTITY_ID AND k.STATUS='ACTIVE'
          AND k.VALID_FROM<=CURRENT_TIMESTAMP AND (k.VALID_UNTIL IS NULL OR k.VALID_UNTIL>CURRENT_TIMESTAMP)
          AND (k.SCOPE_TYPE='PUBLIC_COMPANY'
            OR (k.SCOPE_TYPE='PRINCIPAL_PRIVATE' AND k.PRINCIPAL_ID=i.AGENT_ID)
            OR (k.SCOPE_TYPE IN ('ORGANIZATION_SUBTREE','ORGANIZATION_LEVEL') AND EXISTS (
              SELECT 1 FROM CX_ORGANIZATION_MEMBERS m
              JOIN CX_ORGANIZATION_CLOSURE c ON c.DESCENDANT_ID=m.ORGANIZATION_ID
              WHERE m.PRINCIPAL_ID=i.AGENT_ID AND m.STATUS='ACTIVE'
                AND m.VALID_FROM<=CURRENT_TIMESTAMP AND (m.VALID_UNTIL IS NULL OR m.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND c.ANCESTOR_ID=k.ORGANIZATION_ID
                AND (k.SCOPE_TYPE='ORGANIZATION_SUBTREE' OR c.DEPTH<=k.HIERARCHY_DEPTH)))))
      OR (NOT EXISTS (SELECT 1 FROM CX_KNOWLEDGE_ACCESS_POLICIES k WHERE k.ENTITY_ID=e.ENTITY_ID)
        AND (e.OWNED_BY_AGENT=i.AGENT_ID OR e.VISIBILITY='PUBLIC'))
    ))
  )
);
CREATE OR REPLACE VIEW CX_AGENT_KNOWLEDGE_READ AS
SELECT e.* FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_TYPE='KNOWLEDGE';
CREATE OR REPLACE VIEW CX_AGENT_KNOWLEDGE_META_READ AS
SELECT m.* FROM KNOWLEDGE_META m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.ENTITY_ID AND e.ENTITY_TYPE=m.ENTITY_TYPE);
CREATE OR REPLACE VIEW CX_AGENT_EMBEDDING_READ AS
SELECT m.* FROM ENTITY_EMBEDDINGS m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.ENTITY_ID AND e.ENTITY_TYPE=m.ENTITY_TYPE);
CREATE OR REPLACE VIEW CX_AGENT_EDGE_READ AS
SELECT m.* FROM ENTITY_EDGES m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.SOURCE_ID)
  AND EXISTS (SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.TARGET_ID);

-- Do not leave a definer-rights package as a bypass to the revoked base tables.
DECLARE
  PROCEDURE revoke_access(p VARCHAR2, o VARCHAR2, g VARCHAR2) IS
    not_granted EXCEPTION; PRAGMA EXCEPTION_INIT(not_granted, 2221);
    missing_grantee EXCEPTION; PRAGMA EXCEPTION_INIT(missing_grantee, 2012);
  BEGIN
    EXECUTE IMMEDIATE 'REVOKE '||p||' ON '||o||' FROM '||g;
  EXCEPTION WHEN not_granted OR missing_grantee THEN NULL;
  END;
BEGIN
  FOR g IN (SELECT 'DEEP_SEC_SESSION_ROLE' name FROM DUAL UNION ALL SELECT 'AGENT_API' FROM DUAL UNION ALL SELECT 'PUBLIC' FROM DUAL) LOOP
    FOR t IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN (
      'ENTITIES','ENTITY_EMBEDDINGS','KNOWLEDGE_META','ENTITY_EDGES','ENTITY_TAGS',
      'CX_KNOWLEDGE_ACCESS_POLICIES','CX_KNOWLEDGE_CONTEXTS')) LOOP
      revoke_access('SELECT, INSERT, UPDATE, DELETE',t.TABLE_NAME,g.name);
    END LOOP;
    FOR p IN (SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE') LOOP
      revoke_access('EXECUTE',p.OBJECT_NAME,g.name);
    END LOOP;
  END LOOP;
END;
/
GRANT SELECT ON CX_AGENT_ENTITY_READ TO DEEP_SEC_SESSION_ROLE;
GRANT SELECT ON CX_AGENT_KNOWLEDGE_READ TO DEEP_SEC_SESSION_ROLE;
GRANT SELECT ON CX_AGENT_KNOWLEDGE_META_READ TO DEEP_SEC_SESSION_ROLE;
GRANT SELECT ON CX_AGENT_EMBEDDING_READ TO DEEP_SEC_SESSION_ROLE;
GRANT SELECT ON CX_AGENT_EDGE_READ TO DEEP_SEC_SESSION_ROLE;

-- Native writes bind ownership to SESSION_USER. No owner or visibility argument.
CREATE OR REPLACE PACKAGE CX_AGENT_ENTITY_API AS
  PROCEDURE CREATE_PRIVATE(p_id VARCHAR2, p_type VARCHAR2, p_title VARCHAR2, p_content CLOB);
  PROCEDURE UPDATE_PRIVATE(p_id VARCHAR2, p_title VARCHAR2, p_content CLOB);
END;
/
CREATE OR REPLACE PACKAGE BODY CX_AGENT_ENTITY_API AS
  FUNCTION current_agent RETURN VARCHAR2 IS
    a VARCHAR2(128);
  BEGIN
    SELECT i.AGENT_ID INTO a FROM CX_AGENT_DB_IDENTITIES i
      JOIN CX_PRINCIPALS p ON p.PRINCIPAL_ID=i.AGENT_ID AND p.STATUS='ACTIVE'
      WHERE i.DB_USERNAME=SYS_CONTEXT('USERENV','SESSION_USER');
    RETURN a;
  END;
  PROCEDURE CREATE_PRIVATE(p_id VARCHAR2, p_type VARCHAR2, p_title VARCHAR2, p_content CLOB) IS
    a VARCHAR2(128);
  BEGIN
    a:=current_agent();
    IF p_type IS NULL OR p_type NOT IN ('MEMORY','KNOWLEDGE') THEN
      RAISE_APPLICATION_ERROR(-20001,'unsupported entity type');
    END IF;
    INSERT INTO ENTITIES(ENTITY_ID,ENTITY_TYPE,TITLE,CONTENT,OWNED_BY_AGENT,SOURCE_AGENT,VISIBILITY)
      VALUES(p_id,p_type,p_title,p_content,a,a,'PRIVATE');
    IF p_type='KNOWLEDGE' THEN
      INSERT INTO KNOWLEDGE_META(ENTITY_ID,ENTITY_TYPE) VALUES(p_id,p_type);
    END IF;
  END;
  PROCEDURE UPDATE_PRIVATE(p_id VARCHAR2, p_title VARCHAR2, p_content CLOB) IS
    a VARCHAR2(128);
  BEGIN
    a:=current_agent();
    UPDATE ENTITIES SET TITLE=p_title,CONTENT=p_content,UPDATED_AT=CURRENT_TIMESTAMP
      WHERE ENTITY_ID=p_id AND OWNED_BY_AGENT=a AND VISIBILITY='PRIVATE'
      AND ENTITY_TYPE IN ('MEMORY','KNOWLEDGE')
      AND NOT EXISTS (SELECT 1 FROM CX_KNOWLEDGE_ACCESS_POLICIES k WHERE k.ENTITY_ID=p_id);
    IF SQL%ROWCOUNT<>1 THEN RAISE_APPLICATION_ERROR(-20002,'entity unavailable'); END IF;
  END;
END;
/
GRANT EXECUTE ON CX_AGENT_ENTITY_API TO DEEP_SEC_SESSION_ROLE;
