-- v4.4.12 organization-scoped knowledge policy constraints.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CK_CX_KAP_SCOPE_V412';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CX_KNOWLEDGE_ACCESS_POLICIES ADD CONSTRAINT CK_CX_KAP_SCOPE_V412 CHECK ((SCOPE_TYPE=''PUBLIC_COMPANY'' AND ORGANIZATION_ID IS NULL AND PRINCIPAL_ID IS NULL) OR (SCOPE_TYPE=''ORGANIZATION_SUBTREE'' AND ORGANIZATION_ID IS NOT NULL AND PRINCIPAL_ID IS NULL) OR (SCOPE_TYPE=''ORGANIZATION_LEVEL'' AND ORGANIZATION_ID IS NOT NULL AND HIERARCHY_DEPTH IS NOT NULL AND PRINCIPAL_ID IS NULL) OR (SCOPE_TYPE=''PRINCIPAL_PRIVATE'' AND PRINCIPAL_ID IS NOT NULL AND ORGANIZATION_ID IS NULL))';
  END IF;
END;
/
