-- Resolve native organization access through the active Human PRIMARY_OWNER.
-- Independent logins read database-filtered projections, never raw entities.
CREATE OR REPLACE VIEW CX_AGENT_ENTITY_READ AS
SELECT e.* FROM ENTITIES e WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_DB_IDENTITIES i
  JOIN CX_PRINCIPALS p ON p.PRINCIPAL_ID=i.AGENT_ID AND p.STATUS='ACTIVE'
  WHERE i.DB_USERNAME=SYS_CONTEXT('USERENV','SESSION_USER') AND (
    (e.ENTITY_TYPE<>'KNOWLEDGE' AND (e.OWNED_BY_AGENT=i.AGENT_ID OR e.VISIBILITY='PUBLIC'))
    OR (e.ENTITY_TYPE='KNOWLEDGE' AND (
      EXISTS (SELECT 1 FROM CX_KNOWLEDGE_ACCESS_POLICIES k
        WHERE k.ENTITY_ID=e.ENTITY_ID AND k.STATUS='ACTIVE'
          AND k.VALID_FROM<=CURRENT_TIMESTAMP AND (k.VALID_UNTIL IS NULL OR k.VALID_UNTIL>CURRENT_TIMESTAMP)
          AND (k.SCOPE_TYPE='PUBLIC_COMPANY'
            OR (k.SCOPE_TYPE='PRINCIPAL_PRIVATE' AND k.PRINCIPAL_ID=i.AGENT_ID)
            OR (k.SCOPE_TYPE IN ('ORGANIZATION_SUBTREE','ORGANIZATION_LEVEL') AND EXISTS (
              SELECT 1 FROM CX_ORGANIZATION_MEMBERS m
              JOIN CX_ORGANIZATION_CLOSURE c ON c.DESCENDANT_ID=m.ORGANIZATION_ID
              JOIN CX_AGENT_RELATIONSHIPS r ON r.PRINCIPAL_ID=m.PRINCIPAL_ID
              JOIN CX_PRINCIPALS h ON h.PRINCIPAL_ID=r.PRINCIPAL_ID
              JOIN CX_PRINCIPALS a ON a.PRINCIPAL_ID=r.AGENT_ID
              JOIN CX_ORGANIZATIONS mo ON mo.ORGANIZATION_ID=m.ORGANIZATION_ID
              JOIN CX_ORGANIZATIONS ko ON ko.ORGANIZATION_ID=k.ORGANIZATION_ID
              WHERE r.AGENT_ID=i.AGENT_ID AND m.STATUS='ACTIVE'
                AND r.RELATIONSHIP_ROLE='PRIMARY_OWNER' AND r.STATUS='ACTIVE'
                AND (r.ENDED_AT IS NULL OR r.ENDED_AT>CURRENT_TIMESTAMP)
                AND h.PRINCIPAL_TYPE='HUMAN' AND h.STATUS='ACTIVE' AND a.STATUS='ACTIVE'
                AND mo.STATUS='ACTIVE' AND ko.STATUS='ACTIVE'
                AND mo.VALID_FROM<=CURRENT_TIMESTAMP AND (mo.VALID_UNTIL IS NULL OR mo.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND ko.VALID_FROM<=CURRENT_TIMESTAMP AND (ko.VALID_UNTIL IS NULL OR ko.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND m.VALID_FROM<=CURRENT_TIMESTAMP AND (m.VALID_UNTIL IS NULL OR m.VALID_UNTIL>CURRENT_TIMESTAMP)
                AND c.ANCESTOR_ID=k.ORGANIZATION_ID
                AND (k.SCOPE_TYPE='ORGANIZATION_SUBTREE' OR c.DEPTH<=k.HIERARCHY_DEPTH)))))
      OR (NOT EXISTS (SELECT 1 FROM CX_KNOWLEDGE_ACCESS_POLICIES k WHERE k.ENTITY_ID=e.ENTITY_ID)
        AND (e.OWNED_BY_AGENT=i.AGENT_ID OR e.VISIBILITY='PUBLIC'))
    ))
  )
);
CREATE OR REPLACE VIEW CX_AGENT_KNOWLEDGE_READ AS
SELECT e.* FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_TYPE='KNOWLEDGE';
CREATE OR REPLACE VIEW CX_AGENT_KNOWLEDGE_META_READ AS
SELECT m.* FROM KNOWLEDGE_META m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.ENTITY_ID AND e.ENTITY_TYPE=m.ENTITY_TYPE);
CREATE OR REPLACE VIEW CX_AGENT_EMBEDDING_READ AS
SELECT m.* FROM ENTITY_EMBEDDINGS m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.ENTITY_ID AND e.ENTITY_TYPE=m.ENTITY_TYPE);
CREATE OR REPLACE VIEW CX_AGENT_EDGE_READ AS
SELECT m.* FROM ENTITY_EDGES m WHERE EXISTS (
  SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.SOURCE_ID)
  AND EXISTS (SELECT 1 FROM CX_AGENT_ENTITY_READ e WHERE e.ENTITY_ID=m.TARGET_ID);
