-- Additive v4.4.13 policy; no runtime grants or JSON SQL dependencies.
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_PORTAL_KNOWLEDGE_POLICY';
 IF n=0 THEN
  EXECUTE IMMEDIATE 'CREATE TABLE CX_PORTAL_KNOWLEDGE_POLICY (
   POLICY_ID VARCHAR2(128) PRIMARY KEY,
   MODE VARCHAR2(32) NOT NULL CHECK (MODE IN (''KNOWLEDGE_FIRST'',''KNOWLEDGE_ONLY'')),
   ALLOW_MODEL_SUPPLEMENT CHAR(1) NOT NULL CHECK (ALLOW_MODEL_SUPPLEMENT IN (''Y'',''N'')),
   DISCLOSURE_PROFILES_JSON CLOB NOT NULL, VERSION NUMBER(10) NOT NULL CHECK (VERSION>0),
   UPDATED_BY VARCHAR2(128) NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   REASON VARCHAR2(2000) NOT NULL)';
 END IF;
END;
/
MERGE INTO CX_PORTAL_KNOWLEDGE_POLICY p USING (SELECT 'DEFAULT' AS POLICY_ID FROM DUAL) s
 ON (p.POLICY_ID=s.POLICY_ID)
 WHEN NOT MATCHED THEN INSERT
 (POLICY_ID,MODE,ALLOW_MODEL_SUPPLEMENT,DISCLOSURE_PROFILES_JSON,VERSION,UPDATED_BY,REASON)
 VALUES ('DEFAULT','KNOWLEDGE_FIRST','N','[]',1,'SYSTEM_BOOTSTRAP','Initial knowledge-first policy; model disclosure requires explicit configuration');
