-- AI Agent Infra v4.0.1 YashanDB migration
CREATE TABLE EXECUTION_JOBS (
    JOB_ID VARCHAR(64) PRIMARY KEY, JOB_TYPE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(24) NOT NULL, AGENT_ID VARCHAR(64) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL, RESULT_JSON JSON, ERROR_MESSAGE VARCHAR(2000),
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL UNIQUE,
    ATTEMPT_COUNT INTEGER DEFAULT 0 NOT NULL, MAX_ATTEMPTS INTEGER DEFAULT 3 NOT NULL,
    LEASE_TOKEN VARCHAR(128), LEASE_OWNER VARCHAR(128), LEASE_UNTIL TIMESTAMP,
    REQUIRES_APPROVAL CHAR(1) DEFAULT 'Y' NOT NULL, APPROVED_BY VARCHAR(64), APPROVED_AT TIMESTAMP,
    CANCEL_REQUESTED CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT CK_EJ_STATUS CHECK (STATUS IN ('WAITING_APPROVAL','PENDING','RUNNING','RETRY','SUCCEEDED','FAILED','CANCELLED','REJECTED'))
);
CREATE INDEX IDX_EJ_CLAIM ON EXECUTION_JOBS(STATUS, CREATED_AT);
CREATE INDEX IDX_EJ_LEASE ON EXECUTION_JOBS(STATUS, LEASE_UNTIL);

CREATE TABLE EXECUTION_ATTEMPTS (
    ATTEMPT_ID VARCHAR(64) PRIMARY KEY, JOB_ID VARCHAR(64) NOT NULL,
    ATTEMPT_NUMBER INTEGER NOT NULL, LEASE_TOKEN VARCHAR(128) NOT NULL,
    WORKER_ID VARCHAR(128) NOT NULL, STATUS VARCHAR(24) NOT NULL,
    RESULT_JSON JSON, ERROR_MESSAGE VARCHAR(2000),
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_EA_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT UK_EA_ATTEMPT UNIQUE (JOB_ID, ATTEMPT_NUMBER)
);

CREATE TABLE EXECUTION_POLICIES (
    POLICY_ID VARCHAR(64) PRIMARY KEY, POLICY_NAME VARCHAR(128) NOT NULL UNIQUE,
    JOB_TYPE VARCHAR(32), POLICY_JSON JSON NOT NULL, ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE EXECUTION_ARTIFACTS (
    ARTIFACT_ID VARCHAR(64) PRIMARY KEY, JOB_ID VARCHAR(64) NOT NULL,
    ARTIFACT_TYPE VARCHAR(32) NOT NULL, ARTIFACT_URI VARCHAR(1000) NOT NULL,
    CONTENT_HASH VARCHAR(64) NOT NULL, SIZE_BYTES BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_EAR_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE
);

CREATE TABLE EXECUTION_AUDIT (
    AUDIT_ID VARCHAR(64) PRIMARY KEY, JOB_ID VARCHAR(64) NOT NULL,
    ACTION_TYPE VARCHAR(32) NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL,
    DETAIL_JSON JSON, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_EAU_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOBS(JOB_ID) ON DELETE CASCADE
);
COMMIT;

ALTER TABLE HARNESS_META ADD (PARENT_TEMPLATE_ID VARCHAR(64));
ALTER TABLE ENTITY_EMBEDDINGS ADD (EMBEDDING_VERSION INTEGER DEFAULT 1 NOT NULL);

CREATE TABLE EVENT_LOG (
    EVENT_ID VARCHAR(64) PRIMARY KEY, EVENT_TYPE VARCHAR(64) NOT NULL,
    SOURCE_ID VARCHAR(64), SOURCE_TYPE VARCHAR(32), PAYLOAD JSON,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE EVENT_SUBSCRIPTIONS (
    SUB_ID VARCHAR(64) PRIMARY KEY, AGENT_ID VARCHAR(64) NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL, FILTER_PATTERN VARCHAR(500),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_ES_AGENT_EVENT UNIQUE (AGENT_ID, EVENT_TYPE)
);
CREATE TABLE AGENT_CAPABILITY_INDEX (
    CAP_ID VARCHAR(64) PRIMARY KEY, AGENT_ID VARCHAR(64) NOT NULL,
    CAPABILITY VARCHAR(256) NOT NULL, CONFIDENCE NUMERIC(5,4) DEFAULT 1.0000,
    LAST_VERIFIED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE APPROVAL_REQUESTS (
    APPROVAL_ID VARCHAR(64) PRIMARY KEY, ENTITY_TYPE VARCHAR(32) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL, REQUESTED_BY VARCHAR(64) NOT NULL,
    APPROVAL_STATUS VARCHAR(16) DEFAULT 'PENDING' NOT NULL, APPROVED_BY VARCHAR(64),
    APPROVED_AT TIMESTAMP, REJECT_REASON VARCHAR(500), SLA_DEADLINE TIMESTAMP,
    SLA_ESCALATE_TO VARCHAR(64), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE STEP_RETRY_POLICY (
    POLICY_ID VARCHAR(64) PRIMARY KEY, STEP_ID VARCHAR(64) NOT NULL,
    MAX_RETRIES INTEGER DEFAULT 3, BACKOFF_SECONDS INTEGER DEFAULT 5,
    BACKOFF_MULTIPLIER NUMERIC(3,1) DEFAULT 2.0, TIMEOUT_SECONDS BIGINT,
    FALLBACK_ACTION VARCHAR(32) DEFAULT 'FAIL', RETRY_COUNT INTEGER DEFAULT 0,
    LAST_RETRY_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE STEP_EXECUTION_PLAN (
    PLAN_ID VARCHAR(64) PRIMARY KEY, ROOT_PLAN_ID VARCHAR(64) NOT NULL,
    STEP_GROUP_ID INTEGER, STEP_ORDER INTEGER NOT NULL, STEP_ID VARCHAR(64) NOT NULL,
    PARENT_STEP_ID VARCHAR(64), PARALLEL_GROUP INTEGER, STATUS VARCHAR(16) DEFAULT 'PENDING',
    ASSIGNED_AGENT_ID VARCHAR(64), STARTED_AT TIMESTAMP, COMPLETED_AT TIMESTAMP,
    REQUIRES_APPROVAL CHAR(1) DEFAULT 'N', APPROVED_BY VARCHAR(64), APPROVED_AT TIMESTAMP
);
CREATE TABLE TOOL_REGISTRY (
    TOOL_ID VARCHAR(64) PRIMARY KEY, TOOL_NAME VARCHAR(256) NOT NULL,
    TOOL_NAMESPACE VARCHAR(64) NOT NULL, TOOL_VERSION VARCHAR(32), DESCRIPTION VARCHAR(2000),
    INPUT_SCHEMA JSON, OUTPUT_SCHEMA JSON, RUNTIME_REQS JSON,
    TOOL_TYPE VARCHAR(32) DEFAULT 'API', STATUS VARCHAR(16) DEFAULT 'ACTIVE',
    REQUIRES_APPROVAL CHAR(1) DEFAULT 'N', MCP_EXPOSED CHAR(1) DEFAULT 'N',
    CALL_COUNT BIGINT DEFAULT 0, LAST_CALLED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_TR_NAME UNIQUE (TOOL_NAME, TOOL_VERSION)
);
CREATE TABLE TOOL_CHAINS (
    CHAIN_ID VARCHAR(64) PRIMARY KEY, CHAIN_NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(2000), CREATED_BY VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE TOOL_CHAIN_STEPS (
    CHAIN_STEP_ID VARCHAR(64) PRIMARY KEY, CHAIN_ID VARCHAR(64) NOT NULL,
    STEP_ORDER INTEGER NOT NULL, TOOL_ID VARCHAR(64) NOT NULL,
    INPUT_MAPPING JSON, OUTPUT_MAPPING JSON, PARALLEL_GROUP INTEGER, TIMEOUT_SECONDS BIGINT
);
CREATE TABLE COLLAB_MESSAGES (
    MESSAGE_ID VARCHAR(64) PRIMARY KEY, GROUP_ID VARCHAR(64) NOT NULL,
    SENDER_AGENT_ID VARCHAR(64) NOT NULL, RECEIVER_AGENT_ID VARCHAR(64),
    PARENT_MESSAGE_ID VARCHAR(64), THREAD_ID VARCHAR(64), SUBJECT VARCHAR(500),
    BODY CLOB NOT NULL, MESSAGE_TYPE VARCHAR(32) DEFAULT 'TEXT' NOT NULL,
    PRIORITY VARCHAR(16) DEFAULT 'NORMAL' NOT NULL, STATUS VARCHAR(16) DEFAULT 'SENT' NOT NULL,
    ATTACHMENT_ENTITY_ID VARCHAR(64), READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE EVENT_DEAD_LETTER (
    DEAD_LETTER_ID VARCHAR(64) PRIMARY KEY, ORIGINAL_EVENT_ID VARCHAR(64),
    AGENT_ID VARCHAR(64), EVENT_TYPE VARCHAR(128), EVENT_PAYLOAD CLOB,
    FAILURE_REASON VARCHAR(4000), RETRY_COUNT INTEGER DEFAULT 0,
    MAX_RETRIES INTEGER DEFAULT 5, STATUS VARCHAR(32) DEFAULT 'PENDING',
    FIRST_FAILED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, LAST_RETRY_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_EDL_STATUS ON EVENT_DEAD_LETTER(STATUS);
CREATE INDEX IDX_EDL_AGENT ON EVENT_DEAD_LETTER(AGENT_ID);
CREATE TABLE DAG_EXECUTION_LOG (
    LOG_ID VARCHAR(64) PRIMARY KEY, PLAN_ID VARCHAR(64), STEP_ID VARCHAR(64),
    AGENT_ID VARCHAR(64), EXECUTION_STATUS VARCHAR(32), STARTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP, DURATION_MS NUMERIC, ERROR_MESSAGE CLOB,
    RETRY_COUNT INTEGER DEFAULT 0, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_DEL_PLAN ON DAG_EXECUTION_LOG(PLAN_ID);
CREATE INDEX IDX_DEL_STEP ON DAG_EXECUTION_LOG(STEP_ID);
CREATE TABLE ALERT_RULES (
    RULE_ID VARCHAR(64) PRIMARY KEY, RULE_NAME VARCHAR(255) NOT NULL,
    AGENT_ID VARCHAR(128), METRIC_NAME VARCHAR(128) NOT NULL,
    OPERATOR VARCHAR(8) NOT NULL, THRESHOLD NUMERIC NOT NULL,
    ACTION VARCHAR(64) NOT NULL, ACTION_CONFIG JSON,
    ENABLED CHAR(1) DEFAULT 'Y', COOLDOWN_MINUTES INTEGER DEFAULT 30,
    LAST_TRIGGERED_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
