-- Idempotent public product knowledge used by the v4.4.13 Portal.
MERGE INTO ENTITIES e USING (
 SELECT 'CXK_V4413_OVERVIEW' id,'川序 v4.4.13 平台总览' title,'川序是以数据库为权威控制面的企业 AI Agent 管理平台。' summary,'川序（Chuanxu），技术工程名称 AI Agent Infra with DB，是用于部署、运营、治理和协作 AI Agent 的平台，不是单一聊天机器人。v4.4.13 为 Development Candidate，已完成工程验证但仍需独立人工审核。平台统一管理 Human 与 Agent 的身份、权限、注册、凭据、生命周期和归属，提供 Agent Pool、Portal、知识、记忆、任务、工作区、Skills、工具、频道、审批、审计、合规、安全域、模型、部署、监控与大屏。核心原则是数据库权威、最小权限、双主体授权、显式治理与全链路审计。' content FROM DUAL UNION ALL
 SELECT 'CXK_V4413_PORTAL','川序 v4.4.13 Portal 与知识增强问答','Portal 使用授权知识与获准模型提供知识增强问答。','Portal 是用户连接获准 Agent Pool 智能体的入口。问答先验证用户与 Agent 都有 knowledge.read，再检索双方共同可访问的有效知识。命中时由获准 LLM 基于材料生成回答并附引用；未命中且策略允许模型补充时，使用模型通用能力并明确其不是企业政策。输入、知识和完整输出均经过内容安全检查。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_SECURITY','川序 v4.4.13 身份权限与安全治理','Human 与 Agent 均是受治理主体。','用户通过角色、权限覆盖、委派、组织和安全域获得有限访问；Agent 必须注册、激活并验证凭据。平台支持 MFA、会话策略、Portal 连接限制、Agent containment、审批、审计与合规。高影响阻断要求不可变 Action Card 和独立授权确认。v4.4.13 对输入、知识与完整模型输出实施内容检查，并采用失败关闭。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_COLLAB','川序 v4.4.13 Agent 协作与工作管理','平台统一管理 Agent Pool、任务、工作区、协作与扩展。','川序支持 Agent Pool 分配、心跳、休眠、释放、转移、下线与隔离。任务、工作区、上下文链、分支、循环和协作组用于长期工作；频道支持显式成员、提及、动作卡和安全域边界。Skills 与工具支持查看、编辑、下载、停用或软删除，写操作受权限与 CSRF 保护。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_DATA','川序 v4.4.13 数据模型、审计与运维','统一实体、能力注册表与审计构成平台基础。','平台以统一实体保存知识、记忆、任务输出、经验、规格、技能、Agent 与审批，以实体边表达关系。能力开关由 CX_PLATFORM_CAPABILITIES 管理。运维包括预检、迁移、配置、健康检查、模型与 Embedding 治理、审计导出及保留策略。v4.4.13 增加 Agent 诊断、摘要、能力发现和租约 fencing 恢复证据。' FROM DUAL UNION ALL
 SELECT 'CXK_V4413_DB','川序 v4.4.13 YashanDB Enterprise 数据库能力','YashanDB Enterprise 适配器的版本基线与能力。','当前适配器为川序 v4.4.13 YashanDB Enterprise Edition，数据库基线为 YashanDB 23.5.4+。它支持崖山数据库原生连接、Agent 用户配置、统一实体与关系、身份权限、审计、任务、知识、Portal 和能力注册表，并保持与其他适配器一致的上层 API 与治理语义。候选版本已验证初始化、外部 Agent、原生授权与并发、Portal 策略和版本不可变性，但仍不等同于正式发布批准。' FROM DUAL
) s ON (e.ENTITY_TYPE='KNOWLEDGE' AND e.TITLE=s.title)
WHEN MATCHED THEN UPDATE SET e.CONTENT=s.content,e.SUMMARY=s.summary,e.CATEGORY='PRODUCT',e.STATUS='ACTIVE',e.VISIBILITY='PUBLIC',e.IMPORTANCE=10,e.UPDATED_AT=CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN INSERT (ENTITY_ID,ENTITY_TYPE,TITLE,CONTENT,SUMMARY,CATEGORY,STATUS,VISIBILITY,IMPORTANCE) VALUES (s.id,'KNOWLEDGE',s.title,s.content,s.summary,'PRODUCT','ACTIVE','PUBLIC',10);

UPDATE ENTITIES SET CONTENT=CONTENT||' Chuanxu, whose engineering name is AI Agent Infra with DB, is a database-authoritative enterprise platform for deploying, operating, governing, and coordinating AI Agents. Version 4.4.13 is a Development Candidate pending independent human review; it is not a public-release or production-approval claim.' WHERE ENTITY_ID='CXK_V4413_OVERVIEW';
UPDATE ENTITIES SET CONTENT=CONTENT||' Portal checks knowledge.read for both the Human and assigned Agent, retrieves only their shared authorized Knowledge, and lets an approved LLM produce cited answers. When no Knowledge matches, policy may allow a clearly labeled general-model answer. Without a model, authorized extracts remain available.' WHERE ENTITY_ID='CXK_V4413_PORTAL';
UPDATE ENTITIES SET CONTENT=CONTENT||' Humans and Agents are governed principals. Roles, overrides, delegations, organizations, and Security Domains determine access. Registration, credential proof, MFA, session policy, approvals, audit, compliance, and fail-closed content checks protect the platform.' WHERE ENTITY_ID='CXK_V4413_SECURITY';
UPDATE ENTITIES SET CONTENT=CONTENT||' Chuanxu governs Agent Pool assignment and release, durable Tasks and Workspaces, context lineage, Branches, Loops, Channels, Action Cards, Skills, Tools, and Security Domain boundaries.' WHERE ENTITY_ID='CXK_V4413_COLLAB';
UPDATE ENTITIES SET CONTENT=CONTENT||' Unified entities store Knowledge, Memory, outputs, experience, Specs, Skills, Agents, and approvals, while edges preserve relationships. Operations cover preflight, migration, health, model and Embedding governance, retention, diagnostics, and lease-fencing recovery evidence.' WHERE ENTITY_ID='CXK_V4413_DATA';
UPDATE ENTITIES SET CONTENT=CONTENT||' The YashanDB 23.5.4+ adapter provides native connectivity, independent Agent identities, unified entities and relations, database authorization, audit, tasks, Knowledge, Portal, and capability registry under the same Chuanxu governance API.' WHERE ENTITY_ID='CXK_V4413_DB';

MERGE INTO KNOWLEDGE_META km USING (SELECT ENTITY_ID FROM ENTITIES WHERE ENTITY_TYPE='KNOWLEDGE' AND TITLE LIKE '川序 v4.4.13%') e
ON (km.ENTITY_ID=e.ENTITY_ID AND km.ENTITY_TYPE='KNOWLEDGE')
WHEN NOT MATCHED THEN INSERT (ENTITY_ID,ENTITY_TYPE,DOMAIN,TOPIC,DIFFICULTY) VALUES (e.ENTITY_ID,'KNOWLEDGE','PLATFORM','Chuanxu v4.4.13','INTERMEDIATE');
