-- v4.4.14 database-authoritative model and external execution posture.
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_MODEL_CAPABILITIES';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CX_MODEL_CAPABILITIES (
  CAPABILITY_KEY VARCHAR2(128) PRIMARY KEY, STATE VARCHAR2(32) NOT NULL CHECK (STATE IN (''OFF'',''READ_ONLY'',''PROPOSAL_ONLY'',''GOVERNED_EXECUTOR'')),
  VERSION BIGINT DEFAULT 1 NOT NULL CHECK (VERSION>0), MANDATORY CHAR(1) DEFAULT ''N'' NOT NULL CHECK (MANDATORY IN (''Y'',''N'')),
  SECURITY_DOMAIN_ID VARCHAR2(128), SOURCE_DIGEST VARCHAR2(64), SCHEMA_DIGEST VARCHAR2(64), RESOURCE_SCOPE_JSON CLOB DEFAULT ''{}'' NOT NULL,
  EVIDENCE_REF VARCHAR2(256), REASON VARCHAR2(2000) NOT NULL, UPDATED_BY VARCHAR2(128) NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_MODEL_CAPABILITY_HISTORY';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CX_MODEL_CAPABILITY_HISTORY (
  HISTORY_ID VARCHAR2(128) PRIMARY KEY, CAPABILITY_KEY VARCHAR2(128) NOT NULL, FROM_STATE VARCHAR2(32) NOT NULL, TO_STATE VARCHAR2(32) NOT NULL,
  EXPECTED_VERSION BIGINT NOT NULL, EVIDENCE_REF VARCHAR2(256), REASON VARCHAR2(2000) NOT NULL, CHANGED_BY VARCHAR2(128) NOT NULL,
  CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;
 SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='CX_MODEL_EXECUTION_EVIDENCE';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE CX_MODEL_EXECUTION_EVIDENCE (
  EVIDENCE_ID VARCHAR2(128) PRIMARY KEY, REQUEST_ID VARCHAR2(128) NOT NULL, PROVIDER_KEY VARCHAR2(128), MODEL_ID VARCHAR2(256),
  FINISH_STATE VARCHAR2(32) NOT NULL, TOOL_CALL_COUNT INT DEFAULT 0 NOT NULL, STRUCTURED_OUTPUT_STATE VARCHAR2(32) NOT NULL,
  USAGE_JSON CLOB DEFAULT ''{}'' NOT NULL, LATENCY_MS BIGINT DEFAULT 0 NOT NULL, TIMEOUT_STATE VARCHAR2(32) DEFAULT ''NONE'' NOT NULL,
  CANCELLATION_STATE VARCHAR2(32) DEFAULT ''NONE'' NOT NULL, RETRY_COUNT INT DEFAULT 0 NOT NULL, IDEMPOTENCY_KEY VARCHAR2(256),
  EVIDENCE_DIGEST VARCHAR2(64) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;
END;
/
MERGE INTO CX_MODEL_CAPABILITIES d USING (
 SELECT 'model_reasoning' k,'READ_ONLY' s,'Y' m,'Reasoning metadata is visible only as bounded metadata' r FROM DUAL UNION ALL
 SELECT 'structured_output','READ_ONLY','Y','Structured output requires registered schema validation' FROM DUAL UNION ALL
 SELECT 'model_tool_calls','PROPOSAL_ONLY','Y','Model tool calls create proposals by default' FROM DUAL UNION ALL
 SELECT 'mcp_discovery','OFF','N','External MCP discovery requires explicit trust configuration' FROM DUAL UNION ALL
 SELECT 'mcp_execution','OFF','N','External MCP execution is disabled by default' FROM DUAL UNION ALL
 SELECT 'a2a_exchange','OFF','N','External A2A exchange is disabled by default' FROM DUAL UNION ALL
 SELECT 'governed_execution','PROPOSAL_ONLY','Y','High-impact execution requires Human approval' FROM DUAL
) s ON (d.CAPABILITY_KEY=s.k)
WHEN NOT MATCHED THEN INSERT(CAPABILITY_KEY,STATE,MANDATORY,REASON,UPDATED_BY) VALUES(s.k,s.s,s.m,s.r,'SYSTEM_BOOTSTRAP');
