BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CX_TASK_MIGRATION_CONTROL (MIGRATION_KEY VARCHAR2(64) PRIMARY KEY, STATE VARCHAR2(20) NOT NULL, VERSION NUMBER(20,0) DEFAULT 1 NOT NULL, UPDATED_BY VARCHAR2(128) NOT NULL, REASON VARCHAR2(2000) NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
INSERT INTO CX_TASK_MIGRATION_CONTROL(MIGRATION_KEY,STATE,UPDATED_BY,REASON) SELECT 'TASK_STEPS','PREPARING','SYSTEM_BOOTSTRAP','v4.4.15 online task migration' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CX_TASK_MIGRATION_CONTROL WHERE MIGRATION_KEY='TASK_STEPS');
