DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME='TASK_STEPS' AND CONSTRAINT_NAME='FK_STEP_PLAN';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TASK_STEPS ADD CONSTRAINT FK_STEP_PLAN FOREIGN KEY(PLAN_ID) REFERENCES TASK_PLANS(PLAN_ID)';
  END IF;
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
    WHERE TABLE_NAME='CX_TASK_MIGRATION_CONTROL' AND CONSTRAINT_NAME='CK_CX_TASK_MIGRATION_STATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CX_TASK_MIGRATION_CONTROL ADD CONSTRAINT CK_CX_TASK_MIGRATION_STATE CHECK(STATE IN (''PREPARING'',''DUAL_WRITE'',''CUTOVER'',''VERIFIED'',''ROLLBACK''))';
  END IF;
END;
/
UPDATE CX_TASK_MIGRATION_CONTROL SET STATE='VERIFIED',VERSION=VERSION+1,
 UPDATED_BY=USER,REASON='Stable task identity foreign key validated',UPDATED_AT=CURRENT_TIMESTAMP
 WHERE MIGRATION_KEY='TASK_STEPS' AND STATE<>'VERIFIED';
