-- Explicit dynamic MCP exposure; retain previously authorized YashanDB flags.
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='TOOL_REGISTRY' AND COLUMN_NAME='MCP_EXPOSED';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TOOL_REGISTRY ADD (MCP_EXPOSED CHAR(1) DEFAULT ''N'')'; END IF;
END;
/
UPDATE TOOL_REGISTRY SET MCP_EXPOSED='N' WHERE MCP_EXPOSED IS NULL;
ALTER TABLE TOOL_REGISTRY MODIFY (MCP_EXPOSED DEFAULT 'N');
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='TOOL_REGISTRY' AND COLUMN_NAME='MCP_EXPOSED' AND NULLABLE='Y';
  IF n>0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TOOL_REGISTRY MODIFY (MCP_EXPOSED NOT NULL)'; END IF;
  SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE TABLE_NAME='TOOL_REGISTRY' AND CONSTRAINT_NAME='CX415_TOOL_MCP_FLAG';
  IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TOOL_REGISTRY ADD CONSTRAINT CX415_TOOL_MCP_FLAG CHECK (MCP_EXPOSED IN (''Y'',''N''))'; END IF;
END;
/
