-- Portal Agent ownership isolation for multi-node Admin Agent deployments.
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AGENT_REGISTRY ADD (PORTAL_NODE_ID VARCHAR(128))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_AR_PORTAL_NODE ON AGENT_REGISTRY(PORTAL_NODE_ID, STATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
COMMIT;
