-- AI Agent Infra v4.1.0 YashanDB registration objects (all editions)
-- Enterprise governance objects are deployed separately by
-- 8_v4_1_0_governance.sql.

CREATE TABLE AGENT_REGISTRATIONS (
    AGENT_ID VARCHAR2(128) PRIMARY KEY,
    OWNER_REF VARCHAR2(256) NOT NULL,
    RUNTIME VARCHAR2(128) NOT NULL,
    ENVIRONMENT VARCHAR2(128) NOT NULL,
    NODE_ID VARCHAR2(128),
    CAPABILITIES_JSON CLOB,
    CREDENTIAL_VERSION VARCHAR2(64) NOT NULL,
    CREDENTIAL_HASH VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_SEEN_AT TIMESTAMP,
    EXPIRES_AT TIMESTAMP,
    IDEMPOTENCY_KEY VARCHAR2(160) NOT NULL UNIQUE,
    CREATED_BY VARCHAR2(256) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CK_AR_GOV_STATUS CHECK (STATUS IN ('ACTIVE','DISABLED','REVOKED','EXPIRED','DUPLICATE_CONFLICT'))
);

CREATE INDEX IDX_AR_GOV_STATUS ON AGENT_REGISTRATIONS(STATUS, UPDATED_AT);
CREATE INDEX IDX_AR_GOV_LAST_SEEN ON AGENT_REGISTRATIONS(LAST_SEEN_AT);
