-- Only explicitly exposed, active contracts are visible to independent Agents.
CREATE OR REPLACE VIEW CX_MCP_EXPOSED_TOOLS AS
SELECT TOOL_ID, TOOL_NAME, DESCRIPTION, INPUT_SCHEMA, STATUS, MCP_EXPOSED
FROM TOOL_REGISTRY WHERE MCP_EXPOSED='Y' AND STATUS='ACTIVE'
WITH READ ONLY;
GRANT SELECT ON CX_MCP_EXPOSED_TOOLS TO DEEP_SEC_SESSION_ROLE;

-- Bind authority to the authenticated database login, never CURRENT_SCHEMA.
CREATE OR REPLACE TRIGGER CX415_TOOL_MCP_GUARD
BEFORE INSERT OR UPDATE OR DELETE ON TOOL_REGISTRY
FOR EACH ROW
DECLARE owner_name VARCHAR2(128);
BEGIN
  SELECT OWNER INTO owner_name FROM ALL_OBJECTS
  WHERE OBJECT_NAME='CX415_TOOL_MCP_GUARD' AND OBJECT_TYPE='TRIGGER'
    AND OWNER=SYS_CONTEXT('USERENV','CURRENT_USER');
  IF SYS_CONTEXT('USERENV','SESSION_USER')<>owner_name THEN
    IF (INSERTING OR UPDATING) AND :NEW.MCP_EXPOSED='Y' THEN
      RAISE_APPLICATION_ERROR(-20090,'MCP exposure requires control-plane authority');
    END IF;
    IF (UPDATING OR DELETING) AND :OLD.MCP_EXPOSED='Y' THEN
      RAISE_APPLICATION_ERROR(-20090,'An exposed tool requires control-plane authority');
    END IF;
  END IF;
END;
/
