PROMPT ============================================================
PROMPT v4.2.0 Graph Engineering - YashanDB execution graph
PROMPT ============================================================

CREATE TABLE GRAPH_DEFINITIONS (
    GRAPH_ID       VARCHAR2(128) NOT NULL,
    GRAPH_NAME     VARCHAR2(256) NOT NULL,
    DESCRIPTION    VARCHAR2(2000),
    OWNER_REF      VARCHAR2(256) NOT NULL,
    STATUS         VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    METADATA_JSON  CLOB,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_DEFINITIONS PRIMARY KEY (GRAPH_ID),
    CONSTRAINT CK_GRAPH_DEF_STATUS CHECK (STATUS IN ('ACTIVE','DISABLED','ARCHIVED'))
);

CREATE TABLE GRAPH_VERSIONS (
    GRAPH_VERSION_ID VARCHAR2(128) NOT NULL, GRAPH_ID VARCHAR2(128) NOT NULL,
    VERSION_NO NUMBER(10,0) NOT NULL, VERSION_LABEL VARCHAR2(128),
    STATUS VARCHAR2(32) DEFAULT 'DRAFT' NOT NULL, PARENT_VERSION_ID VARCHAR2(128),
    SCHEMA_VERSION VARCHAR2(32) NOT NULL, INPUT_SCHEMA_JSON CLOB, OUTPUT_SCHEMA_JSON CLOB,
    BUDGET_JSON CLOB, DEFINITION_DIGEST VARCHAR2(128), SIGNATURE CLOB,
    VALIDATION_DIAGNOSTICS_JSON CLOB, RISK_LEVEL VARCHAR2(32), ACTOR_ID VARCHAR2(256) NOT NULL,
    REASON VARCHAR2(2000) NOT NULL, SOURCE_RUN_ID VARCHAR2(128), SOURCE_CHECKPOINT_ID VARCHAR2(128),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_VERSIONS PRIMARY KEY (GRAPH_VERSION_ID),
    CONSTRAINT UK_GRAPH_VERSION_NO UNIQUE (GRAPH_ID, VERSION_NO),
    CONSTRAINT FK_GRAPH_VERSION_GRAPH FOREIGN KEY (GRAPH_ID) REFERENCES GRAPH_DEFINITIONS(GRAPH_ID),
    CONSTRAINT CK_GRAPH_VERSION_STATUS CHECK (STATUS IN ('DRAFT','VALIDATED','PUBLISHED','DEPRECATED','ARCHIVED')),
    CONSTRAINT CK_GRAPH_VERSION_RISK CHECK (RISK_LEVEL IS NULL OR RISK_LEVEL IN ('LOW','MEDIUM','HIGH','CRITICAL'))
);

-- YashanDB resolves a self-reference after the table has been created.
ALTER TABLE GRAPH_VERSIONS ADD CONSTRAINT FK_GRAPH_VERSION_PARENT
    FOREIGN KEY (PARENT_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID);

CREATE TABLE GRAPH_NODES (
    NODE_ID VARCHAR2(128) NOT NULL, GRAPH_VERSION_ID VARCHAR2(128) NOT NULL,
    NODE_KEY VARCHAR2(256) NOT NULL, NODE_TYPE VARCHAR2(128) NOT NULL, TYPE_VERSION VARCHAR2(64) NOT NULL,
    CONFIG_JSON CLOB, INPUT_SCHEMA_JSON CLOB, OUTPUT_SCHEMA_JSON CLOB,
    SIDE_EFFECT_CLASS VARCHAR2(32) DEFAULT 'NONE' NOT NULL, CAPABILITY_JSON CLOB,
    RESOURCE_SCOPE_JSON CLOB, BUDGET_JSON CLOB, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_NODES PRIMARY KEY (NODE_ID), CONSTRAINT UK_GRAPH_NODE_KEY UNIQUE (GRAPH_VERSION_ID, NODE_KEY),
    CONSTRAINT FK_GRAPH_NODE_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID),
    CONSTRAINT CK_GRAPH_NODE_EFFECT CHECK (SIDE_EFFECT_CLASS IN ('NONE','DB_TRANSACTIONAL','IDEMPOTENT_EXTERNAL','NON_IDEMPOTENT'))
);

CREATE TABLE GRAPH_EDGES (
    EDGE_ID VARCHAR2(128) NOT NULL, GRAPH_VERSION_ID VARCHAR2(128) NOT NULL,
    SOURCE_NODE_KEY VARCHAR2(256) NOT NULL, TARGET_NODE_KEY VARCHAR2(256) NOT NULL,
    EDGE_KIND VARCHAR2(32) DEFAULT 'NORMAL' NOT NULL, DECISION_TYPE VARCHAR2(64) DEFAULT 'FIXED' NOT NULL,
    CONDITION_JSON CLOB, CONFIG_JSON CLOB, ORDER_INDEX NUMBER(10,0) DEFAULT 0 NOT NULL,
    JOIN_KEY VARCHAR2(256), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_EDGES PRIMARY KEY (EDGE_ID),
    CONSTRAINT FK_GRAPH_EDGE_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID),
    CONSTRAINT UK_GRAPH_EDGE_KEY UNIQUE (GRAPH_VERSION_ID, EDGE_ID)
);

CREATE TABLE GRAPH_ALIASES (
    GRAPH_ID VARCHAR2(128) NOT NULL, ALIAS_NAME VARCHAR2(128) NOT NULL, GRAPH_VERSION_ID VARCHAR2(128) NOT NULL,
    ACTOR_ID VARCHAR2(256) NOT NULL, REASON VARCHAR2(2000) NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_ALIASES PRIMARY KEY (GRAPH_ID, ALIAS_NAME),
    CONSTRAINT FK_GRAPH_ALIAS_GRAPH FOREIGN KEY (GRAPH_ID) REFERENCES GRAPH_DEFINITIONS(GRAPH_ID),
    CONSTRAINT FK_GRAPH_ALIAS_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID)
);

CREATE TABLE GRAPH_TYPE_REGISTRY (
    TYPE_ID VARCHAR2(128) NOT NULL, TYPE_KIND VARCHAR2(32) NOT NULL, TYPE_NAME VARCHAR2(128) NOT NULL,
    TYPE_VERSION VARCHAR2(64) NOT NULL, MANIFEST_JSON CLOB, STATUS VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    ACTOR_ID VARCHAR2(256) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_TYPES PRIMARY KEY (TYPE_ID), CONSTRAINT UK_GRAPH_TYPE_VERSION UNIQUE (TYPE_KIND, TYPE_NAME, TYPE_VERSION),
    CONSTRAINT CK_GRAPH_TYPE_STATUS CHECK (STATUS IN ('ACTIVE','DISABLED','DEPRECATED'))
);

CREATE TABLE GRAPH_COMPILE_PLANS (
    PLAN_ID VARCHAR2(128) NOT NULL, GRAPH_VERSION_ID VARCHAR2(128) NOT NULL, COMPILER_VERSION VARCHAR2(64) NOT NULL,
    DEFINITION_DIGEST VARCHAR2(128) NOT NULL, PLAN_JSON CLOB NOT NULL, PLAN_DIGEST VARCHAR2(128) NOT NULL,
    DIAGNOSTICS_JSON CLOB, RISK_LEVEL VARCHAR2(32) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRAPH_COMPILE_PLANS PRIMARY KEY (PLAN_ID), CONSTRAINT UK_GRAPH_PLAN_VERSION UNIQUE (GRAPH_VERSION_ID),
    CONSTRAINT FK_GRAPH_PLAN_VERSION FOREIGN KEY (GRAPH_VERSION_ID) REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID)
);

CREATE INDEX IDX_GRAPH_VERSION_GRAPH ON GRAPH_VERSIONS(GRAPH_ID, STATUS, VERSION_NO);
CREATE INDEX IDX_GRAPH_EDGE_VERSION ON GRAPH_EDGES(GRAPH_VERSION_ID, SOURCE_NODE_KEY, ORDER_INDEX);
CREATE INDEX IDX_GRAPH_ALIAS_VERSION ON GRAPH_ALIASES(GRAPH_VERSION_ID);
CREATE INDEX IDX_GRAPH_TYPE_LOOKUP ON GRAPH_TYPE_REGISTRY(TYPE_KIND, TYPE_NAME, TYPE_VERSION, STATUS);

PROMPT Creating native YashanDB Property Graph projection...
BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH YASHAN_EXECUTION_GRAPH';
EXCEPTION
    WHEN OTHERS THEN
        IF ABS(SQLCODE) NOT IN (42421, 2187, 2012) THEN
            RAISE;
        END IF;
END;
/

CREATE PROPERTY GRAPH YASHAN_EXECUTION_GRAPH
  VERTEX TABLES (
    GRAPH_DEFINITIONS KEY (GRAPH_ID) LABEL graph_definition
      PROPERTIES (GRAPH_ID, GRAPH_NAME, OWNER_REF, STATUS),
    GRAPH_VERSIONS KEY (GRAPH_VERSION_ID) LABEL graph_version
      PROPERTIES (GRAPH_VERSION_ID, GRAPH_ID, VERSION_NO, STATUS, DEFINITION_DIGEST),
    GRAPH_NODES KEY (GRAPH_VERSION_ID, NODE_KEY) LABEL graph_node
      PROPERTIES (NODE_ID, GRAPH_VERSION_ID, NODE_KEY, NODE_TYPE, TYPE_VERSION, SIDE_EFFECT_CLASS)
  )
  EDGE TABLES (
    GRAPH_EDGES KEY (EDGE_ID)
      SOURCE KEY (GRAPH_VERSION_ID, SOURCE_NODE_KEY) REFERENCES GRAPH_NODES (GRAPH_VERSION_ID, NODE_KEY)
      DESTINATION KEY (GRAPH_VERSION_ID, TARGET_NODE_KEY) REFERENCES GRAPH_NODES (GRAPH_VERSION_ID, NODE_KEY)
      LABEL graph_edge
      PROPERTIES (EDGE_ID, GRAPH_VERSION_ID, EDGE_KIND, DECISION_TYPE, ORDER_INDEX)
  )
/

PROMPT v4.2.0 Graph Engineering YashanDB objects ready.
