export const statusLabels: Record<string, [string, string]> = {
  ACTIVE: ["活动", "Active"],
  RUNNING: ["运行中", "Running"],
  WAITING: ["等待中", "Waiting"],
  READY: ["已就绪", "Ready"],
  RELEASED: ["已放行", "Released"],
  REJECTED: ["已拒绝", "Rejected"],
  PROPOSED: ["待审批", "Proposed"],
  DISABLED: ["已禁用", "Disabled"],
  PENDING: ["待处理", "Pending"],
  FAILED: ["失败", "Failed"],
  PAUSED: ["已暂停", "Paused"],
  COMPLETED: ["已完成", "Completed"],
  QUARANTINED: ["已隔离", "Quarantined"],
  UNKNOWN: ["未知", "Unknown"],
  COMPLIANT: ["合规", "Compliant"],
  DEGRADED: ["降级", "Degraded"],
  NON_COMPLIANT: ["不合规", "Non-compliant"],
  NORMAL: ["正常", "Normal"],
  PENDING_ACTIVATION: ["待激活", "Pending activation"],
  NEVER_SEEN: ["未观察", "Never observed"],
  ONLINE: ["在线", "Online"],
  IDLE: ["空闲", "Idle"],
  STALE: ["已失效", "Stale"],
  OFFLINE: ["离线", "Offline"],
  BOUNDARY_ONLY: ["仅边界证据", "Boundary only"],
  SIGNED_ADAPTER: ["已签名适配器", "Signed adapter"],
  MANAGED_RUNTIME: ["受管运行时", "Managed runtime"],
  SCOPE_LIMITED: ["范围受限", "Scope limited"],
  REMEDIATING: ["整改中", "Remediating"],
  ACKNOWLEDGED: ["已确认", "Acknowledged"],
  APPROVED: ["已批准", "Approved"],
  DENIED: ["已拒绝", "Denied"],
  EXPIRED: ["已过期", "Expired"],
  REVOKED: ["已撤销", "Revoked"],
  ACKED: ["已确认", "Acknowledged"],
  DEAD_LETTER: ["死信", "Dead letter"],
  INACTIVE: ["非活动", "Inactive"],
  ERROR: ["错误", "Error"],
  PENDING_CONFIRMATION: ["待确认", "Pending confirmation"],
  CANCELLED: ["已取消", "Cancelled"],
  REVIEW_REQUIRED: ["需要复核", "Review required"],
  DRAFT: ["草稿", "Draft"],
  WORKING_REVISION: ["工作修订", "Working revision"],
  APPROVED_BASELINE: ["已批准基线", "Approved baseline"],
  AMENDMENT: ["修订", "Amendment"],
  SUPERSEDED_BASELINE: ["已替代基线", "Superseded baseline"],
  RETIRED: ["已退役", "Retired"],
  VALID: ["有效", "Valid"],
  ENABLED: ["已启用", "Enabled"],
  APPROVAL_ONLY: ["仅审批", "Approval only"],
  INITIALIZED: ["已初始化", "Initialized"],
  ACTIVATION_PENDING: ["待激活", "Activation pending"],
  CONFIGURED_ONLY: ["仅已配置", "Configured only"],
  VERIFIED: ["已验证", "Verified"],
  AGENT_VERIFIED: ["智能体验证", "Agent verified"],
  GATEWAY_VERIFIED: ["网关验证", "Gateway verified"],
  HIGH_AVAILABILITY_NOT_READY: ["高可用尚未就绪", "High availability not ready"],
  HIGH_AVAILABILITY_READY: ["高可用已就绪", "High availability ready"],
  SYSTEM_PROTECTED: ["系统保护", "System protected"],
  RESTRICTED: ["受限", "Restricted"],
  CANDIDATE: ["候选", "Candidate"],
  OBSERVATION: ["观察中", "Observation"],
  HEALTHY: ["健康", "Healthy"],
  STAGED: ["已暂存", "Staged"],
  PUBLISHED: ["已发布", "Published"],
  NOT_CONFIGURED: ["未配置", "Not configured"],
  NOT_READY: ["未就绪", "Not ready"],
  CONTROLLED: ["受控启用", "Controlled"],
  DELIVERED: ["已送达", "Delivered"],
  READ: ["已读", "Read"],
  DELETED: ["已删除", "Deleted"],
  OFF: ["已关闭", "Off"],
  PROPOSAL_ONLY: ["仅提案", "Proposal only"],
  GOVERNED_EXECUTOR: ["受治理执行", "Governed executor"],
  PREPARING: ["准备中", "Preparing"],
  DUAL_WRITE: ["双写中", "Dual write"],
  CUTOVER: ["切换中", "Cutover"],
  ROLLBACK: ["回滚中", "Rollback"],
  REVIEWING: ["审核中", "Reviewing"],
  ARCHIVED: ["已归档", "Archived"],
  CONFLICTED: ["存在冲突", "Conflicted"],
  MIGRATED: ["已迁移", "Migrated"],
  MIGRATING: ["迁移中", "Migrating"],
  PREFLIGHT_FAILED: ["预检失败", "Preflight failed"],
  PREFLIGHT_PASSED: ["预检通过", "Preflight passed"],
  DRAIN: ["排空", "Drain"],
  REQUIRED: ["必需", "Required"],
  OPTIONAL: ["可选", "Optional"],
  DUPLICATE_CONFLICT: ["重复冲突", "Duplicate conflict"],
  READ_ONLY: ["只读", "Read only"],
  MERGED: ["已合并", "Merged"],
  STOPPED: ["已停止", "Stopped"],
  TIMEOUT: ["已超时", "Timed out"],
  REMEDIATED: ["已整改", "Remediated"],
  DISCOVERED: ["已发现", "Discovered"],
  ANALYZED: ["已分析", "Analyzed"],
  AUTHORIZED: ["已授权", "Authorized"],
  EXECUTING: ["执行中", "Executing"],
  VERIFYING: ["验证中", "Verifying"],
  VERIFY_FAILED: ["验证失败", "Verification failed"],
  COMPENSATED: ["已补偿", "Compensated"],
  SUSPENDED: ["已挂起", "Suspended"],
  REVIEW: ["审核中", "Under review"],
  APPLIED: ["已应用", "Applied"],
  VALIDATED: ["已校验", "Validated"],
  VALIDATING: ["校验中", "Validating"],
  KNOWN: ["已知", "Known"],
  FALSE_POSITIVE: ["误报", "False positive"],
  ESCALATED: ["已升级处理", "Escalated"],
  DISPATCHING: ["派发中", "Dispatching"],
  IMPLEMENTED: ["已实施", "Implemented"],
  EXCEPTION_APPROVED: ["例外已批准", "Exception approved"],
  SKIPPED: ["已跳过", "Skipped"],
  DONE: ["已完成", "Done"],
  RECEIVED: ["已接收", "Received"],
  PROCESSING: ["处理中", "Processing"],
  PROCESSED: ["已处理", "Processed"],
  DUPLICATE: ["重复", "Duplicate"],
  VERIFIED_BUILTIN: ["内置验证通过", "Verified built-in"],
  INVALID: ["无效", "Invalid"],
  ROLLED_BACK: ["已回滚", "Rolled back"],
  COMMITTED: ["已提交", "Committed"],
  DEADLOCKED: ["发生死锁", "Deadlocked"],
  WAITING_APPROVAL: ["等待审批", "Waiting for approval"],
  RETRY: ["重试中", "Retry"],
  UNAVAILABLE: ["不可用", "Unavailable"],
  UNOBSERVED: ["未观测", "Unobserved"],
  UNVERIFIED: ["未验证", "Unverified"],
  UNSUPPORTED: ["不支持", "Unsupported"],
  DEPRECATED: ["已弃用", "Deprecated"],
  OPEN: ["待处理", "Open"],
  CLOSED: ["已关闭", "Closed"],
  RESOLVED: ["已解决", "Resolved"],
  BLOCKED: ["受阻", "Blocked"],
  IN_PROGRESS: ["进行中", "In progress"],
  OFFERED: ["待接收", "Offered"],
  CLAIMED: ["已领取", "Claimed"],
  PREPARED: ["已准备", "Prepared"],
  SENDING: ["发送中", "Sending"],
  SENT: ["已发送", "Sent"],
  PASS: ["通过", "Pass"],
  FAIL: ["失败", "Fail"],
  PENDING_REVIEW: ["待审核", "Pending review"],
  NEEDS_REVIEW: ["需要审核", "Needs review"],
  SUPERSEDED: ["已替代", "Superseded"],
  DRAINING: ["排空中", "Draining"],
  DRAINED: ["已排空", "Drained"],
  CANCEL_REQUESTED: ["已请求取消", "Cancellation requested"],
  SUCCESS: ["成功", "Success"],
  SUCCEEDED: ["已成功", "Succeeded"],
  WARNING: ["警告", "Warning"],
  NOT_APPLICABLE: ["不适用", "Not applicable"],
};

// Translate display values only; API values and raw evidence remain unchanged.
export function statusLabel(value: unknown, text: (zh: string, en: string) => string): string {
  if (value === null || value === undefined || value === "") return "-";
  const label = statusLabels[String(value).trim().toUpperCase()];
  return label ? text(label[0], label[1]) : String(value);
}
